Backport Check for 2 different Xcode locations (#9861) to release/5.0
dotnet/arcade pull request #10051
Opened 2022-07-18 17:17 UTC by jonfortescue

Backport 14da5af378931c944abaf3318315f88e7b710489 to release/5.0.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2022-07-18 17:27 UTC, garath approved these changes

2022-07-18 17:27 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh
> +#!/bin/bash
I don't think just copying a file into this repo is going to solve that issue, there seems to be a lot more history

Release 5.0 has ios-helix-job-payload.sh [which gets renamed to xharness-runner.ios.sh](https://github.com/dotnet/arcade/commits/29ae7a00fff56255b343fdce87811ec7dbe8d5bf/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.ios.sh?browsing_rename_history=true&new_path=src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh&original_branch=main) and later this file name.  Without the SDK changes to include and use this script I don't think this solves your problem.

2022-07-18 17:31 UTC, MattGal requested changes
I think this either needs to take in subsequent Xharness changes or be abandoned.

2022-07-18 18:02 UTC, jonfortescue commented
the failing build does indeed indicate that it does not. Okay, I'll dive more deeply into this; was hoping just cherry-picking that commit would be enough.

2022-07-19 08:45 UTC, premun commented
The way I was backporting the XHarness was copying the whole `xharness-runner` directory and then 2 XHarness MSBuild tasks from Helix SDK. I can do this for release 5.0 if we need this

2022-07-19 21:49 UTC, jonfortescue commented
@premun I would appreciate that!

2022-07-19 21:50 UTC, closed without merging