Update Xunit to 2.4.2
dotnet/arcade pull request #10512
Opened 2022-08-19 17:31 UTC by ericstj

2022-08-19 19:28 UTC, ViktorHofer approved these changes

2022-08-22 07:19 UTC, ViktorHofer commented
/azp run arcade-ci

2022-08-22 12:49 UTC, ViktorHofer commented
@dotnet/dnceng can you please help with diagnosing the test failures? I spent some time looking at the binlogs to see if the work items are submitted incorrectly but as the XUnitWorkItems feature is something very unfamiliar to me, I don't have any clues.

All work items fail with the following error:
```
✖DownloadError: Unable to download https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c914a8/nuget/v3/flat2/xunit.runner.console/2.4.2/xunit.runner.console.2.4.2.nupkg after retrying. Execution may fail as a result.
```

2022-08-22 13:03 UTC, dkurepa commented
Looking at the logs, I think it's failing on trying to get `xunit.runner.console 2.4.2` from the [dotnet-eng](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng), but it's not available, I'm only seeing `2.4.2-pre**` packages. Should there be a `xunit.runner.console 2.4.2` in there too?

2022-08-22 13:06 UTC, ViktorHofer commented
Yes, it was just recently published to nuget.org (two weeks ago). Can you please add the package to the dotnet-eng feed?

2022-08-22 14:05 UTC, dkurepa commented
We usually add packages like this to the dotnet-public feed. I just checked and it's already there. Is it possible to fetch it from there?

2022-08-22 15:28 UTC, ViktorHofer commented
If the prerelease versions were pushed to dotnet-eng as well, the we should also push the stable version there.

For the future we can for sure avoid having these in dotnet-eng.

2022-08-22 16:46 UTC, dkurepa commented
I added 2.4.2 to dotnet-eng, should be unblocked now

2022-08-22 17:01 UTC, ViktorHofer commented
/azp run arcade-ci

2022-08-22 17:35 UTC, ViktorHofer submitted a review, later dismissed

2022-08-22 17:37 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/Readme.md
> +    <XUnitRunnerVersion>2.4.2/XUnitRunnerVersion>
Typo: Deleted a >

2022-08-22 17:37 UTC, MattGal requested changes
Should fix the typo before merging.

2022-08-22 17:41 UTC, ViktorHofer commented on src/Microsoft.DotNet.Helix/Sdk/Readme.md
> +    <XUnitRunnerVersion>2.4.2/XUnitRunnerVersion>
Thanks, fixed the typo.

2022-08-22 17:43 UTC, MattGal approved these changes

2022-08-22 17:44 UTC, ViktorHofer approved these changes

2022-08-22 17:49 UTC, dougbu approved these changes

2022-08-22 18:54 UTC, merged