add Internal.Utilities project
dotnet/arcade pull request #11227
Opened 2022-10-11 11:02 UTC by oleksandr-didyk

Related issue: https://github.com/dotnet/source-build/issues/3040

Adding an internal utilities library for re-used code

Copied in `VersionDetailsParser` from Darc and `FileSystem` from Arcade Services + will replace existing implementation with this library after the PR is accepted

2022-10-11 18:48 UTC, ChadNedzlek requested changes

2022-10-11 18:48 UTC, ChadNedzlek commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
Many of these path operations really don't need to be abstracted. I'm not sure I see the point of adding a layer that's calling a pure logic method underneath. Sure, the things that actually DO file operations, yeah, but anything on "Path" should just be used directily.

2022-10-11 21:34 UTC, ChadNedzlek commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public void WriteToFile(string path, string content)
Should we have an async version of this? I'm not sure how big content is expected to be.

2022-10-11 21:36 UTC, ChadNedzlek commented on src/Microsoft.Dotnet.Internal.Utilities/IFileSystem.cs
> +        _fileInfo = new(path);
I'd like the "new FileInfo" here.  Took me a minute to figure out what we were "newing" up.  Much like var, new should only be used when the type is clear on the line.

2022-10-11 21:38 UTC, ChadNedzlek commented
"Utilities" is a _really_ vague name for an assembly. "SourceBuildInfo" and "DependnecyDetail" don't feel like utilities to me.  Most of this code (other than the FileSystem stuff), feels like it's really source build stuff, so should probably be in an assembly dedicated to source build.

2022-10-12 10:01 UTC, premun commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
Fair point. We could remove all methods without file system side effects. Only risk is that it might cause failures in unit tests when run on Windows vs Linux.

2022-10-12 10:03 UTC, premun commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public void WriteToFile(string path, string content)
The goal of this class/layer is abstracting away FS calls to enable unit testing. My understanding is that this class was created quite some time ago and methods were added one by one as people needed to mock them.

So, we're not aiming to create a super long swiss knife for the whole IO library and whether you do or don't need async is a decision made by whoever added these.

2022-10-12 10:05 UTC, premun commented
> Most of this code (other than the FileSystem stuff), feels like it's really source build stuff

It's actually Maestro stuff around `Version.Details.xml` files. Code used by both source-build and DarcLib. That's roughly a TLDR why we need this library.

The naming should be a subject to discussion on this PR so it's good you're bringing this up. Utilities doesn't sound too off though for classes that are helpers around some Arcade/Maestro concepts.

2022-10-13 08:34 UTC, oleksandr-didyk commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
Should we then remove them is the risk of test failure is not worth it?

2022-10-13 08:37 UTC, premun commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
I'd check how many are if there are many and fix them right away, if it's not too many?

2022-10-13 08:38 UTC, oleksandr-didyk commented on src/Microsoft.Dotnet.Internal.Utilities/IFileSystem.cs
> +        _fileInfo = new(path);
Makes perfect sense, added

2022-10-13 08:41 UTC, oleksandr-didyk commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
5 it seems, which should not be too many. Furthermore, these changes only copy in the code from Arcade Services, so in this particular PR we don't need to change a lot

2022-10-14 08:12 UTC, premun commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
There won't be much in arcade-services. I only copied the class recently and am the only user there so it's fine.

2022-10-26 08:41 UTC, oleksandr-didyk commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
@premun so I can remove all of the `Path` operations?

2022-10-26 08:45 UTC, oleksandr-didyk commented
@ChadNedzlek would you have any examples of what you think the library should be named based on @premun 's answer?

2022-10-26 08:51 UTC, ChadNedzlek commented
It seems like if it's about virtual mono repo stuff, that should probably be reflected in the name.  The FileSystem stuff could probably be in it's own assembly with something like "Microsoft.Internal.DotNet.FileSystem.Abstractions" or something like that.  It feels distinctly different than the other stuff, in that's it's pretty much just a file system abstraction, without any real product identity/logic in it.  The dependency stuff feels different enough to me that it should be in something else. Maybe Microsoft.Internal.DotNet.VirtualMonoRepo or something?

2022-10-26 08:52 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/Models/DependencyDetail.cs
> +namespace Microsoft.DotNet.Internal.Utilities;
To my knowledge, arcade follows runtime style. And runtime has explicitly decided against file scoped namespaces.  So we should stick with that style.

2022-10-26 08:52 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/Models/DependencyDetail.cs
> +        Locations = new List<string>();
Why not do this in the initializer and save having to write a constructor at all?

2022-10-26 08:53 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities.Tests/Microsoft.DotNet.Internal.Utilities.Tests.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
runtime/arcade does not use implicit usings. Please follow existing style.

2022-10-26 08:55 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/MsBuildPropsFile.cs
> +#nullable enable
Since this is an entirely new assembly with no dependencies, lets not piecemeal the nullable file by file.

2022-10-26 08:56 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
Can this one be an extension method? It seems like everyone will always implement it the same way (load an XmlDocument, parse it, and then call the other overload)

2022-10-26 08:58 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    public const string ShaElementName = "Sha";
I personally don't like this level of constification... it means when I'm reading a line, I have to bounce up here to figure out what the value actually is.  Not every string, especially strings that are just `ThingName = "Thing"` needs to be a const, I'm not sure what it adds other than making a reviewer/reader have to scroll up to get the real value, and making this class much longer to define all these consts that are used only 1 (or often zero) times.

2022-10-26 09:00 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +                throw new ParserException($"Dependencies cannot be top-level and must belong to a group such as {ProductDependencyElementName}");
This error message doesn't seem right.

2022-10-26 09:05 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +public interface IVersionDetailsParser
I'm curious what other implementations of this class might exist.  It's almost pure logic with nothing that would every need to be mocked or use some other weird dependency, and the XMLness is baked into the interface, so it's not like we could have a "JsonVersionDetailsParser" or anythign.  Do we actually need an interface for this?

2022-10-26 09:05 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    public const string ShaElementName = "Sha";
These are being used in DarcLib from other classes as well:
https://github.com/dotnet/arcade-services/search?q=ShaElementName

2022-10-26 09:06 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(XmlDocument document, bool includePinned = true);
Have we considered using "XDocument" rather than XmlDocument? It's a bit "newer" and I think it's API is a little easier to use in some places.

2022-10-26 09:07 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
These methods were extracted from internals of DarcLib which uses both of these. We will need to mock these eventually when testing the code there and that won't be possible with an extension method.

We can implement it on the interface but I would personally stay away from that feature.

Regardless, I don't think we will have more implementations than this one as this one is specifically here for easier re-use and the interface for testability. So I don't think it's a big issue because there won't be any other implementation doing the same.

2022-10-26 09:09 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +            if (dependency.NodeType == XmlNodeType.Comment || dependency.NodeType == XmlNodeType.Whitespace)
@ChadNedzlek this is not a new implementation, it's just extracting code from within DarcLib that is not being tested anywhere. I don't think it's a subject of this PR to change behaviour nor I would be bold enough to do it in DarcLib in its current state.

2022-10-26 09:10 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +public interface IVersionDetailsParser
https://github.com/dotnet/arcade-services/search?q=IVersionDetailsParser

2022-10-26 09:12 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(XmlDocument document, bool includePinned = true);
We have not considered anything, we're just copying code to re-use it between `arcade` and `arcade-services`.

I'd keep this change strictly moving code only. We can improve later.

2022-10-26 09:13 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(XmlDocument document, bool includePinned = true);
https://github.com/dotnet/arcade-services/commit/1132ca0b7e3ecfbd81a54a3dd09d631d5bd16500

2022-10-26 09:14 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +public interface IVersionDetailsParser
Making DarcLib testable is a goal too

2022-10-26 20:28 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
Why would you specifically need to mock the string one with something other than "make an XML document out of it"? You could easily mock the other method and the extension method would call it.

2022-10-27 06:57 UTC, premun commented
> It seems like if it's about virtual mono repo stuff

It's not. This class is used by:
- Maestro (DarcLib) when working with repo dependencies
- Source-Build (which will be in Arcade)
- dotnet/installer (tarball generation)
- VMR (in installer and DarcLib)

I'd say it's pretty generic and that makes it a good candidate as we need to share this between 3 repos.

> The FileSystem stuff could probably be in it's own assembly with something like "Microsoft.Internal.DotNet.FileSystem.Abstractions" or something like that. It feels distinctly different than the other stuff, in that's it's pretty much just a file system abstraction, without any real product identity/logic in it.

Sure, but I guess there will be more stuff like this that we already share between repos (I remember @missymessa and @michellemcdaniel might have some tips for things that they mentioned they copy around).

2022-10-27 07:02 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
But can you explain why? Why would you split logic belonging to this single class into 2 different classes?
Somehow you mind that there's two methods that people would have to implement (even though we don't expect more implementations) but adding a new static class (that's very hard to test) would be fine?

And testing this? You'd have to always provide a full XML document? (see my other comment explaining why I think that's not a good idea)

2022-10-27 07:16 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +public interface IVersionDetailsParser
There are couple of reasons why I don't understand why you propose this:

1. This class would have to be made testable so that it's not using real file system (and that would be quite hard) OR you would have to keep writing XMLs onto the file system during tests and that is a very error prone, slow and quite lengthy operation.
2. I think it's much easier to mock strong-typed declaration of the `DependencyDetail` class rather than adding files / interpolated XML multi-line strings in your tests.
3. This class abstracts away the work with the XMLs (one of principles of OOP - encapsulation). If the XML changes (attribute names, how we organize source-build tags...), or we start using props files instead or whatever... you won't have to go and change manually XMLs in all tests. You will keep using the `DependencyDetail` classes and not worry about implementation details.
4. We already use `DependencyDetail` mocks in many `arcade-services` tests and we have factories for it. E.g. https://github.com/dotnet/arcade-services/blob/3a8b32b60e6030e921756dd7ae8865d72fbc8898/src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs#L1445-L1460 You can also see how much XML you would have to prepare for a test like this. You would end up creating a factory for the XML to which you would have to provide everything that you provide to the `DependencyDetail` class.

I really don't understand where you're coming from but I guess you must have an angle that I don't see. Can you help me understand why you propose this? (same with the extension method).

2022-10-27 07:24 UTC, premun commented on src/Microsoft.Dotnet.Internal.Utilities/FileSystem.cs
> +    public string PathCombine(string path1, string path2) => Path.Combine(path1, path2);
So.. the issue is that many tests just mock `PathCombine` to `$"{first}/{second}" and the whole testing can than expect that we use UNIX style paths.

If we remove these, the tests might start working different way on Windows / Linux. We already have a tests in `arcade-services` and `arcade` (and I think some other repos) that don't run well on both Windows / Linux for this exact reason.
Example: https://github.com/premun/arcade-services/blob/prvysoky/testable-vmr/src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrUpdaterTests.cs

I would not say that it's problematic to keep these but I also think it's not the end of the world to fix the tests. However, we're talking about what - 4 lines of code here? Furthermore, I think it's nice if you can fully remove the `System.IO` using from classes as it means there's no real IO operations left.

But I don't have a strong opinion on this.

2022-10-27 19:57 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
You have to provide a full document either way, the only implementation you'd be testing requires it.  And if you are mocking stuff, you can just mock the single method that's real, rather than having to mock both (since you wouldn't know which the stuff was calling, or you'd have to change the tests a bunch if you wanted to use the other inside).

You could use a default interface method if you really were worried about having multiple classes, but to me (and to most of runtime) having "interface IThing" that has some helper methods on "static class Thing" is a pretty normal pattern, and reduces the burden of having to have every implementation implement more methods. It also reduces testing if we ever do create a second copy of the interface, because there would only be a single implementation of the extension method that needs to be tested, rather than two for every implementer.

Why is a static class any harder to test than the instance implementation of it? It would be easy, you'd make a Mock<IVersionDetailsParser>, and then call the extension method on it and make sure it produced the correct XML document.  Right now it's MUCH harder to test the overload, since you can't actually isolate the "string" version of the method, so you have to duplicate all the tests for the XML tests to the string overload, and try to ensure they have the same behaviors.

2022-10-27 19:59 UTC, ChadNedzlek commented
> Sure, but I guess there will be more stuff like this that we already share between repos

We shouldn't create one giant "all the random stuff we want to share assembly".  If we end up with more stuff related to this versiony/dependency flowy stuff, it can go in whatever assembly this is. If it's some other code, unrelated to that, then it should go in its own assembly.

My understanding was that all four of those things is VMR, so maybe my understanding is wrong.  Maybe "DependencyManagement" or something else, but it seems like some sort of concept should be able to be wrapped around it.

2022-10-31 08:37 UTC, premun commented on src/Microsoft.DotNet.Internal.Utilities/VersionDetailsParser.cs
> +    IList<DependencyDetail> ParseVersionDetailsXml(string fileContents, bool includePinned = true);
> You have to provide a full document either way, the only implementation you'd be testing requires it.

Yes, but only once when testing this one class responsible for XML (so it's kind of understandable there will have to be some XML somewhere) not every time we test any class that depends on this!

> And if you are mocking stuff, you can just mock the single method that's real, rather than having to mock both (since you wouldn't know which the stuff was calling, or you'd have to change the tests a bunch if you wanted to use the other inside).

Why would you need to mock both? The class that you're testing usually just calls one of these so you mock that one? So having the code here or in an extension + having 1 mock is the same amount of code?

Also if you check the code, what you propose means you would have to do then really crazy things instead of just mocking a very simple method? A simple example: 
I have a method calling several times into this logic, I want to be able to return different sets of `DependencyDetail`.
I could easily setup a mock that does things based on the contents of `fileContents` rather than xpathing the `XmlDocument` to see what's inside..

> You could use a default interface method

Yes, this is what I am proposing above as a different solution but it's a very nasty thing once inheritance comes into play as child class can't call into this method easily since it's not on the parent but on the iface. I heard even Roslyn guys say that this feature went sideways. Personally, I use it for pure functions only and this case is not a pure function.

> Why is a static class any harder to test than the instance implementation of it? 

Not the method itself but code dependent on this..

> Right now it's MUCH harder to test the overload, since you can't actually isolate the "string" version of the method, so you have to duplicate all the tests for the XML tests to the string overload, and try to ensure they have the same behaviors.

The piece of code we're talking about is not going away with moving it into the extension. Having it here is not "MUCH harder" as it would also not go away. It's just MUCH harder to test code dependent on this.

2022-10-31 08:40 UTC, premun commented
I like `Microsoft.DotNet.DependencyManagement` or `Microsoft.DotNet.DependencyManagement.Utilities`

2022-11-01 10:43 UTC, oleksandr-didyk commented
Hey @ChadNedzlek and @premun, just to outline a few things so that this PR can get merged:

  - This PR is just moving code from Arcade Services to Arcade, so I would be strongly against introducing any new changes to the existing logic. I would like to merge this PR, replace existing usage of moved code in Arcade Services with this library and afterwards we can return to discussions started here
  - I will of course comply with all style changes requested by Chad
  - The library name can be changed to the proposed `Microsoft.DotNet.DependencyManagement` if its A-OK for everyone

Please let me know if this is acceptable to you. Thanks!

2022-11-01 13:51 UTC, oleksandr-didyk commented on src/Microsoft.DotNet.Internal.Utilities/Models/DependencyDetail.cs
> +namespace Microsoft.DotNet.Internal.Utilities;
Of course, my bad, changed

2022-11-01 13:51 UTC, oleksandr-didyk commented on src/Microsoft.DotNet.Internal.Utilities.Tests/Microsoft.DotNet.Internal.Utilities.Tests.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
My bad, fixed

2022-11-01 13:51 UTC, oleksandr-didyk commented on src/Microsoft.DotNet.Internal.Utilities/MsBuildPropsFile.cs
> +#nullable enable
Fair point, changed

2022-11-01 17:15 UTC, missymessa commented
Is there a reason this code is being moved to Arcade? Is something in Arcade going to be consuming this code now?

2022-11-01 18:06 UTC, missymessa commented
Ah, I see this PR is related to the thread that was started last month. 

Here's my opinion (and it's just an opinion, so take it or leave it :D): Functionality in Arcade should be used by the product repos. If that's the case here (and based on the list Premek provided, that looks like it may be the case), if there are things in Arcade that will consume this code, can we also include that refactor in this PR? If the things that will consume the code changes are in consuming repos, can we make sure that we have issues to handle that refactor? 

My concerns with this work are 1) we may be moving functionality that is only used by dnceng into Arcade, which is shared infra for product repos (as noted by Premek, it sounds like there are product repos that would use this functionality, so this may be a moot concern), and 2) this code will be orphaned if nothing consumes it (just want to make sure that once this code is migrated that it will be used by repos that aren't owned by dnceng).

2022-11-02 10:10 UTC, premun commented
> I think Arcade was suggested as the best place to put the code in question so it can be re-used throughout multiple repos, including arcade services (as the repos in question would get updates through the dependency flow)

@oleksandr-didyk isn't also one of the goals to use this logic directly in Arcade for the PvP stuff? This would be used then in every repo through the SourceBuild leg?

@missymessa additionally, this code will be used by `dotnet/arcade-services` and potentially `dotnet/installer`.

2022-11-02 16:13 UTC, missymessa commented
arcade-services is one of our team's projects which is where this code is originating from, so the fact that this code will once again be used by arcade-services isn't a selling point, in my opinion, to move it to another repo, especially once that was created to support common infra for the product repos.

2022-11-02 16:19 UTC, premun commented
@missymessa as noted above - I think it will be used for SourceBuild legs which will be running Arcade YAML templates in every product repo (and the SB tooling is in `arcade`) so `arcade` needs this and so the other repos. I think this is the reason we started all of this (Alex needs these classes from DarcLib in Arcade).

I think it's better to have this code in `arcade` and flow it to `arcade-services` as opposed the other way because `arcade-services` is .NET 6.0 so it would have to do something special just to build 7.0/8.0 things. It's better to multi-target 6/8 from Arcade.

2023-03-14 11:18 UTC, oleksandr-didyk commented
Closing due to the PR being quite outdated + new re-org

2023-03-14 11:18 UTC, closed without merging