Use new .NET logo in NuGet packages.
dotnet/arcade pull request #11482
Opened 2022-11-02 11:26 UTC by teo-tsirpanis

Fixes dotnet/runtime#77695.

2022-11-02 14:20 UTC, riarenas requested changes
Waiting for confirmation in the original issue that this is something we want to do.

2023-09-28 18:18 UTC, bricelam commented
Please do this! The current purple is so ugly and goes against [everything](https://github.com/dotnet/brand) @BethMassi and team worked so hard to create

2023-10-12 09:09 UTC, akoeplinger commented
The consensus in https://github.com/dotnet/runtime/issues/77695 was that the purple logo is the correct one. I updated the PR with the official logo png from https://github.com/dotnet/brand/blob/main/logo/dotnet-logo.png

2023-10-12 09:10 UTC, akoeplinger approved these changes

2023-10-16 08:34 UTC, ViktorHofer approved these changes

2023-10-16 08:34 UTC, merged