Manage the ceapex PAT for OneLocBuild
dotnet/arcade pull request #12020
Opened 2022-12-23 00:12 UTC by jonfortescue

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2022-12-27 20:08 UTC, garath requested changes
I also ran this manually to force-rotate.

2022-12-27 20:08 UTC, garath commented on .vault-config/product-builds-engkeyvault.yaml
> +      scopes: packaging_read
```suggestion
      scopes: packaging
```

Read-only scope doesn't use the suffix.

2023-01-03 13:17 UTC, riarenas commented
Would you mind moving this PAT to https://github.com/dotnet/arcade/blob/main/.vault-config/product-builds-dnceng-pipeline-secrets.yaml? Let's not add new PATs used by automation to engKeyvault

2023-01-04 00:42 UTC, jonfortescue commented
@riarenas I don't mind moving it at all and indeed considered that I should do so. Will be taking care of that.

2023-01-05 00:42 UTC, jonfortescue commented
Just to clarify @riarenas, this isn't a new PAT but rather an existing one that was previously in engkeyvault. Still moving it bc it should be moved.

2023-01-05 00:54 UTC, jonfortescue commented
In order to migrate this, I'll also need to migrate BotAccount-dotnet-bot-repo-PAT. I'll be doing that shortly.

2023-01-05 14:46 UTC, riarenas commented
> Just to clarify @riarenas, this isn't a new PAT but rather an existing one that was previously in engkeyvault. Still moving it bc it should be moved.

Ah, that makes sense. Thanks for moving it anyways!

2023-01-05 18:27 UTC, garath submitted a review, later dismissed

2023-09-29 16:20 UTC, missymessa commented
@jonfortescue do you recall if this work is still needed?

2023-09-29 17:08 UTC, jonfortescue commented
@missymessa Yes, as long as we're using OneLocBuild, this will be needed. Idk if this is the right "form" for it anymore, but the work needs to be done regardless.

2023-10-02 17:08 UTC, garath commented
@jonfortescue sorry to bother, but what was this for? To get these PATs in secret-manager? 

Any recommendations for a testing proceedure?

Is your comment about "form" regarding the format that OneLoc wants, or the form that secret-manager wants?

2023-10-02 17:28 UTC, jonfortescue commented
@garath no worries! It was indeed for getting this PAT in secret manager. For testing, as long as it is in the correct vaults, it shouldn't be an issue -- you'll know if it breaks if the PAT expires or if you move it incorrectly bc loc will break everywhere haha (specifically, the OneLocBuild task will begin failing). The big thing would be to try to rotate it once and make sure that works.

For "form", I'm referring to the format that secret-manager wants. Given that there's merge conflicts and that I think you've made changes to secret-manager, I think that should be reevaluated, basically.

2023-10-30 20:37 UTC, riarenas commented
I filed https://github.com/dotnet/arcade/pull/12020 to track this work. We can use this PR as a guide for the changes but this has a lot of conflicts with the current manifests, so closing.

2023-10-30 20:37 UTC, closed without merging