Disable CG in non-prod branches
dotnet/arcade pull request #13214
Opened 2023-04-19 18:54 UTC by wtgodbe

Disables Component Governance except in internal builds of branches named `main` or `internal/release/*`. Repos who want to opt in to other branches running CG can set the `disableComponentGovernance` parameter in their .yml file (Same with dev branches). I tested this in EFCore and all the scenarios I tried worked. Note that repos like aspnetcore that use the `job.yml` template instead of `jobs.yml` will also have to manually set the `disableComponentGovernance` param.

2023-04-19 19:07 UTC, garath commented
Just curious, CG tools already understand the difference between "production" and "non-production" branches. Is that not covering your scenario?

2023-04-19 19:27 UTC, mmitche approved these changes

2023-04-19 19:31 UTC, dougbu requested changes

2023-04-19 19:49 UTC, wtgodbe commented on eng/common/templates/jobs/jobs.yml
> +          disableComponentGovernance: true
I was trying to avoid that since moving this logic into `job.yml` means it's too late to set the value of the `disableComponentGovernance` param, which is used later in that file to decide if we inject the task. I also thought only aspnetcore used `job.yml`, but I see now dotnet/runtime does too so this should definitely get moved. 

I think it'll work if we just set the `skipComponentGovernanceDetection` variable based off of similar logic, then use _that_ to determine whether or not we inject the CG task. I've got a build going now to see if that works

2023-04-19 19:49 UTC, wtgodbe commented on eng/common/templates/jobs/jobs.yml
> +          disableComponentGovernance: true
https://dev.azure.com/dnceng/internal/_build/results?buildId=2162520&view=results

2023-04-19 20:05 UTC, garath commented
> There's a long email thread w/ Tactics and more people on it about this very topic.

Ah I had a feeling that I was missing part of the convo. Thanks for the answer!

2023-04-19 21:03 UTC, wtgodbe commented
Test builds for new approach:

[non-prod branch](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162586&view=results) - Should skip CG (no arcade injected task, auto-injected task should be skipped due to variable)
[prod branch](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162587&view=results) - Should run the arcade injected task, skip the auto-injected task
[non-prod branch that opts itself back in](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162588&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a) - Same behavior as above

2023-04-19 21:09 UTC, wtgodbe commented
Whoops, gotta account for OS when setting the variable, another iteration incoming

2023-04-19 21:28 UTC, wtgodbe commented
New builds:

[non-prod branch](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162614&view=results) - Should skip CG (no arcade injected task, auto-injected task should be skipped due to variable)
[prod branch](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162616&view=results) - Should run the arcade injected task, skip the auto-injected task
[non-prod branch that opts itself back in](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162619&view=results) - Same behavior as above

2023-04-19 22:03 UTC, wtgodbe commented
One more iteration because I realized that at least one of the steps in `component-governance.yml` needed to run on every build, and previously neither would run in PR builds against internal branches. I moved all of the logic into the invocation of the template. New builds going now

2023-04-19 22:39 UTC, wtgodbe commented
Alright, latest builds behaved how I'd expect. @dougbu any concerns with the current approach?

2023-04-19 23:09 UTC, dougbu commented on eng/common/templates/steps/component-governance.yml
> +  - script: "echo ##vso[task.setvariable variable=skipComponentGovernanceDetection]true"
Could you explain how this works or link to the successful test builds❔ I expected the variable would need to be set around https://github.com/dotnet/arcade/pull/13214/files#diff-22da7e3800f8d77bccd75b181def1385123174ef4a38a7ccbd7a3d7317580c12R162 i.e., before the default injection logic runs (which is effectively the first step of any pipeline).

2023-04-19 23:29 UTC, wtgodbe commented on eng/common/templates/steps/component-governance.yml
> +  - script: "echo ##vso[task.setvariable variable=skipComponentGovernanceDetection]true"
[here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162639&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=2331deb8-a2c0-52bb-dfb1-18607764ad9e&l=12) is an example from a build of this branch. This variable doesn't actually skip the step entirely (even when set "in time"), it only tells the step to no-op. The auto-injected step only skips entirely if CG has already ran (e.g. [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162641&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=2331deb8-a2c0-52bb-dfb1-18607764ad9e&l=1))

2023-04-20 00:36 UTC, dougbu commented on eng/common/templates/steps/component-governance.yml
> +  - script: "echo ##vso[task.setvariable variable=skipComponentGovernanceDetection]true"
In that build, click on `Windows` on the left side, open `job preparation parameters`, then head down to line 163. You'll see a long line that ends w/ a check of the variable:
``` text
Evaluating:
  and(
    eq(resources['repositories']['self']['ref'], resources['repositories']['self']['defaultBranch']),
    eq(resources['repositories']['__designer_repo']['ref'], resources['repositories']['__designer_repo']['defaultBranch']),
    or(eq(resources['repositories']['self']['type'], 'Git'),
       eq(resources['repositories']['__designer_repo']['type'], 'Git'),
       eq(resources['repositories']['self']['type'], 'Github'),
       eq(resources['repositories']['__designer_repo']['type'], 'Github'),
       eq(resources['repositories']['self']['type'], 'GitHubEnterprise'),
       eq(resources['repositories']['__designer_repo']['type'], 'GitHubEnterprise')),
    ne(variables['PREVENT_RUNNING_CG'], 'true'),
    ne(variables['skipComponentGovernanceDetection'], 'true'))
```
If the variable were set in job.yml's `variables` expansion (as we did at <https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/.azure/pipelines/jobs/default-build.yml#L164-L165>), the step _should_ be removed entirely. That's more efficient and avoids noise in the build display. Unfortunately, it's not working :frowning:

In any case and as I think about this more, I doubt there's anyone w/ a strange need to use the auto-injected task b/c it's so limited e.g., it only handles 'main' and runs in public builds too. You could simplify things and _unconditionally_ set the variable in job.yml.

Due to the current bug around auto-injection (it worked when we changed dotnet/aspnetcore), this isn't worth holding up the PR.

2023-04-20 00:37 UTC, dougbu approved these changes

2023-04-20 15:44 UTC, wtgodbe commented
/backport to release/6.0

2023-04-20 15:44 UTC, wtgodbe commented
/backport to release/7.0

2023-04-20 15:47 UTC, wtgodbe commented
Manual PRs incoming. Looks like the timeout failure is happening everywhere, @mmitche / @dougbu could I get help merging this?

2023-04-20 20:35 UTC, merged

2023-04-24 09:58 UTC, JanKrivanek commented on eng/common/templates/job/job.yml
> +        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), eq(parameters.runAsPublic, 'false'), or(contains(variables['Build.SourceBranch'], 'i
Doesn't the 'Build.SourceBranch' contain the full branch name?

`eq(variables['Build.SourceBranch'], 'main')` ---> `eq(variables['Build.SourceBranch'], 'refs/heads/main')`
`contains(variables['Build.SourceBranch'], 'internal/release')` ---> `startsWith(variables['Build.SourceBranch'], 'refs/heads/internal/release')`

2023-04-24 18:37 UTC, jakobbotsch commented on eng/common/templates/job/job.yml
> +      componentGovernanceIgnoreDirectories: ${{ parameters.componentGovernanceIgnoreDirectories }}
Shouldn't it have something like
```
        disableComponentGovernance: ${{ parameters.disableComponentGovernance }}
```
in the non-empty case to pass the value through? (We are getting CG warnings in our internal superpmi-collect pipeline that tries to pass this through to job.yml.)

2023-04-24 18:59 UTC, jander-msft commented on eng/common/templates/job/job.yml
> +      componentGovernanceIgnoreDirectories: ${{ parameters.componentGovernanceIgnoreDirectories }}
I put up a PR for this: https://github.com/dotnet/arcade/pull/13274