Remove Source Link package references
dotnet/arcade pull request #13260
Opened 2023-04-22 00:39 UTC by tmat

Source Link is now included in .NET SDK.

2023-04-22 00:39 UTC, tmat commented
@mmitche

2023-04-23 08:03 UTC, ViktorHofer requested changes
I'm excited to see sourcelink support added directly into the SDK.

We must wait until Arcade updates to an SDK that has the implicit sourcelink support though. Based on https://github.com/dotnet/sdk/commit/dd2e7b5c8a3e3c8e4fc4292d1d97d135195bd490, that would be 8.0 Preview 4.

We should also communicate this change with the Arcade Engineering Partners alias as this is a breaking change. Before, you could set an explicit source link package version and Arcade would have respected that while now such an explicit version would just be ignored.

2023-04-24 18:18 UTC, mmitche commented
Yep, this should not be merged until p4 is released and arcade updates to P4.

2023-04-24 18:19 UTC, mmitche submitted a review, later dismissed
Wait till p4 release

2023-05-17 16:34 UTC, mmitche commented on eng/Version.Details.xml
> -    <Dependency Name="Microsoft.SourceLink.GitHub" Version="8.0.0-beta.23218.3">
We should exclude these changes initially. Most repos have coherent parent dependency attributes on their sourcelink dependencies. This means that the arcade updates will fail. Instead, you should:
1. Do the changes in `eng/Versions.props` and `RepositoryInfo.targets`
2. Flow this to all repos
3. Remove the sourcelink dependencies in all repos' `Version.Details.xml` 
4. Remove the sourcelink dependencies here.

2023-06-12 15:59 UTC, tmat commented
@ViktorHofer Help would be appreciated. Thanks!

2023-06-14 16:08 UTC, ViktorHofer approved these changes

2023-06-14 17:37 UTC, merged