Add artifacts pattern to SDL tool arguments
dotnet/arcade pull request #13893
Opened 2023-07-12 16:29 UTC by MilenaHristova

Passing the path to the artifacts folder as a pattern suitable for BinSkim
We're enabling the BinSkim tool in the repos that run SDL checks in their CI builds as described in [Automate BinSkim runs over official builds issue](https://github.com/dotnet/arcade-services/issues/2647) 

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2023-07-12 16:40 UTC, riarenas requested changes
I think this is probably better added to the steps template directly.

2023-07-12 16:40 UTC, riarenas commented on eng/common/templates/job/execute-sdl.yml
> +      additionalParameters: -ArtifactsDirectory '$(Build.ArtifactStagingDirectory)\artifacts\**'
It doesn't seem right to add this to the job template. Should this instead be added to the steps template referenced by this one? Default additional parameters don't seem "additional" to me.

2023-07-12 16:50 UTC, MilenaHristova commented on eng/common/templates/job/execute-sdl.yml
> +      additionalParameters: -ArtifactsDirectory '$(Build.ArtifactStagingDirectory)\artifacts\**'
I added it there at first but the steps template is used also here https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/templates/steps/sdl-validation.yml&version=GBmain&line=63&lineEnd=64&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents and the parameter would get overwritten

2023-07-12 17:08 UTC, riarenas commented on eng/common/templates/job/execute-sdl.yml
> +      additionalParameters: -ArtifactsDirectory '$(Build.ArtifactStagingDirectory)\artifacts\**'
I'm not sure I follow why that makes this change OK.

If the release repo wants to override the parameter for that invocation of the sdl steps, that seems fine. If we don't want the release repo doing that, we should change the release repo.

Is there a more granular place this can be added? since it's just for binskim, should it go to where we execute binskim in the sdl toolset instead?

2023-07-13 09:20 UTC, MilenaHristova commented on eng/common/templates/job/execute-sdl.yml
> +      additionalParameters: -ArtifactsDirectory '$(Build.ArtifactStagingDirectory)\artifacts\**'
agree, it's not the best solution. @andriipatsula i propose we add the `Target` argument to `BinskimAdditionalRunConfigParams` instead of setting it separately - I tested it in arcade-services https://dev.azure.com/dnceng/internal/_build/results?buildId=2220935&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=66df1a84-4ac1-5ba1-6998-e011cc992fec with
```
-BinskimAdditionalRunConfigParams @("IgnorePdbLoadError < True","Recurse < True","Target < $(Build.ArtifactStagingDirectory)\artifacts\**")'
```
I believe it will work also for the release repo

2023-07-14 08:28 UTC, MilenaHristova commented
3rd try - making the artifacts directory into a pattern just for binskim. No additional arguments need to be passed from the yaml of the product repos. 
Test run on `arcade-services` https://dev.azure.com/dnceng/internal/_build/results?buildId=2221107&view=results

2023-07-14 08:39 UTC, andriipatsula approved these changes

2023-07-14 09:20 UTC, merged