Enable Vertical build PoC as a more first-class concept
dotnet/arcade pull request #14274
Opened 2023-12-08 19:24 UTC by mmitche

For the vertical builds, we need some of the arcade infra required for source build, but not all. This PR introduces two switches:
- ArcadeBuildVertical - Enables arcade infra for vertical build. Similar to source build but without some SB customization (e.g. filtering)
- DotNetBuildVertical - Passed to inner build when ArcadeBuildVertical is enabled.

Note that BOTH switches may be passed if you wanted.

I probably could have introduced a more polished switch structure here. But I don't want to disturb existing SB functionality before a full design and rollout plan is determined.

In addition:
- Add inner-clone support for Windows.
- Add ExcludeFromVerticalBuild switch. We could use ExcludeFromBuild for the PoCs but there are other uses of ExcludeFromBuild in the product and I want to avoid confusion.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2023-12-08 20:21 UTC, steveisok submitted a review, later dismissed

2023-12-08 23:48 UTC, mmitche commented
https://dev.azure.com/dnceng/internal/_build/results?buildId=2332244&view=results

2023-12-08 23:49 UTC, mmitche commented
@ViktorHofer This works now when building arcade with itself with -verticalBuild switch on windows. I think we'll need this infra to get the PoC working.

2023-12-09 08:56 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj
> +    <NoWarn>$(NoWarn);3021;NU5105;NU5111;SYSLIB0013</NoWarn>
Add a comment above indicating what the individual NoWarns are for. The others were already there but adding a comment for each is a best practice that we follow in other places.

2023-12-09 09:00 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/TargetFrameworkDefaults.props
> +    <NetToolCurrent Condition="'$(DotNetBuildFromSource)' == 'true' or '$(DotNetBuildVertical)' == 'true'">$(NetCurrent)</NetToolCurrent>
That looks wrong. We don't want to change the meaning of TFMs when building from the VMR.

2023-12-09 09:01 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcadeTools.targets
> +            (('$(ArcadeBuildFromSource)' == 'true'  and '$(ArcadeInnerBuildFromSource)' == 'true' and '@(SourceBuildIntermediateNupkgReference)' != '') or
revert:

```suggestion
            (('$(ArcadeBuildFromSource)' == 'true' and '$(ArcadeInnerBuildFromSource)' == 'true' and '@(SourceBuildIntermediateNupkgReference)' != '') or
```

2023-12-09 09:07 UTC, ViktorHofer commented on eng/common/build.ps1
> +  Write-Host "  -sourceBuild            Run in 'source build' infra mode."
This doesn't look right. The same switch exists in the build.sh file for Unix platforms but does something completely different: https://github.com/dotnet/arcade/blob/7245f17c491d7e5dafbc74e9890a65d59f7a3af6/eng/common/build.sh#L22-L24

What does "source build" infra mode mean?

2023-12-09 09:08 UTC, ViktorHofer commented on eng/common/build.ps1
> +  Write-Host "  -verticalBuild          Run in 'vertical build' infra mode."
Why do we need a new switch and not just use the already defined `DotNetBuildVertical` one?

2023-12-09 09:13 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
> +             Condition="'$(Publish)' == 'true' and '$(DotNetBuildFromSource)' != 'true' and '$(DotNetBuildVertical)' != 'true'"/>
Wouldn't it make more sense to just not pass the `-publish` argument in when building the repos from the VMR? That's done here: https://github.com/dotnet/dotnet/blob/ab06cf16219bc309a2a725008556abbbdab01007/repo-projects/Directory.Build.props#L152

2023-12-09 09:20 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
> +             Condition="'$(ArcadeBuildFromSource)' == 'true' or '$(ArcadeBuildVertical)' == 'true'"/>
This confuses me. Why would invoke source build infrastructure when not building from source? 

Which infrastructure from AfterSourceBuild.proj would you want a VMR build to execute? We don't create prebuilt usage reports in the VMR today when not building from source and I don't see that in scope for the PoCs. Similarly, I was under the impression that we don't want to create the source built intermediate nuget packages when not building from source.

If there really is some common infrastructure (please explain which part), then we should rename the `AfterSourceBuild.proj` file or create a new `AfterBuildVertical.proj` and share the code between both projects, i.e. via a targets file.

2023-12-09 09:23 UTC, ViktorHofer requested changes
Marking as "Request changes" to prevent an accidental merge before we resolve the feedback.

2023-12-11 15:05 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/TargetFrameworkDefaults.props
> +    <NetToolCurrent Condition="'$(DotNetBuildFromSource)' == 'true' or '$(DotNetBuildVertical)' == 'true'">$(NetCurrent)</NetToolCurrent>
Yeah, you're probably right on this one.

2023-12-11 15:06 UTC, mmitche commented on eng/common/build.ps1
> +  Write-Host "  -sourceBuild            Run in 'source build' infra mode."
I added this for completeness. It would end up being "windows build without prebuilts". I can remove it.

2023-12-11 15:08 UTC, mmitche commented on eng/common/build.ps1
> +  Write-Host "  -verticalBuild          Run in 'vertical build' infra mode."
This basically is the PoC mode for Windows and potentially other platforms. You need two switches to make thsi work:
- ArcadeBuildVertical
- DotNetBuildVertical

ArcadeBuildVertical should be initially passed

2023-12-11 15:13 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
> +             Condition="'$(ArcadeBuildFromSource)' == 'true' or '$(ArcadeBuildVertical)' == 'true'"/>
You need to create the intermediate nupkgs coming out of each repo build for use in downstream builds for the orchestrated build infra to work today.

IMO, we should keep the prebuilt detection in place for VB (but only error in "strict" SB mode).

Yes, we should rename AfterSourceBuild to something else, but I want to do this after [.NET 9: Redesign source-build behavior controls](https://github.com/dotnet/source-build/issues/2974) is complete. What we want to do with the PoC, IMO, is use the source build infra, while not necessarily using the SB repo behavior.

2023-12-11 15:15 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
> +             Condition="'$(Publish)' == 'true' and '$(DotNetBuildFromSource)' != 'true' and '$(DotNetBuildVertical)' != 'true'"/>
Maaybe? I'm not sure why that was put there in the first place so I'm skeptical of removing it at this point.

2023-12-11 16:02 UTC, ViktorHofer commented on eng/common/build.ps1
> +  Write-Host "  -sourceBuild            Run in 'source build' infra mode."
OK. Let's remove this until there's a need and  until it works with the existing infrastructure.

2023-12-11 19:36 UTC, tkapin commented on src/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/git-clone-to-dir.ps1
> +    git clone -c protocol.file.allow=always --depth=1 --no-local --no-checkout "$Source" "$Dest"
When native executables calls fail, the error is not propagated in PowerShell (unless I'm missing some external setup) and $LASTEXITCODE has to be checked. Do we have a solution for this in arcade (such as a wrapper function for calling native binaries that checks the LASTEXITCODE and throws if non-zero) or that's something that we'd need to do yet?

2023-12-11 20:33 UTC, ViktorHofer approved these changes

2023-12-11 21:12 UTC, merged