Fix up SBOM generation
dotnet/arcade pull request #15014
Opened 2024-08-20 22:57 UTC by mmitche

It looks as though during the 1ESPT migration, we lost arcade's SBOM generation due to the steps not being included in the official job template. Because of how arcade handles artifacts, we do need our SBOM generation until 1ESPT handles pipeline logging command based uploads.

### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

2024-08-20 22:59 UTC, mmitche commented
@chcosta can you take a look at this? It looks like we dropped SBOM generation, but not sure exactly how this was intended to be structured.

2024-08-20 23:19 UTC, chcosta requested changes
The first comment is a bit of a nit.  Setting this to "Request changes" only because I'd like Jeremy to validate he isn't affected by this before it gets merged.

2024-08-20 23:19 UTC, chcosta commented on eng/common/templates-official/job/job.yml
> +  BuildDropPath: '$(Build.SourcesDirectory)/artifacts'
I think these could now be removed from https://github.com/dotnet/arcade/blob/27387fefc9bf262b71c16f003cc79ebb25244470/eng/common/core-templates/job/job.yml#L36-L39

2024-08-20 23:19 UTC, chcosta commented on eng/common/templates/job/job.yml
> -      - template: /eng/common/templates/steps/component-governance.yml
@jkoritzinsky had a scenario where this was needed in the public templates.  We should ensure that isn't regressed.

2024-08-20 23:26 UTC, jkoritzinsky commented on eng/common/templates/job/job.yml
> -      - template: /eng/common/templates/steps/component-governance.yml
I believe these steps control all CG execution on public pipelines. If we still want that, we either need to keep these steps or just revert my PR that moved them out of the "shared template"

2024-08-21 14:01 UTC, mmitche commented on eng/common/templates/job/job.yml
> -      - template: /eng/common/templates/steps/component-governance.yml
Because 1ESPT is injecting on the official pipelines, I think we want to keep the CG in public, but not in official

2024-08-21 16:36 UTC, chcosta approved these changes

2024-08-21 18:03 UTC, mmitche commented on eng/common/templates/job/job.yml
> -      - ${{ if ne(parameters.artifacts.publish, '') }}:
@chcosta No issue with de-indenting this, is there?

2024-08-21 18:18 UTC, mmitche commented
https://dev.azure.com/dnceng/internal/_build/results?buildId=2521030&view=results for a test

2024-08-23 19:48 UTC, mmitche commented
@chcosta can you approve?

2024-08-23 20:40 UTC, chcosta approved these changes

2024-08-23 20:40 UTC, merged