Use pigz when available for faster tar.gz
dotnet/arcade pull request #15038
Opened 2024-08-29 15:41 UTC by am11

Ideally, we should move to System.Formats.Tar based task for this, but for now this uses pigz over gzip tool to parallaleize the work of compression. Consequently, `dotnet-runtime-10.0.0-dev-osx-arm64.tar.gz` creation goes from `3.7s` to `0.57s` after `brew install pigz`.

cc @akoeplinger, @ViktorHofer

2024-09-03 08:56 UTC, akoeplinger requested changes

2024-09-03 08:56 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
can we use the `--use-compress-program=pigz` tar option instead? that'd simplify the command

we can detect presence of pigz like this and use it:
```
    <Exec Command="command -v pigz" IgnoreExitCode="true" StandardOutputImportance="Low">
      <Output TaskParameter="ExitCode" PropertyName="_PigzFoundExitCode" />
    </Exec>
...
   <PropertyGroup>
     <UsePigzCommand Condition="'$(_PigzFoundExitCode)' == '0'">--use-compress-program=pigz</UsePigzCommand>
   </PropertyGroup>
```

btw. I think this runs on Windows too right? we should skip detecting pigz there

2024-09-03 19:21 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
There was a perf difference, which is why i've used pipe. Copilot says:

```
Piping Data: In the first command, tar -cf - . | pigz > file.tar.gz, the data is piped directly from tar to pigz. This allows both commands to run concurrently, potentially utilizing multiple CPU cores more effectively.
Single Process: In the second command, tar -cf file.tar.gz --use-compress-program=pigz ., tar handles the compression internally, which might not be as efficient in utilizing multiple cores compared to the first method.
```

I applied this diffs in files found by `find ~/.nuget -name archives.targets` and ran packs subset to measure the perf.

I can split the check if necessary, but we are using one liner compact syntax in other places as well.

The shipping archives in windows are normally .zip, but if we are using it on windows, can add support?

2024-09-04 09:06 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
> There was a perf difference, which is why i've used pipe. Copilot says:

What's the diff? Also please don't simply trust what Copilot says. The manpage for tar on my Mac says
```
--use-compress-program program
   Pipe the input (in x or t mode) or the output (in c mode) through program instead of using the builtin compression support.
```

So it sounds like it should pipe the data too?

> The shipping archives in windows are normally .zip, but if we are using it on windows, can add support?

Yes you can opt in to .tar.gz on Windows:
https://github.com/dotnet/arcade/blob/5602a0a33795dfdac629b71417d5d46506c2c292/src/Microsoft.DotNet.Build.Tasks.Archives/README.md?plain=1#L13-L17

2024-09-04 09:17 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
I just tried on my Mac and I see no difference between `--use-compress-program` and piping.

2024-09-04 09:50 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
I did measurements myself and there was difference which is why I used the pipe, can you share the stats? The explanation for why the difference occurred is what copilot provided..

2024-09-04 10:24 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
The average time suggests no significant difference. I think testing with single iteration was flaky when I tested it.

artifacts/bin is 1.2 GB:
```
#!/bin/bash

total_time_1=0
total_time_2=0
total_time_3=0

for i in {1..5}; do
    time_1_seconds=$( { time sh -c "tar -C artifacts/bin --use-compress-program=pigz -cf 'ss.tar.gz' ."; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_1=$(echo "$total_time_1 + $time_1_seconds" | bc)
done

for i in {1..5}; do
    time_2_seconds=$( { time sh -c "tar -C artifacts/bin -cf - . | pigz > 'ss.tar.gz'"; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_2=$(echo "$total_time_2 + $time_2_seconds" | bc)
done

for i in {1..5}; do
    time_3_seconds=$( { time sh -c "tar -C artifacts/bin -czf 'ss.tar.gz' ."; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_3=$(echo "$total_time_3 + $time_3_seconds" | bc)
done

echo "Average time for first command: $(echo "$total_time_1 / 5" | bc -l) seconds"
echo "Average time for second command: $(echo "$total_time_2 / 5" | bc -l) seconds"
echo "Average time for third command: $(echo "$total_time_3 / 5" | bc -l) seconds"
```

```
Average time for first command: 6.09620000000000000000 seconds
Average time for second command: 6.02840000000000000000 seconds
Average time for third command: 42.77940000000000000000 seconds
```

2024-09-04 10:25 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
The average time suggests no significant difference. I think testing with single iteration was flaky when I tested it.

artifacts/bin is 1.2 GB:
```sh
#!/bin/bash

total_time_1=0
total_time_2=0
total_time_3=0

for i in {1..5}; do
    time_1_seconds=$( { time sh -c "tar -C artifacts/bin --use-compress-program=pigz -cf 'ss.tar.gz' ."; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_1=$(echo "$total_time_1 + $time_1_seconds" | bc)
done

for i in {1..5}; do
    time_2_seconds=$( { time sh -c "tar -C artifacts/bin -cf - . | pigz > 'ss.tar.gz'"; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_2=$(echo "$total_time_2 + $time_2_seconds" | bc)
done

for i in {1..5}; do
    time_3_seconds=$( { time sh -c "tar -C artifacts/bin -czf 'ss.tar.gz' ."; } 2>&1 | grep real | awk '{print $2}' | awk -Fm '{print ($1 * 60) + $2}')
    total_time_3=$(echo "$total_time_3 + $time_3_seconds" | bc)
done

echo "Average time for first command: $(echo "$total_time_1 / 5" | bc -l) seconds"
echo "Average time for second command: $(echo "$total_time_2 / 5" | bc -l) seconds"
echo "Average time for third command: $(echo "$total_time_3 / 5" | bc -l) seconds"
```

results in:
```sh
Average time for first command: 6.09620000000000000000 seconds
Average time for second command: 6.02840000000000000000 seconds
Average time for third command: 42.77940000000000000000 seconds
```
I'll update to support windows and remove the pipeline. ;)

2024-09-04 11:13 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +      <_CompressionArg>--use-compress-program=gzip</_CompressionArg>
we could move these and the pigz checking Exec into a separate task so we don't need to duplicate

2024-09-04 11:16 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> -    <Exec Command="tar -C '$(_SymbolsOutputPathRoot)' -czf $(_DestinationFileName) ."
at least on my macOS version of `tar` I can keep the `z` arg and `--use-compress-program` still works, mind checking if that is true on Linux too? then we could just insert `_CompressionArg` using pigz

2024-09-04 11:50 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +      <_CompressionArg>--use-compress-program=gzip</_CompressionArg>
Separate target or a task? https://github.com/dotnet/msbuild/issues/7944 is waiting for OOTB task (similar to `ZipDirectory`). If we don't need to support .NET Framework in arcade, which seems to be the case:

https://github.com/dotnet/arcade/blob/e39986b4ebd8cc28aecdda28b8ead0f1612e74b8/src/Microsoft.DotNet.Build.Tasks.Archives/Microsoft.DotNet.Build.Tasks.Archives.csproj#L4

I can create one with enough customization to support these use-cases. That'd be much bigger than +26/-2 delta. 😅

2024-09-04 11:58 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +      <_CompressionArg>--use-compress-program=gzip</_CompressionArg>
just a separate target :)

2024-09-04 14:15 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
busybox tar (alpine linux etc.) doesn't support this option:

```
tar: unrecognized option: use-compress-program=gzip
BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [LONGOPT]... [FILE]...

Create, extract, or list files from a tar file

	c	Create
	x	Extract
	t	List
	-f FILE	Name of TARFILE ('-' for stdin/out)
	-C DIR	Change to DIR before operation
	-v	Verbose
	-O	Extract to stdout
	-m	Don't restore mtime
	-o	Don't restore user:group
	-k	Don't replace existing files
	-Z	(De)compress using compress
	-z	(De)compress using gzip
	-J	(De)compress using xz
	-j	(De)compress using bzip2
	--lzma	(De)compress using lzma
	-a	(De)compress based on extension
	-h	Follow symlinks
	-T FILE	File with names to include
	-X FILE	File with glob patterns to exclude
	--exclude PATTERN	Glob pattern to exclude
	--overwrite		Replace existing files
	--strip-components NUM	NUM of leading components to strip
	--no-recursion		Don't descend in directories
	--numeric-owner		Use numeric user:group
	--no-same-permissions	Don't restore access permissions
```

where piping is the only option.

2024-09-05 08:13 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
the problem is that piping doesn't work on Windows. I think we should just not support using pigz on Windows to make the conditionals easier.

2024-09-05 09:50 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
Piping does work on windows cmd.exe, just tested it with https://sourceforge.net/projects/pigz-for-windows/ (and i have `C:\Program Files\Git\usr\bin` in PATH which contains tar.exe):

```cmd
> dotnet new console -n hw1
> cd hw1
> dotnet publish -r win-x64
> tar cf - bin | pigz > foo.tar.gz
> mkdir g
> cd g
> tar xzf ..\foo.tar.gz
> bin\Release\net8.0\win-x64\hw1.exe
Hello World!
```

2024-09-09 11:04 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
ah nice, TIL

2024-09-09 11:06 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Message Text="Successfully created archive -> '$(_DestinationFileName)' from '$(_OutputPathRoot)" Importance="high" />
any reason why you changed the message? the old format matched what Roslyn produced for compiling so it makes more sense to me

2024-09-09 11:47 UTC, am11 commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Exec Command="command -v pigz &gt;/dev/null 2&gt;&amp;1 &amp;&amp; tar -C '$(_OutputPathRoot)' -cf - . | pigz &gt; '$(_DestinationFileName)' || tar -C '$(_OutputPathRoot)' -czf '$(_DestinationFi
PowerShell (which msbuild only uses when we explicitly specify `Exec Command="powershell ..."`, we aren't using it here), pipe can have strange behavior based on the codepage. AFAIK, cmd.exe doesn't have this problem https://stackoverflow.com/q/59110563.

2024-09-09 13:29 UTC, akoeplinger commented on src/Microsoft.DotNet.Build.Tasks.Archives/build/archives.targets
> +    <Message Text="Successfully created archive -> '$(_DestinationFileName)' from '$(_OutputPathRoot)" Importance="high" />
Ok

2024-09-09 13:30 UTC, akoeplinger approved these changes

2024-09-09 15:37 UTC, akoeplinger submitted a review, later dismissed

2024-09-09 17:42 UTC, am11 commented
`Merging can be performed automatically with 1 approving review.` guess github is confused today 😅

2024-09-09 22:22 UTC, akoeplinger commented
> New changes require approval from someone other than akoeplinger because they were the last pusher.

Can you push some empty change so I can approve again :D

2024-09-10 06:44 UTC, am11 commented
@akoeplinger, ready. 😎

2024-09-10 06:48 UTC, akoeplinger approved these changes

2024-09-10 06:50 UTC, merged