[release/9.0] Update to RC1
dotnet/arcade pull request #15071
Opened 2024-09-11 00:14 UTC by mmitche

### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

2024-09-11 01:32 UTC, lewing approved these changes

2024-09-11 16:34 UTC, rainersigwald requested changes
This will almost certainly fail official builds because of https://github.com/dotnet/sdk/issues/43339.

2024-09-11 18:52 UTC, lewing commented
release/9.0 workaround here https://github.com/dotnet/arcade/pull/15077

2024-09-11 19:39 UTC, rainersigwald approved these changes

2024-09-12 15:58 UTC, agocke commented
Looks like only system.buffers Android tests are failing

2024-09-12 17:25 UTC, merged