Enable unpack and repack of .deb containers
dotnet/arcade pull request #15345
Opened 2024-12-17 22:45 UTC by NikolaMilosavljevic

Fixes: https://github.com/dotnet/arcade/issues/14436

This work enables unpack and repack of .deb containers. I've tested this with all current .NET DEB packages.

I've updated `test.deb` to include a signable file - this makes the DEB test complete.

2024-12-17 23:11 UTC, ellahathaway commented
Do you have a binlog from an arcade-validation (or some equivalent repo) build with these changes? Wondering if you've done e2e testing and also curious to see what the SignTool output looks like.

2024-12-17 23:31 UTC, jkoritzinsky commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            if (false == createDebPackageTask.Execute())
```suggestion
            if (!createDebPackageTask.Execute())
```

2024-12-17 23:31 UTC, jkoritzinsky commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +using Microsoft.DotNet.Build.Tasks.Installers.src;
Can we change the namespaces in the `Installers` package to remove the `.src` nested namespace?

2024-12-17 23:42 UTC, NikolaMilosavljevic commented
> Do you have a binlog from an arcade-validation (or some equivalent repo) build with these changes? Wondering if you've done e2e testing and also curious to see what the SignTool output looks like.

Working on this validation right now.

2024-12-18 02:12 UTC, NikolaMilosavljevic commented
Binlog from local validation in arcade-validation repo: 
[msbuild.zip](https://github.com/user-attachments/files/18173618/msbuild.zip)

Debian signing log entries:
```
File /src/git/arcade-validation/artifacts/packages/Debug/NonShipping/test.deb is not signed.
Extracting file 'data.tar.gz' from '/src/git/arcade-validation/artifacts/packages/Debug/NonShipping/test.deb' to '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz'.
Tracking file '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz' isNested=True
Extracting file 'hello' from '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz' to '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello'.
Tracking file '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello' isNested=True
Ignoring non-signable file: /src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello
Caching file hello 036E707FF7B4A823E1182FE6DF81E90A93AE44EA17A8B2F0044A11CDE169342E
Caching file data.tar.gz 57989E84E7AFBDE7A3396AC35B47F4F3553B0EF68ADC6652C70507814FA45BA2
Caching file test.deb EC14B84B6074AF3A402E8CA7AF2381373705D121EDEAC5310425FD659E23EDC2
```

This is with current `test.deb` package in `arcade-validation` repo. I will recheck with newer version of the package that I've prepared for this PR.

2024-12-18 02:20 UTC, NikolaMilosavljevic commented
Here's the binlog from signing test that includes the updated `test.deb` (with signable binary, mscorlib.dll): 
[msbuild.zip](https://github.com/user-attachments/files/18173850/msbuild.zip)

Log shows additional entries for this binary, i.e.:
```
Extracting file 'mscorlib.dll' from '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz' to '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/39/./usr/local/bin/mscorlib.dll'.
Tracking file '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/39/./usr/local/bin/mscorlib.dll' isNested=True
```

2024-12-18 17:26 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                if (match == null || relativePath.StartsWith(match))
Is `StartsWith` specific enough? Is it possible that the deb package has a `data.tar` and `data.tar2`?

2024-12-18 17:26 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            string dataArchive = NestedParts.Values.First().FileSignInfo.FullPath;
If it's the only expected, then `Single()`?

2024-12-18 17:29 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            var (relativePath, content, contentSize) = ReadDebContainerEntries(debianPackage, "control.tar").First();
Single()? Unless we expect there to be multiple control entries.

2024-12-18 17:31 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            if (false == createDebPackageTask.Execute())
Thanks - will update this and the other instance too.

2024-12-18 17:31 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +using Microsoft.DotNet.Build.Tasks.Installers.src;
Sure, will do that.

2024-12-18 17:31 UTC, jkoritzinsky commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                if (match == null || relativePath.StartsWith(match))
deb packages are defined to only have 3 entries, `debian-binary`, `control.tar`, and `data.tar`, where the two tarballs can be compressed with gz, xz, or (in newer versions) zstd, adding the correct extension for the compression technology.

For more exact checking, this code could check for one of the known-supported extensions, or for `relativePath == "data.tar" || relativePath.StartsWith("data.tar.")`.

2024-12-18 17:32 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +        private void ExtractTarballContents(string file, string destination, bool skipDirectories = false, bool skipSymlinks = false)
Do you need support for skipDirectories or skipSymlinks? I don't any call where they are set to `false` or unset.

2024-12-18 17:33 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            if (false == createMD5SumsFileTask.Execute())
```suggestion
            if (!createMD5SumsFileTask.Execute())
```

2024-12-18 17:34 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                Files = Directory.GetFiles(dataLayout, "*", SearchOption.AllDirectories)
I assume that order doesn't matter in this checksums file?

2024-12-18 17:36 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            }
Is `Installed-Size` always expected?

2024-12-18 17:37 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                if (match == null || relativePath.StartsWith(match))
This method is used for obtaining `data.tar.*` or `control.tar.*` so we need to keep the comparison as is, i.e. compare to `match` argument.

2024-12-18 17:37 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            string dataArchive = NestedParts.Values.First().FileSignInfo.FullPath;
Yeah, will fix - thanks.

2024-12-18 17:38 UTC, mmitche requested changes
Can you add another test or two that validates that the repacked deb has the expected content?

- Correct checksums/metadata
- Correct files/layout

Otherwise looks great aside from some questions/nits.

2024-12-18 17:38 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            var (relativePath, content, contentSize) = ReadDebContainerEntries(debianPackage, "control.tar").First();
Thanks - will fix.

2024-12-18 17:40 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +        private void ExtractTarballContents(string file, string destination, bool skipDirectories = false, bool skipSymlinks = false)
Originally I thought of having this as general-purpose extraction method. But, I should probably rename the method and make it specific to this scenario - i.e. no directories and no symlinks.

2024-12-18 17:42 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                Files = Directory.GetFiles(dataLayout, "*", SearchOption.AllDirectories)
It does not.

2024-12-18 17:43 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            }
No, it is optional. There is a relevant comment right above this block.

2024-12-18 17:44 UTC, NikolaMilosavljevic commented
> Can you add another test or two that validates that the repacked deb has the expected content?
> 
> * Correct checksums/metadata
> * Correct files/layout
> 
> Otherwise looks great aside from some questions/nits.

Certainly. Will do.

2024-12-18 18:19 UTC, ellahathaway commented
> Binlog from local validation in arcade-validation repo: [msbuild.zip](https://github.com/user-attachments/files/18173618/msbuild.zip)
> 
> Debian signing log entries:
> 
> ```
> File /src/git/arcade-validation/artifacts/packages/Debug/NonShipping/test.deb is not signed.
> Extracting file 'data.tar.gz' from '/src/git/arcade-validation/artifacts/packages/Debug/NonShipping/test.deb' to '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz'.
> Tracking file '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz' isNested=True
> Extracting file 'hello' from '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/data.tar.gz' to '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello'.
> Tracking file '/src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello' isNested=True
> Ignoring non-signable file: /src/git/arcade-validation/artifacts/tmp/Debug/ContainerSigning/38/./usr/local/bin/hello
> Caching file hello 036E707FF7B4A823E1182FE6DF81E90A93AE44EA17A8B2F0044A11CDE169342E
> Caching file data.tar.gz 57989E84E7AFBDE7A3396AC35B47F4F3553B0EF68ADC6652C70507814FA45BA2
> Caching file test.deb EC14B84B6074AF3A402E8CA7AF2381373705D121EDEAC5310425FD659E23EDC2
> ```
> 
> This is with current `test.deb` package in `arcade-validation` repo. I will recheck with newer version of the package that I've prepared for this PR.

Binlog looks great. Thanks for validating that.

2024-12-18 19:12 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +using Microsoft.DotNet.Build.Tasks.Installers.src;
Fixed with https://github.com/dotnet/arcade/pull/15345/commits/9fe1ae4d009be57e070115a5ddc81f2d7c4b6253

2024-12-18 19:12 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            string dataArchive = NestedParts.Values.First().FileSignInfo.FullPath;
Fixed with https://github.com/dotnet/arcade/pull/15345/commits/9fe1ae4d009be57e070115a5ddc81f2d7c4b6253

2024-12-18 19:12 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +            var (relativePath, content, contentSize) = ReadDebContainerEntries(debianPackage, "control.tar").First();
Fixed with https://github.com/dotnet/arcade/pull/15345/commits/9fe1ae4d009be57e070115a5ddc81f2d7c4b6253

2024-12-18 20:36 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +        private void ExtractTarballContents(string file, string destination, bool skipDirectories = false, bool skipSymlinks = false)
https://github.com/dotnet/arcade/pull/15345/commits/5f0f7c18eb0b9d7d21694e4eb18b90a77bb4940d

I decided to keep an option to not skip symbolic links during tarball extraction, but updated the default value. I might use this in tests to verify package and tarball contents. We do not want to hash the symlinks, therefore we do not extract them in today's use cases.

2024-12-19 21:27 UTC, NikolaMilosavljevic commented
> Can you add another test or two that validates that the repacked deb has the expected content?
> 
> * Correct checksums/metadata
> * Correct files/layout
> 
> Otherwise looks great aside from some questions/nits.

Fixed with https://github.com/dotnet/arcade/pull/15345/commits/3172fe565588f670f9b68b6a1263ab1fbcf86cca

2024-12-19 21:45 UTC, mmitche submitted a review, later dismissed

2024-12-19 22:35 UTC, jkoritzinsky commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                tar.DataStream?.CopyTo(outputFileStream);
Does this do the right thing for symlinks (preseve the link during extraction or at least during repacking)?

2024-12-19 23:48 UTC, NikolaMilosavljevic commented on src/Microsoft.DotNet.SignTool/src/ZipData.cs
> +                tar.DataStream?.CopyTo(outputFileStream);
This method is not used for data tarball extraction, for the signing purpose. It is only used during repacking of the control tarball, for the purpose of hashing data content. We do not want to hash the symlinks, so we do not extract them.

Tarball extraction and repacking is done with old, unchanged methods, i.e. `ReadTarGZipEntries`.

2024-12-20 16:28 UTC, NikolaMilosavljevic commented
One test is still failing: `MissingCertificateNameButExtensionIsIgnored` for extension: "*.deb" - https://github.com/dotnet/arcade/blob/06ecc3c2f0265574f52ec7fd4186acb079d8d866/src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs#L2297

At first, this failed due to a missing `deb` entry in `needContent` Dictionary - causing the creation of dummy DEB package, which doesn't work with real unpacking code.

It is now failing due to a presence of the the signable file, since we're using the same test package for all DEB tests. New DEB package has a signable file, to be able to better test the DEB unpack/repack code.

If I put back the old `test.deb` file (without a signable file), this test succeeds.

I can add another test DEB package, to be used by this test, but is that the right option?

2024-12-20 17:08 UTC, ellahathaway commented
> One test is still failing: `MissingCertificateNameButExtensionIsIgnored` for extension: `*.deb` -
> 
> https://github.com/dotnet/arcade/blob/06ecc3c2f0265574f52ec7fd4186acb079d8d866/src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs#L2297
> 
> At first, this failed due to a missing `deb` entry in `needContent` Dictionary - causing the creation of dummy DEB package, which doesn't work with real unpacking code.
> 
> It is now failing due to a presence of the the signable file, since we're using the same test package for all DEB tests. New DEB package has a signable file, to be able to better test the DEB unpack/repack code.
> 
> If I put back the old `test.deb` file (without a signable file), this test succeeds.
> 
> I can add another test DEB package, to be used by this test, but is that the right option?

Can we have two test deb packages? One called `SignableDeb.deb` and the other called `UnsignableDeb.deb`?

2024-12-20 18:29 UTC, NikolaMilosavljevic commented
> > One test is still failing: `MissingCertificateNameButExtensionIsIgnored` for extension: `*.deb` -
> > https://github.com/dotnet/arcade/blob/06ecc3c2f0265574f52ec7fd4186acb079d8d866/src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs#L2297
> > 
> > At first, this failed due to a missing `deb` entry in `needContent` Dictionary - causing the creation of dummy DEB package, which doesn't work with real unpacking code.
> > It is now failing due to a presence of the the signable file, since we're using the same test package for all DEB tests. New DEB package has a signable file, to be able to better test the DEB unpack/repack code.
> > If I put back the old `test.deb` file (without a signable file), this test succeeds.
> > I can add another test DEB package, to be used by this test, but is that the right option?
> 
> Can we have two test deb packages? One called `SignableDeb.deb` and the other called `UnsignableDeb.deb`? I don't see harm in having two test packages.

Yeah, this is an option. But, we first need to understand why this is failing and if it's a real issue. We don't want to add a test package for the sake of passing a test-case. @mmitche is going to investigate this.

2024-12-20 23:46 UTC, NikolaMilosavljevic commented
Hmm, not sure why `NuGet.Packaging` was added - will remove.

2025-01-02 16:27 UTC, NikolaMilosavljevic commented
Two commits were not reviewed so this is still blocked. Checks are now passing.

2025-01-02 16:36 UTC, mmitche approved these changes

2025-01-02 16:38 UTC, merged