Add post-build functionality to SignTool
dotnet/arcade pull request #6190
Opened 2020-09-16 19:44 UTC by jcagme

Fixes: https://github.com/dotnet/core-eng/issues/10815

Make SignTool understand post-build metadata i.e. having a BARBuildId per item. 

The actual signing doesn't change at all.

2020-09-16 20:03 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +            var orderedItemsToSign = ItemsToSignPostBuild.OrderBy(i => i.GetMetadata("BARBuildID")).ToArray();
I think our team style here is to be explicit in our variable types and not use var.

2020-09-16 20:06 UTC, missymessa commented
Make sure to write up an issue to write tests to cover these changes :)

2020-09-16 20:21 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        private void PrepareSigning()
I really this. It does all the prep work up front so it doesn't add the overhead downstream into the functions that would use this data.

2020-09-16 20:21 UTC, jcagme commented
> Make sure to write up an issue to write tests to cover these changes :)

I'll add tests in this PR

2020-09-16 21:25 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +                    PrepareSigning();
Can you just move the logic into the `GenerateListOfFiles` function, before it iterates over `_itemsToSign`?  You would need to change `ItemsToSign` in Configuration.cs to be an `ITaskItem []` instead of `string []`.

2020-09-16 21:25 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +            // Based on the ordered set of BARBuildIds we start adding TaskItems to a map keeping track of things
Does this logic do what we want?  ie, isn't this just determining the oldest sign info?  What we want is the oldest if there's a collision for a file (via content hash), otherwise, whatever corresponds to the signing info for the current barId.

ie, fileExtensionSignInfo, I think it's used when you unpack something (a nupkg), and you find files inside.  how do you sign them?  these files won't necessarily show up in "ItemsToSign", just when those items are unpacked.  Then you find foo.dll from repo A.  Later you unpack a nupkg and find bar.dll from repo B.  If I'm understanding the below correctly, then you're always signing foo and bar using repo A's fileExtensionSignInfo.

2020-09-16 21:28 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
Current ItemsToSign is an array of strings, which doesn't allow us to pass in the BAR Build ID as metadata.

2020-09-16 21:31 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
Yeah, but it could be updated to be an ITaskItem.  They behave the same in many cases.  ie, whether it's a string or an ITaskItem, you can call it in MSBuild with a string that will get converted to an ITaskItem.

2020-09-16 21:34 UTC, chcosta requested changes
I'm not quite sure this is the desired behavior.

2020-09-16 21:42 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
How would we pass the BARBuildId to an array of strings?

2020-09-16 21:43 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
we wouldn't, just make ItemsToSign an array of ITaskItems.

2020-09-16 21:47 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
my.proj

```
<mytask
   myparameter="hi;bye;whatever" />

<ItemGroup>
  <myItems Include="hi;bye;whatever">
     <mymetadata>stuff</mymetadata
  </myItems
</ItemGroup>

<mytask
  <mytask
   myparameter="@(myItems)" />

``

if "mytask" is defined such that "myparameter" is `string [] myparameter {get;set;}", then both of the above calls behave the same.

if "mytask" is defined such that "myparamter" is `ITaskItem [] myparameter {get;set;}", then the second call will pass the metadata as well.

2020-09-16 21:49 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
That's interesting. I didn't realize that it was backwards compatible with the existing implementation that used the string array.

2020-09-16 21:54 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +        public ITaskItem[] ItemsToSignPostBuild { get; set; }
Ok then it makes sense. Did that so not to break current usage and didn't know that was supported.

2020-09-21 18:31 UTC, jcagme commented
Closing this since the refactor I did was in a different branch. I addressed comments here over there

2020-09-21 18:31 UTC, closed without merging