Enable post build signing flow
dotnet/arcade pull request #6206
Opened 2020-09-18 19:16 UTC by mmitche

This change makes post build signing more formalized in arcade.
Addresses https://github.com/dotnet/arcade/issues/6205

If PostBuildSign=true, then ItemsToSign is by default blank, and artifacts to sign are included in the manifest.
If PostBuildSign=false or not set, the normal flow is used.

2020-09-18 19:22 UTC, mmitche commented
This change is not breaking based on current defaults (PostBuildSIgn is not true), but will may reaction in a couple repos where we set ItemsToSign right before publishing runs, or that don't use ItemsToSignPostBuild. Places to check:
- runtime
- windowsdesktop
- aspnetcore (I think this one just needs removal).

2020-09-18 19:52 UTC, missymessa commented
Created an issue to get some validation around these changes: https://github.com/dotnet/arcade/issues/6208

2020-09-21 20:59 UTC, chcosta requested changes

2020-09-21 20:59 UTC, chcosta commented on Documentation/ArcadeSdk.md
> +  List of file names (without paths) to sign in post build. May only contain files that are published. All files embedded in a container file are signed (recursively) unless specified otherwise.
```suggestion
  List of file names (without paths) to sign in post build release pipeline. May only contain files that are published. All files embedded in a container file are signed (recursively) unless specified otherwise.
```

2020-09-21 20:59 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <ItemsToSignPostBuild Include="@(_DefaultItemsToSign->'%(Filename)%(Extension)')" Condition="'$(PostBuildSign)' == 'true'" />
Do you think it's worth adding `$(ArtifactsPackagesDir)**\*.wixpack.zip` to the default post build items to sign so that repos don't have to manually add those zips if they switch to post-build signing?  ie, if the itemstosign include an msi or exe or wixlib, we can only sign /repack them if wixpacks are available.

2020-09-21 20:59 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <AllowEmptySignList Condition="'$(PostBuildSign)' != 'true'">false</AllowEmptySignPostBuildList>
The opening and closing tags here don't match.

2020-09-21 21:11 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <AllowEmptySignList Condition="'$(PostBuildSign)' != 'true'">false</AllowEmptySignPostBuildList>
Repos are including all *.zip already, so that shouldn't be a big deal, But isn't it that we say to sign an MSI and exe, and it implicitly signs the wixpack contents instead?

2020-09-21 21:11 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <ItemsToSignPostBuild Include="@(_DefaultItemsToSign->'%(Filename)%(Extension)')" Condition="'$(PostBuildSign)' == 'true'" />
Repos are including all *.zip already, so that shouldn't be a big deal, But isn't it that we say to sign an MSI and exe, and it implicitly signs the wixpack contents instead?

2020-09-21 21:40 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <ItemsToSignPostBuild Include="@(_DefaultItemsToSign->'%(Filename)%(Extension)')" Condition="'$(PostBuildSign)' == 'true'" />
Yes, that's what it does, it needs the wixpack in the ItemsToSign list though, otherwise it doesn't know where the contents come from. ie, SignTool needs to find out about the wixpacks somehow.  

Yeah, the repos I've seen are already including zips, just might be future proofing if there was a repo that only produced msi's and wasn't including zips because they didn't now they produced any.

2020-09-21 21:52 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <ItemsToSignPostBuild Include="@(_DefaultItemsToSign->'%(Filename)%(Extension)')" Condition="'$(PostBuildSign)' == 'true'" />
Fine by me.

2020-09-21 21:54 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
> +    <ItemsToSignPostBuild Include="@(_DefaultItemsToSign->'%(Filename)%(Extension)')" Condition="'$(PostBuildSign)' == 'true'" />
Updated

2020-09-21 21:58 UTC, chcosta approved these changes

2020-09-22 15:02 UTC, merged

2020-10-24 15:43 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/GenerateBuildManifest.proj
> +  <Error Condition="'$(AllowEmptySignPostBuildList)' != 'true' AND '@(ItemsToSignPostBuild)' == ''"
C:\git\vstest\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20522.2\tools\SdkTasks\GenerateBuildManifest.proj(32,3): error : The <Error> tag is no longer supported as a child of the <Project> element. Place this tag within a target, and add the name of the target to the "InitialTargets" attribute of the <Project> element.

I'm going to submit a PR to fix this.

2020-10-24 15:45 UTC, ViktorHofer commented on src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/GenerateBuildManifest.proj
> +  <Error Condition="'$(AllowEmptySignPostBuildList)' != 'true' AND '@(ItemsToSignPostBuild)' == ''"
https://github.com/dotnet/arcade/pull/6452