Sign tool with map
dotnet/arcade pull request #6217
Opened 2020-09-21 20:14 UTC by jcagme

All existing test cases passed a long with the corresponding PostBuild equivalents.

Fixes https://github.com/dotnet/core-eng/issues/10815

Windows desktop validation build is still running but things look good https://dnceng.visualstudio.com/internal/_build/results?buildId=823784&view=results

2020-09-21 22:12 UTC, chcosta requested changes

2020-09-21 22:12 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                ITaskItem itemToSign = _itemsToSignPostBuild.Where(i => i.ItemSpec == fullPath).FirstOrDefault();
is the path interesting?  I thought we wanted to resolve collisions with identical content hashes, not paths.

2020-09-21 22:12 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                        // by ascendent BARBuildOd
```suggestion
                        // by ascendent BARBuildId
```

2020-09-21 22:12 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
make "BARBuildId" a const string and name it something more generic like ... I don't know what, but something about build order or ... actually I can't think of a better name, but there has to be something more generic and less BAR related than "BARBuildId".

2020-09-21 22:14 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
`CollisionResolutionId`?  `CollisionPriorityId`?

2020-09-21 22:16 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
`ContentCollisionId`?

2020-09-21 22:17 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
`ContentNodeId`?

2020-09-22 15:27 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                ITaskItem itemToSign = _itemsToSignPostBuild.Where(i => i.ItemSpec == fullPath).FirstOrDefault();
We use the path to get the actual ITaskItem but we use the hash to determine collisions.

2020-09-22 15:29 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
While we'll use this for ordering and collision resolution at the end of the day it is a BAR Id so I feel the attribute name should represent that. @missymessa any preferences?

2020-09-22 15:36 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
I think BARBuildId reflects exactly what the value is. I see Chris's point for making the name generic, but not sure if that's necessary since most folks who use Arcade understand what a BARBuildId is and unlikely folks will need that value outside of the post build signing process.

2020-09-22 15:38 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
I like the idea of having this be opt-in better. If we define the process is post-build given the existence of BAR ids in ItemsToSign takes us to the same place. Eventually, when we have moved all the repos this will be the default flow and we can stop making a difference and stop worrying about backwards compatibility, etc.

2020-09-22 15:45 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
> when we have moved all the repos this will be the default flow

Maybe? There will likely be some repos that don't move to the post build process, so we probably can't fully count on that.

2020-09-22 15:48 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
Special emphasis in **all** which might be a never thing. While I tried to say is that having a control variable like `IsPostBuild` is safer than start "mixing" new flow with existing, also makes things easier to debug and understand

2020-09-22 15:51 UTC, missymessa commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
If we removed this flag, what's impacted? I think we want to make sure that if there are collisions in the Items to Sign (and the other *SignInfo arrays) we'd want to make sure that the extra metadata is there as expected so that we can prioritize which values to use. If we pull out the `isPostBuild` flag, we'd have to find a way to make that work.

2020-09-22 16:26 UTC, chcosta requested changes

2020-09-22 16:26 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string fileHash = ContentUtil.HashToString(ContentUtil.GetContentHash(fullPath));
isn't this already defined as `hash`?

2020-09-22 16:26 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    barBuildId = itemToSign.GetMetadata("BARBuildId");
1. Even if it stays as "BARBuildId", the value should be a const string
2. I disagree, there's no reason to bring the concept of BAR into SignTool.  At the end of the day, it's just a metadata value for resolving collisions, someone (even us) could setup a different process that just passed in an incremental value as the collision resolution value and the process should still work.  Calling it BarBuildId is confusing because it presumes a dependency on BAR which doesn't exist.  I actually think the metadata value on ItemsToSign shouldn't be called BARBuildId either.

2020-09-22 16:26 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
> `IsPostBuild` is safer than start "mixing" new flow with existing, also makes things easier to debug and understand

Maybe, during development, it's easier, but I think it's less useful in the long term.  It essentially creates an entirely separate block of code which can deviate more and more as time goes on.  I'd prefer that this concept of collision resolution was intrinsic to the tool.  I think that each file should just preserve its resolution Id as it is being defined.  If we encounter a new file with the same content hash and a smaller resolution id, then we throw away the old info and save the new info.  We don't need to know build up a package map, we just pass along the resolution id as we start tracking files.

2020-09-22 16:26 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            ITaskItem[] itemsToSign,
With "IsPostBuild" as a separate block, if we add some new functionality, then we have to test everything twice, once with "IsPostBuild==true" and once with "IsPostBuild==false", instead of just validating "did I break collision resolution?"

Also, if the concept is intrinsic, then you don't have to have a "FileSignInfo" and a "FileSignInfoPostBuild", it's just "FileSignInfo".  You probably do still need to build up a hash set of signing info data by resolution id though.

2020-09-22 16:26 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            _itemsToSignPostBuild = itemsToSign;
`_itemsToSignPostBuild` is defined twice.

`ItemsToSign` should just be changed to an ITaskItem instead of creating a separate variable.

2020-09-23 15:37 UTC, jcagme commented
Windows Desktop build with test task https://dnceng.visualstudio.com/internal/_build/results?buildId=826786&view=results

2020-09-23 17:47 UTC, chcosta commented
I probably won't be able to fully review this til this afternoon, but taking a quick step through the code, I'm really liking the direction this is now going.  Thanks for the rework.

2020-09-23 17:52 UTC, jcagme commented
> I probably won't be able to fully review this til this afternoon, but taking a quick step through the code, I'm really liking the direction this is now going. Thanks for the rework.

Thanks. The thing I found useful which don't know if aligns with your comments is keeping a map with hash to collusion id mostly for nested assets. Having this helped not modifying a lot the existing code and at the same time for collision resolution.

2020-09-23 17:55 UTC, chcosta commented
> The thing I found useful which don't know if aligns with your comments is keeping a map with hash to collusion id

haha, that's the thing that jumped out at me and made me think I needed to spend some qt thinking about / looking at this later this afternoon.  While it jumped out at me, I didn't have a negative reaction to it, I just thought that I needed to consider further why you made that choice.

2020-09-23 17:59 UTC, mmitche commented
I'll try and get to this around midday.

2020-09-23 17:59 UTC, jcagme commented
> > The thing I found useful which don't know if aligns with your comments is keeping a map with hash to collusion id
> 
> haha, that's the thing that jumped out at me and made me think I needed to spend some qt thinking about / looking at this later this afternoon. While it jumped out at me, I didn't have a negative reaction to it, I just thought that I needed to consider further why you made that choice.

For sure. Most likely there is a thing I can reuse in the code already but I didn't find an option that fully gave me that when I wanted it. There are some objects with hashes and SignInfo but they are populated after the `ExtractSignInfo` which doesn't really help, but yeah, open to make this better.

2020-09-23 18:02 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/SignToolTask.cs
> +            Configuration configuration = null;
Changed this so it is not initialized to null and instead does the `new Configuration(` in line 225

2020-09-23 22:24 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +        internal Dictionary<string, string> _hashToCollisionIdMap;
Can you add a comment about what this map is for?

2020-09-23 22:29 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string collisionPriorityId = itemToSign.GetMetadata(SignToolConstants.CollisionPriorityId);
Is the collisionPriorityId what we were saying would be BAR build ID?

2020-09-23 22:34 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                if (_hashToCollisionIdMap.TryGetValue(stringHash, out collisionPriorityId))
Nit, reverse the sides of this and remove the empty if.

2020-09-23 22:36 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    string parentStringHash = ContentUtil.HashToString(ContentUtil.GetContentHash(containerPath));
So is the idea here that if I have a container, say foo.zip. Which contains  bar.nupkg, which contains baz.dll. if foo.zip came from bar ID 10, then the hash of bar.nupkg as well as baz.dll will have collisionId entries in the map as 10?

2020-09-23 22:39 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    string parentStringHash = ContentUtil.HashToString(ContentUtil.GetContentHash(containerPath));
Will the content hash of this containerPath ever change over the course of signtool execution? Basically, is this happening all pre-signing?

2020-09-23 22:40 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                if (string.Compare(collisionPriorityId, existingCollisionId) < 0)
If this is about comparing BAR ids, I'd add a comment here as to the implications of this decision

2020-09-23 22:41 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/SignInfo.cs
> +        internal string CollisionPriorityId { get; }
Can you add a comment as to what this property is intended for?

2020-09-23 22:44 UTC, mmitche reviewed
Logic looks sound to me. A few minor bits of feedback re: readability. 

Also, can you add some unit tests for this functionality?

2020-09-23 22:48 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string collisionPriorityId = itemToSign.GetMetadata(SignToolConstants.CollisionPriorityId);
Yes. @chcosta suggested that we might end up using a different value here so using something more general is useful

2020-09-23 22:51 UTC, mmitche commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string collisionPriorityId = itemToSign.GetMetadata(SignToolConstants.CollisionPriorityId);
Ahh yeah I agree with the naming, just clarifying for my understanding.

2020-09-23 22:54 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    string parentStringHash = ContentUtil.HashToString(ContentUtil.GetContentHash(containerPath));
Yes, we use the original assets since this is called when we are processing the original list of files or the just unpacked container which is useful since we know "right away" whether there are collisions or not and update the values if needed.

2020-09-24 01:56 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                    string parentStringHash = ContentUtil.HashToString(ContentUtil.GetContentHash(containerPath));
Yes unless bar.nupkg is an input of ItemsToSign and has a predefined BAR ID.

2020-09-24 03:14 UTC, jcagme commented
New WD build with generated test Arcade SDK: https://dnceng.visualstudio.com/internal/_build/results?buildId=828572&view=results

2020-09-24 17:18 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string existingCollisionId = _hashToCollisionIdMap[stringHash];
The way I envisioned this working would be, rather than a map, the CollisionPriorityId is added to fileSignInfo.  In ExtractSignInfo, you don't do any collision resolution.  Instead, you just return the sign info and then in the next level up (`TrackFile`) you check for collisions.  Sadly, it appears that signtool doesn't keep a `<ContentHash, FileSignInfo>` map, so my vision doesn't "just work".  Your solution seems fine.

2020-09-24 17:53 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +                string existingCollisionId = _hashToCollisionIdMap[stringHash];
> Sadly, it appears that signtool doesn't keep a <ContentHash, FileSignInfo> map, so my vision doesn't "just work". Your solution seems fine.
This.

2020-09-24 18:25 UTC, chcosta approved these changes
Full disclosure, I didn't examine every line in this, but the design seems reasonable.  Assuming we've validated the changes with one of Missy's builds (and addressed others PR feedback), this looks good to me.

2020-09-24 18:25 UTC, chcosta commented on src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs
> +        private static readonly ITaskItem[] s_fileExtensionSignInfoPostBuild = new ITaskItem[]
nit: post build doesn't need to be a concept here, I'd prefer a name like `s_fileExtensionSignInfoAsTaskItems` or something.

2020-09-24 18:25 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            string containerPath = null)
Isn't this ("containerPath") kind of duplicating the intent of `_whichPackagesTheFileIsIn`?  ie, we could probably get rid of `_whichPackgesTheFileIsIn` and derive the same info from `_filesByContentKey`.  Maybe file an issue and follow up on that as cleanup?

2020-09-24 18:38 UTC, jcagme commented on src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs
> +        private static readonly ITaskItem[] s_fileExtensionSignInfoPostBuild = new ITaskItem[]
Forgot to remove this since is not used anymore

2020-09-24 18:40 UTC, jcagme commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            string containerPath = null)
It's related but different. I use `containerPath` ahead of when `_whichPackagesTheFileIsIn`. Pretty sure `_whichPackagesTheFileIsIn` is used somewhere else while `containerPath` is only useful in this context

2020-09-24 19:33 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            string containerPath = null)
Pretty sure it's only used to provide more info in error output, and that could be derived from containerPath as well.

2020-09-24 23:34 UTC, jcagme commented
WD build after the latest changes https://dnceng.visualstudio.com/internal/_build/results?buildId=829565&view=results, also a pipeline build where signing worked https://dnceng.visualstudio.com/internal/_build/results?buildId=829805&view=logs&j=9ff0e0af-24e7-5b0f-fa76-5e12fc9920ef&t=8f905036-a67b-5486-9ab7-4e85472e8c79. Merging now

2020-09-24 23:34 UTC, merged