Make SignTool allow symbols.nupkgs to be unsigned
dotnet/arcade pull request #6291
Opened 2020-09-30 23:31 UTC by jonfortescue

Closes #6192.

SignTool validation will ignore unsigned .symbols.nupkgs (but won't throw errors if they happen to be signed). Also added a tests to validate this behavior.

2020-10-02 17:22 UTC, chcosta requested changes

2020-10-02 17:22 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            }
Rather than iterate over ever extension identified by a linq expression, you could just use a single linq expression.
```
            // handle multi-part extensions like ".symbols.nupkg" specified in FileExtensionSignInfo
            if (_fileExtensionSignInfo != null)
            {
                extension = _fileExtensionSignInfo.OrderByDescending(o => o.Key.Length).FirstOrDefault(f => fileName.EndsWith(f.Key, StringComparison.OrdinalIgnoreCase)).Key;
            }

```

2020-10-02 17:22 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/BatchSignUtil.cs
> +                else if (fileName.IsNupkg() && !fileName.IsSymbolNupkg())
I think that the cleaner way to handle this is to change the definition of "IsNupkg" to something like

```
        internal static bool IsNupkg(string path)
            => Path.GetExtension(path).Equals(".nupkg", StringComparison.OrdinalIgnoreCase)
             && !IsSymbolsNupkg(path);
```
that way you don't have to try to track down all the places where a nupkg is referenced, and future changes don't have to worry about knowing about that particular quirk.  Note that there still might be places where you have to define behavior based on `IsSymbolsNupkg`, but you can stop defining behavior by `IsNupkg && !IsSymbolsNupkg`

2020-10-02 17:34 UTC, jonfortescue commented on src/Microsoft.DotNet.SignTool/src/Configuration.cs
> +            }
i like clever things like this!

2020-10-02 18:25 UTC, chcosta commented
Have you run this change through the arcade-validation repo?  I could imagine that this breaks signing validation.

2020-10-06 00:26 UTC, jonfortescue commented
@chcosta It took me a lot of fighting with the arcade-validation build but I think I have an acceptable run proving it works okay? https://dev.azure.com/dnceng/internal/_build/results?buildId=842240&view=results

Ricardo and I had trouble dealing with the publishing testing for reasons unrelated to the changes so we took that stage out. Otherwise, it is working perfectly.

2020-10-06 00:51 UTC, chcosta commented
Was this the problem you ran into? https://github.com/dotnet/arcade/issues/6313

2020-10-06 00:54 UTC, jonfortescue commented
yes, essentially. we ended up routing around it but still ended up hitting a roadblock where the darc build it triggered was unable to restore the packages bc it didn't have the general-testing channel. See logs [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=842162&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a&l=34).

2020-10-06 18:04 UTC, chcosta approved these changes
Sadly, arcade-validation doesn't appear to actually validate the scenario I was concerned about.  I was concerned that this change would go in.  SignTool would permit unsigned symbols.nupkgs, and then signing validation would start failing in repos.  But...

- I checked some repos, like extensions and the other validation type pipelines I could find, that still do signing validation, and they're not checking symbols.nupkgs, only nupkgs (they're probably just checking shipping packages, not nonshipping.

- you're not changing the behavior here that much, if a repo was not signing symbols.nupkgs, then they would have been broken before, so this shouldn't break anyone.

All that is to say, LGTM

2020-10-06 18:19 UTC, missymessa commented
> Sadly, arcade-validation doesn't appear to actually validate the scenario I was concerned about. I was concerned that this change would go in. SignTool would permit unsigned symbols.nupkgs, and then signing validation would start failing in repos. But...
> 
> * I checked some repos, like extensions and the other validation type pipelines I could find, that still do signing validation, and they're not checking symbols.nupkgs, only nupkgs (they're probably just checking shipping packages, not nonshipping.
> * you're not changing the behavior here that much, if a repo was not signing symbols.nupkgs, then they would have been broken before, so this shouldn't break anyone.

@chcosta could you open an issue for our epic to ensure that we exercise these scenarios in Arcade Validation, even if we're confident they won't be a problem?

2020-10-06 22:27 UTC, merged