Unseal PipelinesLogger For Extension in dotnet-release
dotnet/arcade pull request #6535
Opened 2020-11-07 00:09 UTC by Tohron

@chcosta suggested I alter my PR for identifying logged errors in dotnet-release operations to use Arcade telemetry.
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/10958?discussionId=53366
 That would seem to require unsealing PipelinesLogger so that I can make a child class in dotnet-release with functions that take arguments regarding whether logged errors are infra or product errors.

2020-11-09 17:13 UTC, chcosta commented
I think this needs more of a refactor than an unsealing of the class.  My comment about "unseal the class if you need to", was a bit misleading because the intent was to let you know that you should feel free to make improvements in Arcade rather than coding around Arcade, but it was a very indirect way of saying it.  My bad.

ie, at its core, the PipelineLogger is a basic logger, a message builder, and then a bunch of MSBuild stuff.  

`PipelineLogger = [ILogger](https://github.com/dotnet/msbuild/blob/master/src/Framework/ILogger.cs) + message builder + context map`

All the "power" that we get from the logger comes from the [message builder](https://github.com/Microsoft/azure-pipelines-tasks/blob/601dd2f0a3e671b19b55bcf139f554a09f3414da/docs/authoring/commands.md).  It seems simple, but it gives us a standard format which empowers azdo to do neat things and allows our powerbi reports to aggregate data (which AzDo collects for us via the Azure DevOps Timeline API).

I think the change that is needed here is to break out the "message builder" functionality to a separate class which can be used both by the MSBuild logger and by the C# logger you're writing in dotnet-release.

2020-11-09 17:14 UTC, chcosta requested changes
I gave unspecific directional guidance (see my comment).  I think this needs to go a slightly different direction.

2020-11-11 16:51 UTC, chcosta requested changes
I'd like to see the end-to-end set of changes before this gets merged, ie, a build and/or tests out of dotnet-release which uses a modified version of Arcade to log errors.

2020-11-11 16:51 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs
> -        internal sealed class MessageBuilder
Move this into its own class (file)

2020-11-11 16:51 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs
> -            internal void Start(string kind)
How do you imagine this will be used?  Do you have a build (or tests) in dotnet-release where you're actually consuming this class in your logger?  It would be good to see  / understand the usage before making any changes to Arcade so we can ensure the right change is happening here.

2020-11-11 17:06 UTC, chcosta commented on src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs
> -            internal void Start(string kind)
Yep.  It'd be good to see the change is validated end-to-end before merging any change to Arcade.

2020-12-16 17:44 UTC, Tohron commented on src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs
> -            internal void Start(string kind)
The changes work in local testing, which I think is sufficient justification to merge.

2020-12-16 17:56 UTC, adiaaida approved these changes

2020-12-16 18:01 UTC, adiaaida commented
@Tohron can you confirm this worked locally for you?

2020-12-16 18:03 UTC, Tohron commented
> @Tohron can you confirm this worked locally for you?

I was able to access the class and use it to format log output successfully

2020-12-16 19:33 UTC, MattGal approved these changes

2020-12-16 19:43 UTC, merged

2021-01-07 16:48 UTC, missymessa commented
I believe this PR is causing builds to fail using versions of Arcade that include this change. Here is the PR of Arcade into Arcade Validation: https://github.com/dotnet/arcade-validation/pull/2040

2021-01-07 17:31 UTC, Tohron commented
I've since made a new, related PR - are you sure that's not the cause?
https://github.com/dotnet/arcade/pull/6739

2021-01-07 17:45 UTC, missymessa commented
Yes, sorry, it was the second PR that was the culprit. I had both this PR and the second PR open while I was investigating the error last night.