Tests for BuildManifestUtil and some fixes in the process
dotnet/arcade pull request #6550
Opened 2020-11-11 23:55 UTC by mmitche

The tests cover the basic creation of the build model from TaskItems, which is what we use to populate it in a build task. They also cover the round-tripping of this model into xml and back out, ensuring that values are preserved.

On the fixes/tweaks side of things:
- Adds an error if an ItemToSign is not in the Blob or PackageArtifacts
- Adds some comments
- Renames some confusing parameters (BuildProperties -> manifestBuildData), since that's what it's called everywhere else.
- Removes some information on the SigningInformatio model that was either unnecessary or duplicated on the parent build model.
- Fixes an issue where the signing model where CloneCustomMetadata was returning a CopyOnWriteDictionary, but we were attempting to cast it to Dictionary (resulting in null ref). Instead cast to IDictionary.
- Ensures that RelativeBlobPath is set on the ITaskItem metadata for a blob. If it isn't, we'd set the blob Id to "". Which is wrong.

2020-11-17 00:21 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            Assert.Throws<ArgumentNullException>(() =>
Can you refactor your asserts to use Fluent Assertions? https://github.com/dotnet/core-eng/blob/master/Documentation/Validation/TestingGuidance.md#fluentassertions

2020-11-17 00:24 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +        private const string _testAzdoRepoUri = "https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-buildtest";
Just verifying that all these string are fake data?

2020-11-17 19:24 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var localPackagePath = TestInputs.GetFullPath(Path.Combine("Nupkgs", "test-package-a.nupkg"));
I don't like us setting a precedent for having physical files for testing in this project. It would be better for us to mock out the functionality that does work on these files, and mock out the results that other parts of this project consume, for testing purposes. 

My worry is that others will see these files and add more physical files to the project: some that may be very large or, naively, introduce not-fake files for tests in a public repo. 

(I realize that some of these files are already in existence, prior to this PR, but we should set a better example going forward).

2020-11-17 19:26 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var taskLoggingHelper = new Microsoft.Build.Utilities.TaskLoggingHelper(stubTask);
This seems to be duplicated in a few tests. Maybe consolidate it into a Setup method to execute when the tests run?

2020-11-17 19:33 UTC, missymessa requested changes
Looks good, so far, just a few tweaks I recommended. I was able to run all these tests locally, without any extra set up, so yay 👍

2020-11-18 16:52 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +        private const string _testAzdoRepoUri = "https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-buildtest";
Yeah that's fake.

2020-11-18 17:40 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var localPackagePath = TestInputs.GetFullPath(Path.Combine("Nupkgs", "test-package-a.nupkg"));
I tried a refactor to make this a reality and really didn't like the result. The root of the problem is really that `BuildManifestUtil` is a static utility class that has a fair bit of interdependency between its methods. Extracting the nupkg reading into an interface, then feeding that through all the various layers of `BuildManifestUtil` led to a very messy ugly API. I'm not a huge fan of making a bad API for the sake of testability.

I think the right thing to do is to replace `BuildManifestUtil` with a `BuildManifestBuilder`, as that's basically what it's doing, with appropriate nupkg reader interfaces, etc. However I think that is a pretty decent sized work item.

2020-11-18 17:40 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var localPackagePath = TestInputs.GetFullPath(Path.Combine("Nupkgs", "test-package-a.nupkg"));
@missymessa What do you think?

2020-11-18 19:15 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var localPackagePath = TestInputs.GetFullPath(Path.Combine("Nupkgs", "test-package-a.nupkg"));
Let's write a work item to refactor that if it seems like it's too much work to refactor right now. I agree we should be doing the right thing, so if that requires a greater refactor, let's write up an issue to handle that.

2020-11-18 19:38 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +            var localPackagePath = TestInputs.GetFullPath(Path.Combine("Nupkgs", "test-package-a.nupkg"));
Yep will do.

2020-11-18 19:54 UTC, missymessa approved these changes

2020-11-18 22:23 UTC, jonfortescue commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +using Xunit;
Should these be nunit instead? I thought that was what we were coalescing toward

2020-11-18 23:08 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +using Xunit;
As far as I can tell there is no use of NUnit in the arcade repo...so it should be done all at once.

2020-11-18 23:17 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/SetupTargetFeedConfigV3Tests.cs
> +            AreEquivalent(expectedFeeds, actualFeeds).Should().BeTrue();
If these are collections, you can do: 

`actualFeeds.Should().BeEquivalentTo(expectedFeeds)`

https://fluentassertions.com/collections/

2020-11-19 00:31 UTC, mmitche commented
/azp run

2020-11-19 03:09 UTC, merged