Symbols should be published to MSDL based on channel + assets and symbols integration
dotnet/arcade pull request #6568
Opened 2020-11-17 05:52 UTC by epananth

Issue : https://github.com/dotnet/arcade/issues/6233

This also includes symbols and assets integration

Test : https://dnceng.visualstudio.com/internal/_build/results?buildId=888262&view=logs&s=380ab8c6-4139-55ff-15c4-fb48260f4dca

2020-11-17 06:00 UTC, epananth commented on eng/Versions.props
> +    <MicrosoftIdentityModelClientsActiveDirectoryVersion>3.17.2</MicrosoftIdentityModelClientsActiveDirectoryVersion>
Symuploader API uses Microsoft.IdentityModel.ActiveDirectory = 3.19.8, having two different version errors out. So I had to downgraded this.

2020-11-17 15:18 UTC, riarenas commented on eng/Version.Details.xml
> +    <Dependency Name="Microsoft.SymbolUploader" Version="1.1.152002">
Do we still need the dependency on the symbol uploader build task?

2020-11-17 15:21 UTC, riarenas commented on eng/Versions.props
> +    <MicrosoftIdentityModelClientsActiveDirectoryVersion>3.17.2</MicrosoftIdentityModelClientsActiveDirectoryVersion>
It looks like the package is only used by the aka.ms links manager. The test build published links, so I think this is fine?

2020-11-17 15:51 UTC, riarenas commented
@epananth can you perform a test publishing to both locations? 

I see that we're losing some informational logging. The old task used to print out something like:

```
  No symbol file(s) were found to publish.
  Publishing symbol packages to https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection
  Publishing symbol packages to https://microsoft.artifacts.visualstudio.com/DefaultCollection
  Performing symbol publish...
  SymbolServerPath: https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection
  ExpirationInDays specified: 3650
  Symbol publish finished
  Performing symbol publish...
  SymbolServerPath: https://microsoft.artifacts.visualstudio.com/DefaultCollection
  ExpirationInDays specified: 3650
  Symbol publish finished
```

While the log from the test build only seems to show a lot of output of the form: 
```
  Symbol file D:\a\1\a\tempDir\Microsoft.Cci.Extensions.6.0.0-beta.20566.11.symbols.nupkg should publish to Symweb.
  
  Symbol file D:\a\1\a\tempDir\Microsoft.DotNet.ApiCompat.6.0.0-beta.20566.11.symbols.nupkg should publish to Symweb.

 ```
But then it says:

```
Publishing to Symweb :
  Succeeded publishing package 'D:\a\1\a/PackageArtifacts/Microsoft.Cci.Extensions.6.0.0-beta.20566.11.nupkg' to feed https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json
```

The job seems to be doing the right thing however, so this probably just means we need to improve the logging.

2020-11-17 15:53 UTC, riarenas commented on src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishArtifactsInManifest.proj
> +      <PublishSpecialClrFiles Condition="'$(PublishSpecialClrFiles)' == ''">false</PublishSpecialClrFiles>
What is this property? should it be documented up top?

2020-11-17 15:55 UTC, riarenas commented on eng/Versions.props
> +    <MicrosoftDotNetSymbolUploaderVerison>1.1.152002</MicrosoftDotNetSymbolUploaderVerison>
Typo: MicrosoftDotNetSymbolUploaderVerison -> MicrosoftDotNetSymbolUploaderVersion

I think bad things would happen after the next symuploader dependency update if this is left like this.

2020-11-17 15:55 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/ParseBuildManifest.cs
> +
```suggestion
```

2020-11-17 15:56 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/ParseBuildManifest.cs
> +using Microsoft.SymbolUploader;
[nit] let's keep these sorted

2020-11-17 15:58 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +        /// Publishes symbol, dll and pdb files to symbol server.
The publishSpecialClrFiles parameter is missing here

2020-11-17 16:00 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +        /// <param name="symbolPublishingExclusionsFile">Right now we do not add any files to this, so this is going to be null</param>
Do any repos use the exclusion file? If this is always going to be null, does it make sense to remove it instead of keeping it as a parameter all the way from the msbuild?

2020-11-17 16:01 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +            Log.LogMessage(MessageImportance.High, "\nPublishing Symbols to Symbol server: ");
Since there are many, should this read `Symbol Servers`?

2020-11-17 16:09 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +            List<string> publishFilesToSymweb = new List<string>();
It seems to me like there's no reason to keep two lists here, they will either be empty, or contain the same files. Since the channel should know which servers it's supposed to publish to, can't we just keep a single list?

The log statement can also be condensed a little, only mentioning the symbol servers where they will be published once before iterating the list of files and listing them.

2020-11-17 16:44 UTC, riarenas requested changes
The test build looks like it's doing the right thing. Just a bunch of questions about potential refactoring and maybe some tests?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +
There's something wrong with the indentation  in this entire block

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                                if (feedConfig.PublishToMsdl)
Similar to my "condense into one list" comment: if we keep a single list of files (The fileEntries array is probably good enough) this instead becomes the place to add which servers they should be going to, and the credential to that server. If in the future we need to add more servers, it's just a matter of adding the URL as a constant, adding it to the targetFeedConfigs, and we don't need to touch this part of the code. Then in LN 369, you could iterate through the list of servers and credentials, since those seem to be the only differences between both calls.

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +
```suggestion

```

[nit] extra blank line

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                string temporarySymbolsLocation = Path.GetFullPath(Path.Combine(BlobAssetsBasePath, @"..\", "tempDir"));
[nit] We can be more specific than `tempDir`. Could it just be `symbols`, or `tempSymbols`?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                if (!Directory.Exists(temporarySymbolsLocation))
What's the implication of this directory already existing and having something in it?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +        /// Copying symbol files to temporary location is required because the symUploader API needs read/write access to the files, since we publish blobs and symbols in parallel this will cause IO
[nit] I think this is a great comment for the place where this is called, but I think the summary should just explain what the function does in a vacuum.

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    Log.LogMessage(MessageImportance.Low, $"Successfully copied file {sourceFile} to {destinationFile}.");
Do we need to copy anything from the pdbartifacts? or is it an exclusive behavior of symbol nupkgs since they also go to blob storage?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +        private void DeleteSymbolTemporaryFiles(string temporarySymbolsLocation)
I think this may be unnecessary since you are copying the symbols to the agent's workspace directory, which gets cleaned up automatically. I think it's a good idea to clean up, but maybe it shouldn't fail the task if it fails?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs
> +        private bool PublishToMsdl { get; set; }
I think I'd like to see this as a list of known symbol servers to publish to instead of a bool. What happens if we need to publish to a third place?

(feel free to tell me why this wouldn't be worth it)

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs
> +        public bool IsPublishToMsdl { get; }
[nit] Since this isn't something that is, but something that should happen when the variable is set, I think shouldPublishToMsdl is more appropriate (if you still want to go with the bool approach)

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSymbolsHelper.cs
> +    internal class Tracer : Microsoft.SymbolStore.ITracer
Does the symbol uploader not provide a default tracer so we need to implement it ourselves?

2020-11-17 16:44 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/SetupTargetFeedConfigV3Tests.cs
> +                    false,
Any tests for the new functionality?

2020-11-17 20:20 UTC, epananth commented on eng/Version.Details.xml
> +    <Dependency Name="Microsoft.SymbolUploader" Version="1.1.152002">
Yes cos V2 still uses build task. We cannot remove it till we get rid of V2 completely.

2020-11-17 20:21 UTC, epananth commented on eng/Versions.props
> +    <MicrosoftIdentityModelClientsActiveDirectoryVersion>3.17.2</MicrosoftIdentityModelClientsActiveDirectoryVersion>
Yes, I was not sure if this will cause any problems.. Looks like it won't..

2020-11-17 20:51 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +        /// <param name="symbolPublishingExclusionsFile">Right now we do not add any files to this, so this is going to be null</param>
I did a general check to see if any repos use this functionality. I don't think they do, but im not a 100% on this. so I kept this functionality so incase it breaks anything then I can fix this. If it doesn't then I can probably remove this param altogether..

2020-11-19 06:21 UTC, epananth commented
[Updated tests]
Publish to SymWeb : https://dnceng.visualstudio.com/internal/_build/results?buildId=891763&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a
Publish to Msdl : https://dnceng.visualstudio.com/internal/_build/results?buildId=892004&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a&l=317

2020-11-19 06:23 UTC, epananth commented
Tests are going to be added as a part of separate issue -> https://github.com/dotnet/arcade/issues/6591

2020-11-19 06:25 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                if (!Directory.Exists(temporarySymbolsLocation))
added cleaning the directory before doing copy

2020-11-19 06:32 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    Log.LogMessage(MessageImportance.Low, $"Successfully copied file {sourceFile} to {destinationFile}.");
We don't need to copy these files. This is only to avoid I/O exceptions for symbol blob uploads.

2020-11-19 06:35 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSymbolsHelper.cs
> +    internal class Tracer : Microsoft.SymbolStore.ITracer
I tried to do that, unfortunately that didn't work. So I had to copy this class too..

2020-11-19 06:35 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/SetupTargetFeedConfigV3Tests.cs
> +                    false,
going to be a part of https://github.com/dotnet/arcade/issues/6591

2020-11-19 06:42 UTC, epananth commented on eng/Versions.props
> +    <MicrosoftDotNetSymbolUploaderVerison>1.1.152002</MicrosoftDotNetSymbolUploaderVerison>
I am def blind, I could not see this difference :D

2020-11-19 06:52 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +        private void DeleteSymbolTemporaryFiles(string temporarySymbolsLocation)
Not failing the task anymore, just printing it as a warning.

2020-11-19 06:55 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +            List<string> publishFilesToSymweb = new List<string>();
removed the extra list. I refracted this method..

2020-11-20 15:31 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +        private const string MsdlServerPath = "https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection";
```suggestion
        private const string MsdlServerPath = "https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection";
        
```
[nit] extra line so that it maintains the format of the file.

2020-11-20 15:49 UTC, riarenas reviewed
Looks mostly good to me. I think the only real thing is the fact that it seems like this change would make it so a channel can only publish to a single server.

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +            StringBuilder builder = new StringBuilder();
The builder variable could use a better name explaining what it's for

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +            if (Directory.Exists(temporarySymbolsLocation))
What should happen if the directory does not exist? Looks like we just don't do anything? should this be an error?

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                else
Does this mean we can't publish to both places at once? I believe we want some channels to publish to both places so this shouldn't be an if-else situation but probably adding it to a collection of (server, token) that you then iterated and call PublishSymbolsHelper.Publish on.

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                builder.Append($"\nPublishing symbol packages to {symbolServerPath}:");
[nit] I'd suggest using AppendLine so you don't have to add the `\n`s all over

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    File.Delete(file);
It's not obvious that this method should be deleting anything. I would probably have a separate method to clean the directory so that it's clearer when reading through ExecuteAsync

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    string[] fileEntries = Directory.GetFiles(temporarySymbolsLocation);
This is the same code as when you're cleaning up the folder earlier, I think you can just call this before calling `CopySymbolFilesToTemporaryLocation` and remove the deletion code from that method

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSymbolsHelper.cs
> +        readonly bool m_verbose;
```suggestion
        readonly TaskLoggingHelper _log;
        readonly bool _verbose;
```

I believe the convention is to not use m_ to name these

2020-11-20 15:49 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs
> +        private bool PublishToMsdl { get; set; }
We synced up, there's no reason to make it a list right now.

2020-11-20 15:52 UTC, riarenas commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                if (!Directory.Exists(temporarySymbolsLocation))
See https://github.com/dotnet/arcade/pull/6568#discussion_r527776693 and https://github.com/dotnet/arcade/pull/6568#discussion_r527777846

2020-11-20 19:03 UTC, mmitche commented
@epananth Can you run a test against a runtime build (e.g. a promotion would be fine) to gauge the performance?

2020-11-20 19:18 UTC, epananth commented
@mmitche sure. Will do.

2020-11-20 19:37 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                else
Yes you are correct!! I looked for v2 publishing and I thought we either publish to msdl or symweb cos of this 

https://github.com/dotnet/arcade/blob/953446fe5733165048586b8a9ffc5399df657f8b/eng/common/templates/post-build/post-build.yml#L279

I further investigated and found this 

https://github.com/dotnet/arcade/blob/953446fe5733165048586b8a9ffc5399df657f8b/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishToSymbolServers.proj#L95

Like discussed I will change it in a such a way, so that when it's public channel, publish to both servers, but when its publish to msdl it ONLY publishes to msdl.

2020-11-20 19:38 UTC, epananth commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    File.Delete(file);
Sure!

2020-11-21 01:52 UTC, epananth commented
Ran a couple of more builds with minor change of publishing to both Msdl and symweb for public channels and publishing only for msdl for internal channels 

Publishing to Msdl : https://dnceng.visualstudio.com/internal/_build/results?buildId=895087&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

Publishing to both Msdl and Symweb : https://dnceng.visualstudio.com/internal/_build/results?buildId=895064&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

2020-11-23 19:48 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs
> +        public string PdbArtifactsBasePath {get; set;}
Can you add comments for these properties?

2020-11-23 19:55 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                        3650,
We should pull this constant out into a class level constant. Doesn't need to be settable.

2020-11-23 19:57 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetFeedConfig.cs
> +        public bool PublishToMsdl { get; }
I would refactor this into two separate properties:
- PublishToSymWeb
- PublishToMsdl

2020-11-23 19:58 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                if (feedConfigsForSymbols.Any(x => x.PublishToMsdl))
I think this would be better as two separate properties, not assuming that if PublishToMsdl is false, then you should publish to symweb and msdl. I think it's a little unclear this way. Instead, better to have two properties and add symbol targets separately for each case.

2020-11-23 20:00 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                        targetChannelConfig.ShouldPublishToMsdl);
See the other comments about splitting this into two properties: ShouldPublishToMsdl and ShouldPublishToSymbweb.

This also gives us a way out if we needed to disable all symbol publishing for some reason (set both properties to false)

2020-11-23 20:02 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                DeleteSymbolTemporaryFiles(temporarySymbolsLocation);
We should probably extend the try/catch to include a finally and add the deletion code in the finally. 

            try
            {

            }
            catch
            {

            }
            finally
            {

            }

2020-11-23 20:04 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +                    string[] fileEntries = Directory.GetFiles(temporarySymbolsLocation);
You can also just do Directory.Delete(temporarySymbolsLocation, true)

2020-11-23 20:04 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs
> +            if (Directory.Exists(temporarySymbolLocation))
You can also just do Directory.Delete(temporarySymbolsLocation, true)

2020-11-23 20:06 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSymbolsHelper.cs
> +                        publishOperation.PublishFiles(fileInfos).GetAwaiter().GetResult();
>l [](start = 27, length = 1)

I would remove this and make this an async method.

2020-11-23 20:12 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/PublishingConstants.cs
> +                false),
See other comments about making this two properties. You could also make a flags enum, which may be better:

[Flags] enum SymbolTargets { None = 0, Symweb = 1, Msdl = 2 }

Then because we typically do either Msdl or MSDL and symweb, add the following constants:

private const InternalSymbolTargets = SymbolTargets.Msdl;
private const PublicAndInternalSymbolTargets = SymbolTargets.Msdl | SymbolTargets.Symweb;

Then use appopriately in this file.

2020-11-23 20:13 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs
> +        private bool PublishToMsdl { get; set; }
See other notes. I would make this is a flags enum. It will make it easier to understand and more extendable.

---
In reply to: [527781272](https://github.com/dotnet/arcade/pull/6568#discussion_r527781272) [](ancestors = 527781272)

2020-11-23 20:17 UTC, mmitche requested changes
Looks generally good. I would get rid of the single boolean for publish to msdl, and fix the async-ness of the publish symbols helper.

2020-11-25 23:10 UTC, epananth reviewed
Publish to msdl and symweb : (https://user-images.githubusercontent.com/47157394/100290479-4d7e7180-2f30-11eb-8e86-09811b55eb2f.png)

Publish to msdl : https://dnceng.visualstudio.com/internal/_build/results?buildId=900290&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

2020-11-26 02:15 UTC, epananth commented
@mmitche @riarenas 

Runtime build before :
1) https://dnceng.visualstudio.com/internal/_build/results?buildId=900510&view=results - 45m 24s
2) https://dnceng.visualstudio.com/internal/_build/results?buildId=900192&view=results - 46m 4s
3) https://dnceng.visualstudio.com/internal/_build/results?buildId=899875&view=results - 27m 56s
 
Runtime build after publishing artifacts integration : https://dnceng.visualstudio.com/internal/_build/results?buildId=900568&view=results - 33m 12s

2020-11-26 02:54 UTC, mmitche commented
> @mmitche @riarenas
> 
> Runtime build before :
> 
> 1. https://dnceng.visualstudio.com/internal/_build/results?buildId=900510&view=results - 45m 24s
> 2. https://dnceng.visualstudio.com/internal/_build/results?buildId=900192&view=results - 46m 4s
> 3. https://dnceng.visualstudio.com/internal/_build/results?buildId=899875&view=results - 27m 56s
> 
> Runtime build after publishing artifacts integration : https://dnceng.visualstudio.com/internal/_build/results?buildId=900568&view=results - 33m 12s

Nice work. The third run is the most applicable since it's .NET 6. The others are .NET 5 stable builds so they also push stable symbol packages to feeds which is expensive.

2020-12-01 15:56 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/SetupTargetFeedConfigV3Tests.cs
> +                        symbolTartgetType));
Nit: typo `symbolTartgetType` -> `symbolTargetType`

2020-12-01 15:57 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs
> +                if (feedConfigsForSymbols.Any(x => (x.SymbolTargetType & SymbolTargetType.Msdl) != SymbolTargetType.None))
Awesome

2020-12-01 16:04 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs
> +                   InstallersFeed.Equals(config.InstallersFeed, StringComparison.OrdinalIgnoreCase);
Is this missing the symbol target comparison?

2020-12-01 21:12 UTC, adiaaida commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSymbolsHelper.cs
> +                        await publishOperation.PublishFiles(fileInfos);
My understanding is that if PublishOperation.PublishFiles fails, it will throw. Do we want to catch that exception?

2020-12-07 22:35 UTC, mmitche approved these changes

2020-12-08 02:56 UTC, merged