Add PushToAzureDevOpsArtifacts tests
dotnet/arcade pull request #6611
Opened 2020-11-20 22:57 UTC by jonfortescue

* Added unit tests that cover all of the manifest creation options
* Added basic mocking for file system and DI for nuget package analysis

I'm going to rename the `PushToAzureDevOpsArtifacts.cs` with tests in it to `PushToAzureDevOpsArtifactsTests.cs` but I think if i do that it will display weird on the comparison?? so i haven't done that yet

2020-11-20 23:03 UTC, jonfortescue commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    internal class MockNupkgInfo : NupkgInfo
these things can be moved into their own file but I wasn't sure where to put them.

2020-11-20 23:06 UTC, jonfortescue commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +    public interface IFileSystem
similar to above, these things probably belong in their own file but i'm unsure where to put them precisely.

2020-11-24 16:11 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
I don't think there is a reason to switch this over to NUnit, as the rest of the repo uses only Xunit. IMO things should be kept consistent.

@missymessa thoughts?

2020-11-24 16:25 UTC, mmitche commented on src/Microsoft.DotNet.VersionTools/lib/src/Automation/NupkgInfo.cs
> +                .AddSingleton<NupkgInfo>()
I don't think this is correct. This is a stateful object that encodes info about a package. Adding it as a singleton will make this class not thread safe, which may break some callsites.

2020-11-24 17:08 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +                true, NupkgInfo.GetDefaultProvider(), _taskLoggingHelper);
I think we should avoid having to pass in the nupkg info provider here

2020-11-24 17:08 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +                true, NupkgInfo.GetDefaultProvider(), _taskLoggingHelper);
Maybe default to null and then assign to the default provider in CreateModelFromItems if it's null?

2020-11-24 17:29 UTC, missymessa requested changes
Refactor how you're doing your DI.

2020-11-24 17:29 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +        public ServiceProvider NupkgInfoProvider { get; set; } = NupkgInfo.GetDefaultProvider();
This isn't the correct way to DI a thing. You should probably just new-up the NupkgInfo object like you did with the RealFileSystem object.

2020-11-24 17:29 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +    public interface IFileSystem
I put these kinds of proxy/wrapper classes in new files for better visibility so others can use them.

2020-11-24 17:29 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
I don't think it hurts to start adding new tests as NUnit since that's the test framework we decided to use going forward. It's one less thing we'll need to convert later down the road. But I do understand the desire for consistency.

2020-11-24 17:29 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
>  // Licensed to the .NET Foundation under one or more agreements.
This file should be renamed to PushToAzureDevOpsArtifactsTests.cs to distinguish that it's a test file.

2020-11-24 17:29 UTC, missymessa commented on src/Microsoft.DotNet.VersionTools/lib/src/Automation/NupkgInfo.cs
> +                .AddSingleton<NupkgInfo>()
We really need to rethink how you're doing DI in this project. The ServiceProvider should encompass the project as a whole, not just one service per ServiceProvider.

2020-11-24 17:37 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
Does arcade run these automatically in a PR if they're next to xunit tests in the same project? Does an entire project need to be converted?

2020-11-24 17:39 UTC, mmitche commented on src/Microsoft.DotNet.VersionTools/lib/src/Automation/NupkgInfo.cs
> +                .AddSingleton<NupkgInfo>()
I think we really want a singleton for an INupkgInfoProvider interface, which has a method which return NupkgInfo given a package path. NupkgInfo should just be a data class.

2020-11-24 17:40 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +    public interface IFileSystem
Should we put these in a test helper project (if one doesn't exist) so that they can be shared?

2020-11-24 18:09 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
Yeah, I'm not seeing these tests in the test results for the PR: https://dev.azure.com/dnceng/public/_build/results?buildId=894925&view=ms.vss-test-web.build-test-results-tab

Likely, the project is missing the nunit test adapter.

2020-11-24 18:13 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
I think we should leave these as xunit and convert the entire project (or maybe all of arcade) en-masse

2020-11-24 19:10 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +    public interface IFileSystem
That's what we did in the dotnet-release solution. The proxies/wrappers that were common between the Release project and Signing.Extensions were moved into a ProxyLib project so we could share them.

2020-12-02 01:48 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +            ServiceProvider nupkgInfoProvider,
Sadly, this seems to be another code smell... passing the provider (and a bunch of other things), means a level of abstraction is missing.  This probably needs to be a "ModelBuilder" object that injects what it needs.

2020-12-02 02:16 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +            ServiceProvider nupkgInfoProvider,
Yeah totally agreed. I think I stuck the equivalent in an issue comment on tests for this somewhere. Not sure whether this is the right time to go and refactor this whole bit though.

2020-12-02 02:36 UTC, mmitche commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +        public static void WriteAsXml(this BuildModel buildModel, string filePath, TaskLoggingHelper log, IFileSystem fileSystem)
IMO maybe we just remove all this altogether. The only value it really adds is a create directory call.

2020-12-02 04:39 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +        public static void WriteAsXml(this BuildModel buildModel, string filePath, TaskLoggingHelper log, IFileSystem fileSystem)
It does seem like just inlining the two method calls is probably easiest.  Having to pass 4 parameters to this method almost makes it harder to understand than the 2 calls it's hiding.

2020-12-02 04:47 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +        public ServiceProvider NupkgInfoProvider { get; set; } = NupkgInfo.GetDefaultProvider();
It really feels like we need a base class to share that can hook up the DI. Having to do it in every individual task is going to cost a lot really fast, especially if people do it differently.

2020-12-07 19:13 UTC, missymessa commented
I'm going to take over this work from Jon while he's on leave. I'll be closing this PR and put up a new one with the changes we've discussed in here.

2020-12-08 01:22 UTC, missymessa commented on src/Microsoft.DotNet.VersionTools/lib/src/Automation/NupkgInfo.cs
> +                .AddSingleton<NupkgInfo>()
Reverted the changes made to this file for now. Will try a different approach if we need to mock this object in the BuildManifestUtil object.

2020-12-08 20:30 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/BuildManifestUtilTests.cs
> +                true, NupkgInfo.GetDefaultProvider(), _taskLoggingHelper);
Redoing how we're handling this.

2020-12-21 17:01 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    internal class MockNupkgInfo : NupkgInfo
This was removed in the new PR.

2020-12-21 17:02 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifacts.cs
> +    [TestFixture]
Converted these all to Xunit in the new PR.

2020-12-21 17:03 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +        public ServiceProvider NupkgInfoProvider { get; set; } = NupkgInfo.GetDefaultProvider();
Redid the DI in the new PR.

2020-12-21 17:09 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +        public static void WriteAsXml(this BuildModel buildModel, string filePath, TaskLoggingHelper log, IFileSystem fileSystem)
Refactored this method in the new PR.

2020-12-21 17:09 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
> +            ServiceProvider nupkgInfoProvider,
Refactored how we did the DI in the new PR.

2020-12-21 17:10 UTC, missymessa commented on src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs
> +    public interface IFileSystem
Moved them to a new file in the new PR.

2020-12-21 17:11 UTC, missymessa commented
Closing this PR now that all the original feedback has been/is being addressed in the new PR: https://github.com/dotnet/arcade/pull/6672

2020-12-21 17:11 UTC, closed without merging