PackageArtifactModel and BlobArtifactModel comparison fixes
dotnet/arcade pull request #6678
Opened 2020-12-11 02:59 UTC by meganaquinn

More fixes to the Equals override so that the tests work.

2020-12-15 15:56 UTC, mmitche commented on src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BlobArtifactModel.cs
> +            return true;
This will return true if the object compared against isn't a blob artifact model.

2020-12-15 15:57 UTC, mmitche requested changes
looks like both equals comparisons are wrong (the package artifact model also returns true if 'other' is not a package artifact model

2020-12-17 04:05 UTC, meganaquinn commented on src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BlobArtifactModel.cs
> +            return true;
Thank you, fixed the scoped on that & added a false after.

2021-01-12 23:15 UTC, ChadNedzlek approved these changes

2021-01-12 23:18 UTC, mmitche approved these changes

2021-01-12 23:18 UTC, merged