Improve the master/main renaming guide
dotnet/arcade pull request #6796
Opened 2021-01-14 13:23 UTC by premun

- Add more screenshots
- Improve prerequisite instructions
- Shorten step names
- Make overview ToC clickable
- Add section about Component Governance
- Other minor clarity improvements

2021-01-14 13:43 UTC, jakubstilec approved these changes

2021-01-14 13:43 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +The **Pesonal Access Token** needs following scopes: {TODO}.
Just to make sure - is {TODO} forgotten or you want to add it later?

2021-01-14 13:45 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +The **Pesonal Access Token** needs following scopes: {TODO}.
Good catch, I'll figure that now

2021-01-14 15:01 UTC, tkapin requested changes

2021-01-14 15:01 UTC, tkapin commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Go to the [internal AzDO dnceng](https://dev.azure.com/dnceng/internal/_git) mirror of your repository and switch the default branch to `main`:
The picture is nice, but the exact instructions would further clarify this.

2021-01-14 17:58 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +The **Pesonal Access Token** needs following scopes: {TODO}.
Yup, I was gonna tackle the PS script next

2021-01-14 18:54 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +The **Pesonal Access Token** needs following scopes: {TODO}.
I will take care of this together with the PS script error handling in a separate PR. I put in my best guess.

2021-01-18 14:51 UTC, tkapin approved these changes

2021-01-18 14:53 UTC, merged