#11884: m2m darc migration script improvements
dotnet/arcade pull request #6816
Opened 2021-01-18 16:46 UTC by jakubstilec

https://github.com/dotnet/core-eng/issues/11884

2021-01-18 17:02 UTC, premun commented
@jakubstilec do you want to make the corresponding changes in the guide too so that we don't get to an inconsistent state?

2021-01-18 17:13 UTC, premun reviewed
Good job! Just one comment about the high level usage of this script.

2021-01-18 17:13 UTC, premun commented on scripts/m2m-dotnet.ps1
> +./m2m-dotnet.ps1 -Repository dotnet/m2m-renaming-test-1
It's a bit weird that the first action also already disables something.

It would be nice to have 4 actions and be very explicit about stating the action, so something like:
```
./m2m-dotnet.ps1 -Action GenerateDataFile -Repository ...
./m2m-dotnet.ps1 -Action DisableSubscriptions -Repository ...
./m2m-dotnet.ps1 -Action Migrate -DataFile [json file]
./m2m-dotnet.ps1 -Action Verify -DataFile [json file]
```

2021-01-18 17:47 UTC, tkapin requested changes

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +            }
For the sake of readability, would you consider to reduce nesting / elseifs by using continue?

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +            if ($line -match "([^\s]+)\s+\(([^\)]+)\)\s+==>\s+'([^']+)'\s+\('([^\)]+)'\)") {
Can you please add a comment with an example of what is this regexp matching? Without that, it's hard to tell if the regexp is ok ok not.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +        if ($line -match "ignoreChecks\s*=\s*\[\s*([^\]]+)\s*\]") {
Could you please add an example of the parsed line as the comment?

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +        $darcOutputLines = $output.Split([Environment]::NewLine)
Thumbs up for considering the right newline. Could you please try this from linux (WSL or docker would suffice) as there will be some people for sure who will run this on Linux? The smae for other scripts.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +            if ($output -notmatch ".*done") {
I assume this is because the darc doesn't always return non0-zero in case of an error. In this case, it should be mentioned in the comment here. Also, please log an issue for such cases - it might be a breaking change, but a reasonable well-behaved command line tool should return non-zero on error.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +                Write-Host ("   WARNING: {0}" -f $output)
Could we use Write-Error here so this goes to STDERR? The same for other error cases.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +    [object[]] ParseIgnoreChecks([string] $line) {
When we are specifying the types here, would it be difficult to have this specified as string[]? or List<string>?. Not a big deal as @().Type() is indeed Object[], but it would be more ellegant.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +    $configFile = "m2m-dotnet_{0:ddMMyyyy_HHmmss}.json" -f (get-date)
A nit - please use yyyyMMdd so it's sortable alphanumerically.

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +    ConvertTo-Json $configs -Depth 4 | Out-File -FilePath $configFile
Does the Depth 4 have any consequences here?

2021-01-18 17:47 UTC, tkapin commented on scripts/m2m-dotnet.ps1
> +        else {
Please add a line saying what command we are executing, so people can re-run this manually in case they encounter an error.

2021-01-19 08:49 UTC, premun approved these changes

2021-01-19 09:24 UTC, premun reviewed
Yeah, I think we should do the Markdown changes as part of this PR too

2021-01-19 16:25 UTC, premun approved these changes
Just some typos

2021-01-19 16:25 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +4. Disable DARC targeting subscriptions:
```suggestion
4. Disable DARC subscriptions targeting your repository:
```

2021-01-19 16:25 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +1. You can optionaly run DARC migration script in a dry run mode. This doesn't update anything, but displays DARC comands which will be executed.
```suggestion
1. You can optionally run DARC migration script in a dry run mode. This doesn't update anything, but displays DARC commands which would be executed.
```

2021-01-19 16:25 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +2. Run DARC migration script (it's safe to be executed repeatedly):
```suggestion
2. Run DARC migration script (it is safe to execute it repeatedly):
```

2021-01-20 13:46 UTC, tkapin approved these changes
The changes LGTM, thanks for addressing the comments!

2021-01-20 17:29 UTC, merged