Add iOS/tvOS signing capability to Helix SDK (XHarness)
dotnet/arcade pull request #6823
Opened 2021-01-20 10:14 UTC by premun

Adds the possibility to target real Apple devices and sign the applications before deploying them using XHarness.

The signing process requires certificates to be placed on each Helix machine in a KeyChain and a provisioning profile from netcorenativeassets that is embedded into the application.

Integration testing will be coming soon

- The `OSX.1015.Amd64.Iphone.Open` queue is already populated with signing certificates and is ready to start signing
- The `OSX.1015.Amd64.AppleTV.Open` will be ready soon (#11675)

2021-01-20 16:37 UTC, akoeplinger requested changes
Great work! I left a few questions.

2021-01-20 16:37 UTC, akoeplinger commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/Entitlements.template.plist
> +<?xml version="1.0" encoding="UTF-8"?>
I think we shouldn't check in this Entitlements.plist file and instead extract it from the mobileprovision file in ` xharness-runner.ios.sh`, like this:

```
security cms -D -i some-profile.mobileprovision > provision.plist
/usr/libexec/PlistBuddy -x -c 'Print :Entitlements' provision.plist > entitlements.plist
```

I get the same contents as what you're trying to check in here so I guess you already figured this out :)

It does contain a few unnecessary keys though, e.g. the MS Apple account provisioning profile results in this which is much shorter (and we don't even need the `keychain-access-groups`):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>SGGM6D27TK.*</string>
	<key>com.apple.developer.team-identifier</key>
	<string>UBF8T346G9</string>
	<key>get-task-allow</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>SGGM6D27TK.*</string>
	</array>
</dict>
</plist>
```

Your provisioning profile will also only work for apps with a bundle ID starting with `net.dot.` which is kinda specific to the apps we build in dotnet/runtime.

Can you try generating a provisioning profile with a complete wildcard `*` for the bundle ID (not sure if this works with your account or needs an enterprise account)?

One issue with just blindly replacing the entitlements though is that any custom entitlements key would be overwritten (we don't use any custom entitlements in dotnet/runtime right now but Xamarin might).
If we want to support that we could also extract existing entitlements from the .app with `codesign -d --entitlements :- HelloiOS.app`.

2021-01-20 17:11 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/Entitlements.template.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Thanks for the review!

Answers:
- I wrote the plist manually, I didn't know about this! 😂 Are you sure it will work for any bundle? Right now I also put in the bundle ID and the provisioning profile doesn't contain this information.
- I wasn't able to do `*`. I think it was because we are using a personal developer account tied to Ilya.
- I think we're good with the basic entitlements so far and we can deal with Xamarin later? I don't think they're anywhere close to using Arcade, only XHarness which is agnostic to this.

2021-01-20 19:04 UTC, akoeplinger commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/Entitlements.template.plist
> +<?xml version="1.0" encoding="UTF-8"?>
> Are you sure it will work for any bundle? Right now I also put in the bundle ID and the provisioning profile doesn't contain this information.

so if you have `%TeamIdentifier%.*` it'll work for any bundle ID, `%TeamIdentifier%.net.dot.*` would only work for those starting with `net.dot`

> I wasn't able to do `*`. I think it was because we are using a personal developer account tied to Ilya.

Ok yeah I think you can only do it with an enterprise account so having `%TeamIdentifier%.net.dot.*` should be fine.

> I added all of the entitlements because I read it doesn't hurt anything?

Well it could subtly change the way certain code works, e.g. the `com.apple.developer.networking.networkextension` for networking stuff and that would be terrible to debug if it only happens on Helix. I think we should start with the minimum amount of entitlements that we need :)

> I think we're good with the basic entitlements so far and we can deal with Xamarin later? I don't think they're anywhere close to using Arcade, only XHarness which is agnostic to this.

Yup, sounds good.

2021-01-21 13:41 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/Entitlements.template.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Cool, it works now without the template!

2021-01-21 15:05 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/XHarnessRunner.targets
> +                  DestinationFolder="$(ArtifactsTmpDir)"
I will just downloaded the profile right into the app folder. No need to do it in C#. If someone wants to create their own, they can just place it there before calling Arcade SDK and the download won't overwrite it.

2021-01-21 15:06 UTC, akoeplinger approved these changes

2021-01-21 16:31 UTC, premun commented
I will wait for this one before merging:
https://github.com/dotnet/xharness/issues/424

2021-01-21 19:09 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/XHarnessRunner.targets
> +                  DestinationFolder="$(ArtifactsTmpDir)"
I checked and this place will only be executed once per the whole Job creation so multiple test projects/bundles are OK and we don't expect mutliple builds at the same time

2021-01-26 16:54 UTC, premun commented
Waiting for #6856 with this

2021-01-26 21:03 UTC, premun commented
@akoeplinger together with the better uninstall, I was able to purge the iPhones in Helix from the old HelloiOS app. Originally - the installed app had more specific permissions and couldn't be removed since we didn't uninstall after a failed install.

I was able to re-deploy it using the entitlements created on-fly using the commands you have provided.
However, I had to change a lot of code since I also renamed ios to apple in the meantime.

I will try later with an app from Egor but this is ready for another review, if you would. Cheers!

2021-01-27 00:20 UTC, akoeplinger approved these changes

2021-01-27 08:51 UTC, merged