#12092: Update M2M guide using new AzDO M2MTool
dotnet/arcade pull request #6913
Opened 2021-02-05 10:08 UTC by jakubstilec

https://github.com/dotnet/core-eng/issues/12092

2021-02-05 10:20 UTC, premun requested changes

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +    - If you don't have access to update policies, you need follow steps for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool?path=%2FREADME.md&_a=preview) and fil
This step doesn't apply for the `dnceng.visualstudio.com` but only for `devdiv` so it might be confusing as we don't have VSEng for this.

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +### 8.1. For [internal](https://dev.azure.com/dnceng/internal) projects, you can update pipelines using [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool).
I would change the 8.1 and 8.2:
The difference when you can use the tool or not is whether the pipeline is based on an AzDO or GitHub repository.
There can still be internal pipelines based on GitHub, so I would just rephrase it.

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +First you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
Please include a full link to the file in the M2MTool repo

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Example of M2MTool configuration file for dotnet-xharness:
```suggestion
Example of M2MTool configuration file for `dotnet-xharness`:
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +First you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
```suggestion
First, you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Once you have configuration file, execute the M2MTool with command `pipeline` and your configuration file. Example for dotnet-xharness:
```suggestion
Once you have the configuration file, execute the M2MTool with command `pipeline` and supply the configuration file:
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +- Example for dotnet/xharness:
```suggestion
- Example for `dotnet/xharness`:
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +To update pipeline:
```suggestion
To update the pipeline:
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Tracking of main breanch is done automatically when a CG task on this branch finishes. Once main branch is tracked you should disable tracking of master branch by [M2MTool](https://devdiv.visualstudi
```suggestion
Tracking of main branch is done automatically when a CG task on this branch finishes. Once main branch is tracked you should disable tracking of master branch by [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool) with command `component-governance-untrack-branch` and configuration prepared in [step 8](#8-change-the-default-branch-for-azdo-pipelines).
```

2021-02-05 10:20 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Tracking of main breanch is done automatically when a CG task on this branch finishes. Once main branch is tracked you should disable tracking of master branch by [M2MTool](https://devdiv.visualstudi
I don't think it is done automatically. It will still be tracking master and you won't be able to switch to main. You need to wait for a finished build so that you see the main branch in the options to start tracking it.

2021-02-05 11:34 UTC, tkapin requested changes

2021-02-05 11:34 UTC, tkapin commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +    - If you don't have access to update policies, you need follow steps for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool?path=%2FREADME.md&_a=preview) and fil
Is the M2M tool accessible to everyone? We should ask people to check if they have access to it in the prerequisites. Also, we should quickly describe where this tool comes from when we first mention this.

2021-02-05 11:34 UTC, tkapin commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +> Make sure that CG task on main branch has finished before starting this step.
When you start using any abbreviation (such as CG), make sure we explain this at the first occurrence of the term (e.g., " ... Component Governance (shortened to CG in the rest of this guide) ..."

2021-02-05 15:39 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +    - If you don't have access to update policies, you need follow steps for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool?path=%2FREADME.md&_a=preview) and fil
updated and added comment about tool's origin above

2021-02-05 15:39 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +### 8.1. For [internal](https://dev.azure.com/dnceng/internal) projects, you can update pipelines using [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool).
updated

2021-02-05 15:42 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +First you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
I can't use exact link because they have it this way:
- Click on most recent build - Build Definition  https://dev.azure.com/devdiv/Engineering/_build?definitionId=13934
- Click on Published
- When you hover over the right hand side of the tool folder you will see a download down arrow - click on that
- Move folder content to wherever you want to store it.

I can probably use most recent version like https://dev.azure.com/devdiv/d9c65f94-67d0-4a2d-8fd0-4285996019c6/_apis/build/builds/4441242/artifacts?artifactName=M2MTool&api-version=6.0&%24format=zip, but then users will miss updates.

2021-02-05 15:46 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +First you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
I meant this?
https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool?path=%2FConfigFiles%2Fconfigfile.csv

2021-02-05 15:48 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +    - If you don't have access to update policies, you need ask .NET Core Engineering <dnceng@microsoft.com>. Be aware that steps described in [M2MTool documentation](https://devdiv.visualstudio.com/
```suggestion
    - If you don't have access to update policies, you need to ask [.NET Core Engineering <dnceng@microsoft.com>](mailto://dnceng@microsoft.com). Beware, the steps described in [M2MTool documentation](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool?path=%2FREADME.md&_a=preview) are applicable for devdiv.
```

2021-02-05 15:50 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +    - If you don't have access to update policies, you need ask .NET Core Engineering <dnceng@microsoft.com>. Be aware that steps described in [M2MTool documentation](https://devdiv.visualstudio.com/
I don't like much this sentence "Beware, the steps described in are applicable for devdiv."

What is the person reading this supposed to do with this information? Only grow uneasy that things might break?

Also this sentence should go somewhere else, there's no mention of M2M tool in this list item

2021-02-05 15:51 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Example for dotnet/xharness (just update parameter URL with URL of your repository):
```suggestion
Example for `dotnet/xharness`:
```

2021-02-05 15:52 UTC, premun requested changes
Not sure the mailto link will work but I cannot see the preview on this page

2021-02-05 15:55 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +### 1. Pipelines based on AzDO repository can be updated by M2MTool
You have `1.` here and nothing below

2021-02-05 15:55 UTC, premun commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +- Do this for all pipelines that are based off a YAML in the GitHub repo that you are working with
```suggestion
- Do this for all pipelines that are based off a YAML in the GitHub repo that you are working with (these are usually in the public AzDO project)
```

2021-02-05 16:04 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +First you need to prepare a configuration file for [M2MTool](https://devdiv.visualstudio.com/DefaultCollection/Engineering/_git/M2MTool). Example can be found in \M2MTool\ConfigFiles\configfile.csv.
oh right, I misunderstood, I thought that you spoke about how to download the tool, it's updated now

2021-02-05 21:01 UTC, jakubstilec commented on Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
> +Tracking of main breanch is done automatically when a CG task on this branch finishes. Once main branch is tracked you should disable tracking of master branch by [M2MTool](https://devdiv.visualstudi
You are right, it looks they has it wrong in M2MTool or it works differently in devdiv. I reverted it back as use of M2MTool doesn't have much sense in this case.

2021-02-08 16:59 UTC, premun approved these changes

2021-02-08 19:26 UTC, tkapin approved these changes

2021-02-09 12:49 UTC, merged