Add support for additional DotNetRuntime
dotnet/arcade pull request #7158
Opened 2021-03-26 19:08 UTC by HaoK

Enables

```
    <IncludeDotNetRuntime>true</IncludeDotNetRuntime>
    <DotNetCliVersion>6.0.100-preview.2.21155.3</DotNetCliVersion>
    <DotNetRuntimeVersion>6.0.0-preview.4.21175.1</DotNetRuntimeVersion>
```

Which will install both the sdk and the runtime into the same directory

2021-03-26 19:10 UTC, HaoK commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets
> +      <HelixCorrelationPayload Include="dotnet-runtime" Condition="$(IncludeDotNetRuntime) == 'true'">
Not sure what `Include=dotnet-runtime` means here, it still ends up installing the runtime bits to the same dotnet-cli which is what I want so...

2021-03-26 19:11 UTC, HaoK commented
@MattGal starting point which seems to do the right thing, I end up with both versions in the payload/correlation directory as I want:


https://helixre8s23ayyeko0k025g8.blob.core.windows.net/aspnetcore-local-66c19a1b48864d5b89/Microsoft.DotNet.Helix.Sdk.Tests.dll/console.ee215eb1.log?sv=2019-07-07&se=2021-04-15T16%3A29%3A54Z&sr=c&sp=rl&sig=QkFKo2BAQxak5acUV%2B%2FqcOy3ovlZMf1pkPUhzQ5EUGk%3D
```

 Directory of C:\h\w\A34108FE\p\dotnet-cli\host\fxr

03/26/2021  04:34 PM    <DIR>          .
03/26/2021  04:34 PM    <DIR>          ..
03/26/2021  04:34 PM    <DIR>          6.0.0-preview.2.21154.6
03/26/2021  04:34 PM    <DIR>          6.0.0-preview.4.21175.1
               0 File(s)              0 bytes

 Directory of C:\h\w\A34108FE\p\dotnet-cli\shared\Microsoft.NETCore.App

03/26/2021  04:34 PM    <DIR>          .
03/26/2021  04:34 PM    <DIR>          ..
03/26/2021  04:34 PM    <DIR>          6.0.0-preview.2.21154.6
03/26/2021  04:34 PM    <DIR>          6.0.0-preview.4.21175.1
```

2021-03-30 16:05 UTC, MattGal requested changes
Awesome this seems so straightforward, but I think it should be more general-purpose than just explicitly allowing one additional runtime.

2021-03-30 16:05 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props
> +    <IncludeDotNetRuntime Condition=" '$(IncludeDotNetRuntime)' != 'true' ">false</IncludeDotNetRuntime>
This seems like something that could be a list of semicolon-delineated runtimes and checked whether empty or not.  It seems locked in to install a single runtime, which may eventually need to be extended.  

Perhaps a collection of ITaskItems named "AdditionalDotNetRuntime"?

2021-03-30 16:10 UTC, HaoK commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props
> +    <IncludeDotNetRuntime Condition=" '$(IncludeDotNetRuntime)' != 'true' ">false</IncludeDotNetRuntime>
So instead of needing the IncludeDotNetRuntime, we can just use AdditionalDotNetRuntime != "", that's much nicer as well

2021-03-30 16:16 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props
> +    <IncludeDotNetRuntime Condition=" '$(IncludeDotNetRuntime)' != 'true' ">false</IncludeDotNetRuntime>
> That seems reasonable to me, is there an easy way to do looping in msbuild to add a FindDotNetCliPackage item for each runtime? Or would it be best to refactor the task to take a list and return a list of urls?

Yes, you can use the MSBuild Item batching syntax (which, while weird and sometimes tricky, once you get it right is fairly straightforward): https://docs.microsoft.com/en-us/visualstudio/msbuild/item-metadata-in-task-batching?view=vs-2019#:~:text=%20Item%20metadata%20in%20task%20batching%20%201,item%20metadata%20that%20is%20assigned%20to...%20More%20

2021-03-30 17:50 UTC, HaoK commented
Could use some msbuild help here with batching, I'm trying to get the outputs of the task to go into an item list and then add it to the correlation payload in a batch, its not happy with my mangling of msbuild

```
    <ItemGroup>
      <_additionaRuntimeVersions Include="@(AdditionalDotNetRuntimes)" />
    </ItemGroup>
    <FindDotNetCliPackage Condition="'%(_additionaRuntimeVersions.Identity)' != ''" Version="$(_additionaRuntimeVersions.Identity)" Runtime="$(DotNetCliRuntime)" PackageType="runtime" Channel="$(DotNetCliChannel)">
      <Output TaskParameter="PackageUri" ItemName="DotNetRuntimePackageUri"/>
    </FindDotNetCliPackage>
    <ItemGroup>
      <HelixCorrelationPayload Include="dotnet-cli">
        <Uri>$(DotNetCliPackageUri)</Uri>
        <Destination>$(DotNetCliDestination)</Destination>
      </HelixCorrelationPayload>
      <HelixCorrelationPayload Include="dotnet-runtime" Condition="%(DotNetRuntimePackageUri) != ''">
        <Uri>%(DotNetRuntimePackageUri.Identity)</Uri>
        <Destination>$(DotNetCliDestination)</Destination>
      </HelixCorrelationPayload>
    </ItemGroup>
```

C:\Github\arcade\src\Microsoft.DotNet.Helix\Sdk\tools\dotnet-cli\DotNetCli.targets(15,5): error MSB4096: The item "C:\Github\arcade\tests\archivepayload.zip" in item list "HelixCorrelationPayload" does not define a value for metadata "DotNetRuntimePackageUri".  In order to use this metadata, either qualify it by specifying %(HelixCorrelationPayload.DotNetRuntimePackageUri), or ensure that all items in this list define a value for this metadata. [C:\Github\arcade\tests\UnitTests.proj]
The results in:

2021-03-30 18:16 UTC, MattGal commented
@HaoK taking a peek.  (also: "_additiona -> _additional")

2021-03-30 18:20 UTC, HaoK commented
I think the issue is that I'm not properly aggregating the output DotNetRuntimePackageUris, for the correlation payloads to batch.  In the binlog it looks like each of those is getting stored into its own Item as opposed to building up a list of packageuris like I want

2021-03-30 18:22 UTC, HaoK commented
Updated msbuild stuff

```
    <ItemGroup>
      <_additionalRuntimeVersions Include="$(AdditionalDotNetRuntimes)" />
    </ItemGroup>
    <FindDotNetCliPackage Condition="'%(_additionalRuntimeVersions.Identity)' != ''" Version="%(_additionalRuntimeVersions.Identity)" Runtime="$(DotNetCliRuntime)" PackageType="runtime" Channel="$(DotNetCliChannel)">
      <Output TaskParameter="PackageUri" ItemName="DotNetRuntimePackageUri"/>
    </FindDotNetCliPackage>
    <ItemGroup>
      <HelixCorrelationPayload Include="dotnet-cli">
        <Uri>$(DotNetCliPackageUri)</Uri>
        <Destination>$(DotNetCliDestination)</Destination>
      </HelixCorrelationPayload>
      <HelixCorrelationPayload Include="dotnet-runtime" Condition="%(DotNetRuntimePackageUri) != ''">
        <Uri>%(DotNetRuntimePackageUri.Identity)</Uri>
        <Destination>$(DotNetCliDestination)</Destination>
      </HelixCorrelationPayload>
    </ItemGroup>
```

![image](https://user-images.githubusercontent.com/6537861/113037397-2f2cba80-914a-11eb-9d69-f425c4c8749a.png)

2021-03-30 18:39 UTC, HaoK commented
Cool that makes sense, I'll try that, but assuming I don't refactor the FindDotNetCliPackage, how do I call it repeatedly and combine the Output from each call into a single list?  That's the msbuild piece I'm stuck on.

each call gives me a single uri, which i can attach to a property name or item, but how do I tell it to append to something?

2021-03-30 18:50 UTC, alexperovich commented
You don't need to append it to something, just add additional correlation payloads.

2021-03-30 21:25 UTC, HaoK commented
One question @MattGal what is the "SomeRuntime1" a friendly moniker?  Why wouldn't that just be the version?

Maybe?
```
<AdditionalDotNetRuntime Include="Version">
        <Runtime>someruntime</Runtime>
        <PackageType>somepackagetype</PackageType>
        <Channel>somechannel</Channel>
</AdditionalDotNetRuntime>
```

2021-03-30 21:30 UTC, HaoK commented
Also does it really make sense to mix runtimes like this?  When would you want to have an arm64 runtime mixed with an osx for example?  I would assume the rid should be shared.  But i'll defer to you guys to determine if that makes sense

2021-03-30 22:11 UTC, MattGal commented
> One question @MattGal what is the "SomeRuntime1" a friendly moniker? Why wouldn't that just be the version?
> 
> Maybe?
> 
> ```
> <AdditionalDotNetRuntime Include="Version">
>         <Runtime>someruntime</Runtime>
>         <PackageType>somepackagetype</PackageType>
>         <Channel>somechannel</Channel>
> </AdditionalDotNetRuntime>
> ```

Sure, you can use any string you want as an ITaskItem's identity, but for anything beyond the first string you use metadata as show.  Identity is just a string and should strive to but doesn't have to be unique.

2021-03-30 22:46 UTC, HaoK commented
I'm still struggling with how to add payloads given the task structure, the message thing works since its just printing, how do I add a payload though...  Here's what I have where I tried to do the actual payload generation instead of the message which works fine, I am unsure how to batch against the list of DotNetCliPackageUri.

```
  <Target Name="AddAdditionalRuntimes" 
          Condition="@(AdditionalDotNetPackage->Count()) != 0"
          AfterTargets="Build" 
          Inputs="@(AdditionalDotNetPackage)"
          Outputs="SomeUris">

      <Message Text = "FindDotNetCliPackage '%(AdditionalDotNetPackage.Identity)' '$(DotNetCliRuntime)' '%(AdditionalDotNetPackage.PackageType)' '%(AdditionalDotNetPackage.Channel)' "/>
  <!-- you'd actually invoke the Target here... -->
    <FindDotNetCliPackage Version="$%(AdditionalDotNetPackage.Identity)" Runtime="$(DotNetCliRuntime)" PackageType="%(AdditionalDotNetPackage.PackageType)" Channel="$(DotNetCliChannel)">
      <Output TaskParameter="PackageUri" PropertyName="DotNetCliPackageUri"/>
    </FindDotNetCliPackage>
    <ItemGroup>
      <HelixCorrelationPayload Include="dotnet-additional">
        <Uri>$(DotNetCliPackageUri)</Uri>
        <Destination>$(DotNetCliDestination)</Destination>
      </HelixCorrelationPayload>
    </ItemGroup>
  </Target>
```

My instinct is to just write a new task that takes a list of AddAdditionalRuntimes and does the right thing in C# to avoid this msbuild stuff, but I'm guessing there's an easy way to do this in msbuild?

2021-03-30 23:16 UTC, HaoK commented
This binlog demonstrates the current issue I'm seeing, each invocation of the FindDotNetCli task overwrites the last output url, and it seems to be using the original package url anyways, instead of adding 3 payloads with different package uris

![image](https://user-images.githubusercontent.com/6537861/113068337-fe14b000-9172-11eb-85a2-7597619bc06a.png)

2021-03-31 00:09 UTC, alexperovich commented
@HaoK that is happening because you aren't batching the target, you are using task batching because you put "%(AdditionalDotNetPackage.Identity)" in the FindDotNetCliPackage task invocation. You need to stick that in the Outputs of the target too for it to batch at the target level.

What you have right now is equivalent to this pseudo code:
```
foreach package in @(AdditionalDotNetPackage)
  <Message/>
foreach package in @(AdditionalDotNetPackage)
  <FindDotNetCliPackage/>
<ItemGroup>
```

If you stick the %(AdditionalDotNetPackage.Identity) into the Outputs of the target, then msbuild will switch to target batching and run the entire target once for each unique value of %(AdditionalDotNetPackage.Identity)

2021-03-31 00:11 UTC, alexperovich commented
Also, the target shouldn't have any Inputs, otherwise msbuild will try to do "up-to-date" checks and possibly not run parts of the target if files of the right names exist.

2021-03-31 18:19 UTC, HaoK commented
Thanks @alexperovich that output seems to have done the trick, I tried the following additional payloads:

```
    <AdditionalDotNetPackage Include="6.0.0-preview.4.21175.1">
      <PackageType>runtime</PackageType>
      <Channel>Current</Channel>
    </AdditionalDotNetPackage>
    <AdditionalDotNetPackage Include="6.0.0-preview.4.21178.6">
      <PackageType>runtime</PackageType>
      <Channel>Current</Channel>
    </AdditionalDotNetPackage>
    <AdditionalDotNetPackage Include="6.0.0-preview.3.21168.5">
      <PackageType>aspnetcore-runtime</PackageType>
      <Channel>Current</Channel>
    </AdditionalDotNetPackage>
```

2021-03-31 18:57 UTC, HaoK commented
Test run looks good to me, 

Input: 

```
    <AdditionalDotNetPackage Include="6.0.0-preview.4.21175.1" />
    <AdditionalDotNetPackage Include="6.0.0-preview.4.21178.6">
      <PackageType>runtime</PackageType>
      <Channel>Current</Channel>
    </AdditionalDotNetPackage>
    <AdditionalDotNetPackage Include="6.0.0-preview.3.21168.5">
      <PackageType>aspnetcore-runtime</PackageType>
    </AdditionalDotNetPackage>
```

Resulted in the expected versions on disk in the sdk.tests.dll:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/aspnetcore-local-3cb65732833747d0af/Microsoft.DotNet.Helix.Sdk.Tests.dll/console.93c9f799.log?sv=2019-07-07&se=2021-04-20T18%3A23%3A48Z&sr=c&sp=rl&sig=As74YPyvDjSe2XfnUcZOKYYiVaE5OvJM%2BiAMF%2BTkg1U%3D

2021-03-31 19:11 UTC, MattGal commented
Can you add some content to https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/Readme.md#all-possible-options about how this works / some examples?

2021-03-31 19:16 UTC, HaoK commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets
> +    <Message Text = "FindDotNetCliPackage '%(AdditionalDotNetPackage.Identity)' '$(DotNetCliRuntime)' '$(_package)' '$(_channel)' "/>
Up to you, I found it nice for debugging, I can remove it or update the text, what do you prefer?

2021-03-31 19:25 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets
> +    <Message Text = "FindDotNetCliPackage '%(AdditionalDotNetPackage.Identity)' '$(DotNetCliRuntime)' '$(_package)' '$(_channel)' "/>
If it's up to me I definitely favor logging it with normal verbosity, something like
```
<Message Text = "Adding correlation payload for additional .NET Core package: Version: '%(AdditionalDotNetPackage.Identity)'  Runtime: '$(DotNetCliRuntime)' Type: '$(_package)' Channel: '$(_channel)' "/>
```

2021-03-31 19:31 UTC, HaoK commented on src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets
> +    <Message Text = "FindDotNetCliPackage '%(AdditionalDotNetPackage.Identity)' '$(DotNetCliRuntime)' '$(_package)' '$(_channel)' "/>
Sounds good, updated

2021-03-31 19:32 UTC, MattGal approved these changes
LGTM, please do update the readme before merging.

2021-03-31 19:41 UTC, monstro805 approved these changes

2021-03-31 20:15 UTC, MattGal approved these changes

2021-03-31 20:15 UTC, MattGal commented on src/Microsoft.DotNet.Helix/Sdk/Readme.md
> +  <!--
Looks good, some suggestions:


- Including additional dotnet correlation payloads -> could be more verbose, e.g. "Optional additional dotnet runtimes or SDKs for correlation payloads"
- Where your examples say "the specified" it couldn't hurt to have (version that's actually in the example) for clarity.
- I would put parenthesis around defaults (e.g. "PackageType (defaults to runtime)")

2021-03-31 22:56 UTC, merged

2021-03-31 22:57 UTC, HaoK commented
What's the best way for me to track when this will be available for us in dotnet/aspnetcore?

2021-03-31 23:18 UTC, MattGal commented
@riarenas can correct what I get wrong here but I'll take a stab:

- [ ] Wait for [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=1066687&view=results) to complete the "publish using darc" phase successfully
- [ ] Once it has, you can go into your repo and do a `darc update-dependencies` with the build id listed in the publish phase (while CD'ed inside your repo)
- [ ] Make a PR with what these changes back to your repo(s)

This will eventually flow via regular Arcade dependency flow automation, as well.

2021-03-31 23:37 UTC, dougbu commented
@HaoK another way to do this would be a bit more inline with the regular promotion process
1. Watch the https://dev.azure.com/dnceng/internal/_build/results?buildId=1066687 and wait for it to complete (it's done now 😀)
2. Watch https://dev.azure.com/dnceng/internal/_build?definitionId=282 for a new build w/ a title like "Update dependencies from https://github.com/dotnet/arcade build 20210331.5" (or later)
3. Watch that build 'til it completes
4. Double-check https://maestro-prod.westus2.cloudapp.azure.com/2/https:%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_git%2Fdotnet-arcade/latest/graph to confirm Maestro++ is aware of the new build (`BAR ID - 84605` in this case)
5. `darc update-dependencies --channel '.NET Eng - Latest' --source-repo arcade` while in dotnet/aspnetcore _or_ `darc trigger-subscriptions --source-repo arcade --target-repo aspnetcore$ --regex --target-branch main`
    - The first command is useful to include in a personal PR, the second option creates a dependency PR (necessary because our subscription is weekly) and allows you to react separately. 

Main difference between that list and @MattGal's suggestion is it includes the promotion checks. Downside is it'll take longer.

2021-03-31 23:40 UTC, HaoK commented
@dougbu since I'm OOF next week, will this likely have flowed into our repo in 2 weeks?

2021-03-31 23:45 UTC, dougbu commented
This fix **absolutely** should flow into dotnet/aspnetcore by next Tuesday at the latest. We took an update in dotnet/aspnetcore#31349 yesterday and that's the only reason I am not confident the PR won't be created "naturally" on Sunday.

2021-03-31 23:47 UTC, MattGal commented
Either way you do it is fine by me, but I was thinking about how once the package version is up on a feed, you can start experimenting with fitting its usage into the ASP.NET's Helix tests in a private branch faster, then land it once it promotes naturally or otherwise.

2021-03-31 23:53 UTC, HaoK commented
Yeah I probably won't have time to play with it before I get back, hopefully it will be trivial (set the new versions in our helix proj), remove our invocations of dotnet-install from our helix bootstrappers and just trust that the correlation payload paths have the right bits...  It 'should' just work, since we are basically doing the same thing today (installing sdk/runtime into a workitem directory)

2021-03-31 23:55 UTC, MattGal commented
If it gets sent to Helix and then breaks, you can pretty much always expect me to help investigate regardless of what my boss wants.  I will be OOF next week though.

2021-03-31 23:56 UTC, dougbu commented
Whoa, how will the rest of us deal❕ Thinking about taking a few Wellness days to avoid the fallout.

2021-03-31 23:58 UTC, HaoK commented
My changes are opt in, if someone else is brave enough to try it first, they are far braver than I would be :)

2021-04-01 00:40 UTC, dougbu commented
/fyi we're at step 3 in [my list](https://github.com/dotnet/arcade/pull/7158#issuecomment-811533082). Promotion build is https://dev.azure.com/dnceng/internal/_build/results?buildId=1066875

2021-04-01 03:53 UTC, dougbu commented
/fyi I manually triggered dotnet/aspnetcore#31427 That brings in the Arcade build 20210331.6 and so contains your fix @HaoK