Add temporary solution for OneLocBuild to GitHub
dotnet/arcade pull request #7298
Opened 2021-04-27 17:50 UTC by jonfortescue

This is a draft PR so I can get feedback early while I'm still finishing up and writing tests and such. I'm using this locally right now to make loc PRs to the various repos that need them for the upcoming release, but I want to make sure it's at least a little sturdy before we flow it.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

2021-04-27 19:14 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +    public class PostOneLocBuildToGitHubTests
I would recommend adding another test to validate that your dependencies were configured correctly. There's examples of them in the tests for the other MSBuild tasks that use the abstract class.

2021-04-27 19:18 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +            _fileSystemMock = new Mock<IFileSystem>();
I would recommend something similar to the SetUp pattern I do in other tests, where the SetUp method returns object that is the system under test, and takes in optional mock objects in case you have tests that require different mocks than the default. Also, it will remove your mocks from the global scope of the class.

2021-04-27 19:18 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +        //public async Task MakesPr()
I assume you do something about this? :)

2021-04-27 19:23 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +        private IServiceCollection CreateMockServiceCollection()
You're not using this.

2021-04-27 19:28 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +            _fileSystemMock = new Mock<IFileSystem>();
Here's some examples of tests that use the MSBuild task abstract class (doesn't use a SetUp method) but you can see how they use the ConfigureServices method for DIing: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PushToAzureDevOpsArtifactsTests.cs

2021-04-27 19:28 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +// Licensed to the .NET Foundation under one or more agreements.
Don't all MSBuild Tasks require an associated proj file?

2021-04-27 19:29 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        private const string _gitFileBlobMode = "100644";
Could you add a comment about where this magic number comes from?

2021-04-27 19:32 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            collection.TryAddSingleton<IGitHubClient>(new GitHubClient(new ProductHeaderValue("OneLocBuild")));
This isn't proper DI :(  You shouldn't "new" up things in your collection for DI.

2021-04-27 19:39 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public async Task<PullRequest> FindExistingOneLocPr(IGitHubClient gitHubClient)
Is this method every going to be called by anything outside of this class? If not, let's make this private.

2021-04-27 19:41 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public static string PrPrefix = "Add localization from OneLocBuild ";
Do these need to be public?

2021-04-27 19:46 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            if (prs.Count() > 0)
I think using .Length here is preferred over .Count()

2021-04-27 19:47 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            if (prs.Count() > 0)
Actually. you could eliminate this whole conditional with using `.FirstOrDefault()`. 

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault?view=net-5.0

2021-04-27 19:50 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +        //public async Task MakesPr()
eventually :)

2021-04-27 19:50 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk.Tests/PostOneLocBuildToGitHubTests.cs
> +        private IServiceCollection CreateMockServiceCollection()
not yet but i will, don't worry

2021-04-27 19:51 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +// Licensed to the .NET Foundation under one or more agreements.
yes, i will add one eventually

2021-04-27 19:51 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        private const string _gitFileBlobMode = "100644";
yes i can

2021-04-27 19:52 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public async Task<PullRequest> FindExistingOneLocPr(IGitHubClient gitHubClient)
it's currently called by the Tests project

2021-04-27 19:52 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public static string PrPrefix = "Add localization from OneLocBuild ";
Probably not? I can make them private

2021-04-27 20:00 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            gitHubClient.Connection.Credentials = new Credentials("dnbot", GitHubPat);
I feel like using a GitHub Client Factory might be the better process here, or setting up the DI of the GitHubClient that will inject the Credentials into it, so you're not having to handle configuration in the method.

2021-04-27 20:01 UTC, ChadNedzlek requested changes
Is this... a build task that opens GitHub PR's? That's a really weird design...

2021-04-27 20:01 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            if (prs.Count() > 0)
This whole block is literally "FirstOrDefault", but with the fun side effect of double evaluating the enumerable. :-)

2021-04-27 20:01 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            var prs = (await gitHubClient.PullRequest.GetAllForRepository(GitHubTargetOrg, GitHubRepo, filter))
Why not add a label filter?  Getting ALL the PR's can be a pretty big list, and might require multiple HTTP roundtrips (there are hundreds of open PRs).

2021-04-27 20:07 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public async Task<PullRequest> FindExistingOneLocPr(IGitHubClient gitHubClient)
Also, since `gitHubClient` is an injected dependency, you can assign it to a class-wide variable, and then you won't have to pass it into this method.

2021-04-27 20:10 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public async Task<PullRequest> FindExistingOneLocPr(IGitHubClient gitHubClient)
We can still make it private, and do tests to verify the logic. Since the method is returning a value, then you will know what to expect for how the parent method will process the value and then write tests based on that.

2021-04-27 20:12 UTC, missymessa commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public bool ExecuteTask(IGitHubClient gitHubClient, IFileSystem fileSystem, IHelpers helpers)
This is the method that is required per the abstract class, but it's wrapped around an async method.

2021-04-27 20:13 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            var prs = (await gitHubClient.PullRequest.GetAllForRepository(GitHubTargetOrg, GitHubRepo, filter))
it does paginate which actually creates a different problem bc this depends on it being in the first fifteen PRs or whatever... the issue with a label filter is that we'd have to create a label for all 19+ repos that are going to use this. if there's a way to search by title that would be ideal but I didn't see that in octokit...

2021-04-27 20:17 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            if (prs.Count() > 0)
ah yes :) that is true :)

2021-04-27 20:17 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        public async Task<PullRequest> FindExistingOneLocPr(IGitHubClient gitHubClient)
good idea

2021-04-27 20:17 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        private const string _gitFileBlobMode = "100644";
sounds reasonable to me!

2021-04-27 20:17 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            collection.TryAddSingleton<IGitHubClient>(new GitHubClient(new ProductHeaderValue("OneLocBuild")));
thank you!!

2021-04-27 20:17 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            string[] filesToPr = fileSystem.ReadFromFile(pathToPrDiffFile).Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
Ahh that's probably smart, yes

2021-04-27 20:21 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +            var prs = (await gitHubClient.PullRequest.GetAllForRepository(GitHubTargetOrg, GitHubRepo, filter))
You might be able to use client.Search.Issues? (Since PR's and Issues are the same thing).

Also, presumably, the PAT can MAKE the label.

2021-05-04 18:40 UTC, jonfortescue commented on src/Microsoft.DotNet.Arcade.Sdk/src/PostOneLocBuildToGitHub.cs
> +        private const string _gitFileBlobMode = "100644";
turns out octokit has a built in thing for this

2021-05-17 17:06 UTC, closed without merging