Migrate GenerateTemplateFromFile to Microsoft.DotNet.Build.Tasks.Templating
dotnet/arcade pull request #7403
Opened 2021-05-18 18:32 UTC by JunTaoLuo

Fixes https://github.com/dotnet/arcade/issues/204. This will need to be backported to 3.1 and 5.0 after approval

2021-05-18 19:11 UTC, dougbu approved these changes
My comments are all nits but I would like to hear from @alexperovich and / or @markwilkie before we merge.

2021-05-18 19:11 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +                                message: $"No property value is available for '{varName}'");
nit: A different warning for the empty variable name case e.g. `${}` may be more understandable.

2021-05-18 19:11 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +}
@alexperovich @markwilkie do most files in this repo end with a newline❔

2021-05-18 19:11 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/MSBuildListSplitter.cs
> +                }
These `continue` cases are syntax errors and should probably be warned about. Maybe not now&hellip;

2021-05-18 19:17 UTC, dougbu commented
/fyi @rainersigwald (re dotnet/msbuild#4018) @ericstj (re #204) @ilyas1974 and @ViktorHofer (re tail end of #135)

2021-05-18 19:24 UTC, dougbu commented
@rainersigwald this migrationf from aspnet/BuildTools reminds me of a rather unrelated question: Why is the `<JoinItems>` task in the .NET SDK and not together with the more general `msbuild` tasks and targets❔ I'm reminded of the discrepancy when I reach for `Remove` with `MatchOnMetadata` (a poorly-documented and limited option) or difficult-to-grok task batching alternatives in projects that don't use that SDK.

2021-05-18 19:27 UTC, rainersigwald approved these changes

2021-05-18 19:27 UTC, rainersigwald commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            return true;
nit: this pattern helps guard against errors-but-task-succeeded cases:
```suggestion
            return !Log.HasLoggedErrors;
```

2021-05-18 19:30 UTC, rainersigwald commented
> Why is the `<JoinItems>` task in the .NET SDK and not together with the more general `msbuild` tasks and targets❔

It was needed there first. I am not opposed in principle to "promoting" it.

2021-05-18 20:13 UTC, ViktorHofer commented
Great to see progress on this 👍 

Does one task justify an additional assembly and with it package? Why not add it to the Arcade.Sdk project instead?

2021-05-18 20:15 UTC, ViktorHofer commented on src/Microsoft.DotNet.Build.Tasks.Templating/build/Microsoft.DotNet.Build.Tasks.Templating.props
> +
```suggestion
<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
```

2021-05-18 20:21 UTC, ViktorHofer commented
That's the implementation that we use in dotnet/runtime: https://github.com/dotnet/runtime/blob/main/src/tasks/installer.tasks/GenerateRunScript.cs which looks simpler. Wouldn't that suffice?

2021-05-18 20:29 UTC, JunTaoLuo commented
@ViktorHofer it was mentioned that this task shouldn't be included in the SDK: https://github.com/dotnet/arcade/issues/204#issuecomment-834790040 so we decided to create a task package instead. As for comparison between GenerateRunScript.cs, this task is more general and can be used to substitute a user specified set of properties instead of just the specific `[[RunCommands]]` and `[[EchoRunCommands]]`

2021-05-18 20:32 UTC, monstro805 approved these changes

2021-05-18 20:47 UTC, ViktorHofer commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var outputPath = Path.GetFullPath(OutputPath.Replace('\\', '/'));
Why is the replace required?

2021-05-18 20:51 UTC, ViktorHofer approved these changes
LGTM. What about tests? :)

2021-05-18 20:53 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var outputPath = Path.GetFullPath(OutputPath.Replace('\\', '/'));
Not sure? I wasn't the one who wrote the original implementation 😮. I suspect this was needed to work on *nix?

2021-05-18 20:54 UTC, JunTaoLuo commented
There were no tests in the original implementation, maybe we should not block on that in this PR and file followup to add tests?

2021-05-18 21:05 UTC, ViktorHofer commented
> There were no tests in the original implementation, maybe we should not block on that in this PR and file followup to add tests?

Sure, works for me.

2021-05-18 21:37 UTC, alexperovich commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
This should be importing eng/BuildTask.targets to align with the other task projects in the repo.

2021-05-18 21:44 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +                                message: $"No property value is available for '{varName}'");
I think `''` is not great but sufficient. If no one has complained over the years, I doubt anyone will start.

2021-05-18 21:46 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +                        : template[i + 1];
I'm not that bothered by `ch` abbreviations. Hard to misinterpret.

2021-05-18 21:48 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Ah, I totally missed that since it was allllll the way at the bottom of the file.

2021-05-18 22:02 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
The style guidelines here: https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md, require specifying types rather than using var (except in some specific circumstances, which these are not)

2021-05-18 22:15 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
@ChadNedzlek the [style guidelines for dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#usage-of-the-var-keyword) say to use `var` as much as possible. Does Arcade have its own guidelines or point to the dotnet/runtime ones somewhere?

2021-05-18 23:26 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
https://github.com/dotnet/arcade/readme.md
* points to https://github.com/dotnet/arcade/blob/main/Documentation/Policy/ArcadeContributorGuidance.md
* points to https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md
* points to https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

2021-05-18 23:27 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
I also had no clue what any of these var values were, so I was totally lost during the review.

2021-05-19 08:14 UTC, lukas-lansky commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
@ChadNedzlek, if we adhere to runtime's style guide, maybe we should take in runtime's `.editorconfig` then? It would make things easier for people who don't live in the repo if the IDE informed about the current rules.

In particular, lines [51-55](https://github.com/dotnet/runtime/blob/6ab1cee00ba41b308009c88864aba46b0f61f061/.editorconfig#L51-L55) are relevant for this discussion.

2021-05-19 08:37 UTC, ViktorHofer commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
We usually have both a .NETCoreApp and a .NETFramework tfm for build tasks so that this works fine on Desktop msbuild as well. There are known problems with .NETStandard build tasks (which I can't find right now...). We follow that approach for every other build task in this repo, i.e. https://github.com/dotnet/arcade/blob/f53feab62c4b34b3b3e7e57b2dd98f0140da6be7/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L4

Note that you don't need L5 as sourcebuild is able to build .NET Framework assemblies now as well.

2021-05-19 14:37 UTC, markwilkie commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
> maybe we should take in runtime's .editorconfig then?

@lukas-lansky - I'm all for this if you wan to submit a PR.

2021-05-19 14:56 UTC, lukas-lansky commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            var values = MSBuildListSplitter.GetNamedProperties(Properties);
👍, here it is: https://github.com/dotnet/arcade/pull/7410

2021-05-19 18:27 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
I see, though I have another question.

When I was deciding between whether to keep the original TFM or use the arcade convention, I saw that there are hardcoded paths: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets#L46. How does this work in arcade builds where the TFM is different, i.e. https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/eng/TargetFrameworkDefaults.props#L9?

2021-05-19 18:39 UTC, ViktorHofer commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Wow great find. That's actually a break and will prevent sourcebuild from using these packages. We need to fix that.

2021-05-19 18:43 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Nice. I meant to file an issue but ended up getting sidetracked and forgot until I was reminded here 😄

2021-05-19 19:14 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Filed: https://github.com/dotnet/arcade/issues/7413.

2021-05-29 07:47 UTC, JunTaoLuo commented
Hey all, I've addressed the style guidelines and other feedback.

2021-05-29 13:16 UTC, ViktorHofer approved these changes

2021-05-29 18:44 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/MSBuildListSplitter.cs
> +                    continue;
Maybe not now but this case deserves a warning too

2021-05-29 18:44 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/Microsoft.DotNet.Build.Tasks.Templating.csproj
> +<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
/fyi @markwilkie four projects in this repo use a different header:
``` xml
<!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. -->
```

They should probably be made consistent.

2021-06-03 21:41 UTC, dougbu commented
This PR has been reviewed though I don't see any :shipit:s from Core-Eng folks. Unless I hear different before later tonight, I'll merge. Please sing out w/ objections if you have any.

2021-06-03 22:04 UTC, markwilkie commented
While I have no context on the code itself, the intent is good with me.  Assuming the right testing has happened, I'm find w/ merging.

2021-06-03 22:10 UTC, ChadNedzlek requested changes

2021-06-03 22:10 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +        [Output]
This "Output" is not correct, it's an input parameter. It's not returned by this task.

2021-06-03 22:22 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            StringBuilder sb = new();
I... hate to suggest this, because regex is generally evil, but this is a _lot_ of code for what I think could be a one-linee, something like
`Regex.Replace(template, @"\{\{(\w)+\}\}", m => values[m.Groups[1].Value])`

This code is probably more efficient, but it's really hard to read and understand.  It's long enough that it should have significant testing.

2021-06-04 00:13 UTC, dougbu commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            StringBuilder sb = new();
> it should have significant testing

@ViktorHofer mentioned tests earlier in this PR. @JunTaoLuo suggested covering that as a follow-up to this migration. Is that sufficient i.e. will this PR be ready to merge after @JunTaoLuo addresses your other https://github.com/dotnet/arcade/pull/7403#pullrequestreview-675774604 comment❔

2021-06-04 00:28 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +        [Output]
Looks like we use it as output here: https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/ProjectTemplates/GenerateContent.targets#L45-L52.

2021-06-04 00:31 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +        [Output]
Though I think it may be more correct to set the value to the value escaped by https://github.com/aspnet/BuildTools/blame/main/src/Internal.AspNetCore.BuildTasks/GenerateFileFromTemplate.cs#L55.

We could probably also separate it out into a separate out parameter like `ResolvedOutputPath` or `EscapedOutputPath` but so far we haven't run into any issues in our builds due to this being an `Output` parameter so I would prefer if we don't block on this change and file followup issues to address.

2021-06-04 00:34 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            StringBuilder sb = new();
I believe testing should be included in the PR that introduces the functionality.

2021-06-04 00:35 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +        [Output]
This path is never set by this code. Marking it output is incorrect, since it doesn't actually output anything.  We should not be checking in new, incorrect, code.

2021-06-09 00:07 UTC, JunTaoLuo commented on src/Microsoft.DotNet.Build.Tasks.Templating/GenerateFileFromTemplate.cs
> +            StringBuilder sb = new();
Tests added.

2021-06-09 00:28 UTC, ChadNedzlek approved these changes

2021-06-09 00:41 UTC, ChadNedzlek approved these changes

2021-06-09 20:49 UTC, merged

2021-06-09 20:55 UTC, ViktorHofer commented
🎉🎉🎉