enable cg2 by default in sharedfx
dotnet/arcade pull request #7476
Opened 2021-06-07 21:59 UTC by mangod9

Updating sharedfx.targets to use crossgen2 by default for ReadyToRun, similar change has been done within the [sdk ](https://github.com/davidwrighton/sdk/blob/94febe75edde0d224f1e5b3aa9260075b9e783cf/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets#L16)but that doesnt seem to take effect while building with sharedFx.targets. 

With active work to decomm crossgen1 need to get this propagated to all repos so we could resolve any outstanding issues. 

I have validated that WindowsDesktop repo does use crossgen2 if I manually update its sharedFx.targets with this change.

2021-06-07 22:03 UTC, davidwrighton approved these changes

2021-06-07 22:06 UTC, jkoritzinsky approved these changes

2021-06-07 22:08 UTC, trylek approved these changes
Awesome, thank you!

2021-06-07 22:17 UTC, AntonLapounov requested changes
I think that setting `PublishReadyToRun` should be moved to sharedfx.props. That way SDK will set `PublishReadyToRunUseCrossgen2` to `true`.

2021-06-07 22:19 UTC, jkoritzinsky commented
We can't move it there because the PlatformPackageType property is set in the user's project file, and the sharedfx.props file gets imported before properties there are read.

2021-06-07 22:32 UTC, mangod9 commented
yeah tested by moving it to props, but `PublishReadyToRun` is not set if moved.

2021-06-07 22:41 UTC, AntonLapounov commented
That is unfortunate. We should probably remove the `'$(PublishReadyToRun)' == 'true'`  condition from this SDK line: https://github.com/dotnet/sdk/blob/751fb14a10203d201b18ec8557f8422e13afe998/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets#L14

2021-06-07 22:41 UTC, AntonLapounov approved these changes

2021-06-08 00:10 UTC, mangod9 commented
> We should probably remove the '$(PublishReadyToRun)' == 'true' condition from this SDK
yeah might make sense to do that change. Let me merge this and we can undo once the SDK change makes it through.

2021-06-08 00:10 UTC, merged