Update workload pack tasks
dotnet/arcade pull request #7614
Opened 2021-07-13 20:12 UTC by joeloff

- Extract ProductLanguage into JSON manifest - these will be needed in the CLI to detect related products when dealing with upgrades for manifest MSIs
- Remove icon file from generated csproj
- Only add pack dependencies if they exist

2021-07-13 22:11 UTC, joeloff commented
@pjcollins hold off on reviewing, there's another fix that needs to go into this to extract more information we need in the CLI

2021-07-13 22:15 UTC, pjcollins requested changes

2021-07-13 22:15 UTC, pjcollins commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
If we remove this `<None Include=Icon.png />` item declaration we'll start seeing this error again on the xamarin/maui side of things:
```
    C:\Program Files\dotnet\sdk\5.0.301\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5046: The icon file 'Icon.png' does not exist in the package.
```

I think your build environment pulls in these props/targets files somewhere:
 https://github.com/dotnet/arcade/blob/74cdaee7ed783cba433fb80f0356e3a7312b62a8/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L20-L21
 https://github.com/dotnet/arcade/blob/74cdaee7ed783cba433fb80f0356e3a7312b62a8/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.targets#L49-L51
 
 This appears to be what is causing the `NU5118` duplicate content warning you are seeing. Maybe we can add something to remove the other icon before including this one, or make this inclusion of the new icon conditional:

```xml
<None Remove="$(PackageIconFullPath)" />
```
or
```xml
<None Include="Icon.png" Condition=" @(None->'%(Identity)') != '$(PackageIconFullPath)' " />
````

2021-07-13 23:55 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
Good point. Let me see about adding the conditional to the generated project

2021-07-14 00:50 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
I ended up just suppressing this. I think there are after targets that might get pulled in, because I ran into this in dotnet/installer, but are not seeing it in dotnet/runtime.

2021-07-14 00:54 UTC, joeloff commented
Here's a sample of what the new metadata will look like. We're extracting the Upgrade table (if present). Otherwise, we need to make make DB calls to extract the information from the MSI at install time and that would add a lot more complexity to the CLI logic. @dsplaisted as an FYI 

So turning this

![image](https://user-images.githubusercontent.com/7409981/125543692-5f4b37f8-2208-4dd6-ae65-8b76970e5b9d.png)

into

```
"RelatedProducts": [
        {
            "UpgradeCode": "{08747630-CB79-3B55-860C-EBEE4EE0C769}",
            "VersionMin": null,
            "VersionMax": {
                "Major": 1,
                "Minor": 2,
                "Build": 2,
                "Revision": -1,
                "MajorRevision": -1,
                "MinorRevision": -1
            },
            "Language": "1033",
            "Attributes": 1
        },
        {
            "UpgradeCode": "{08747630-CB79-3B55-860C-EBEE4EE0C769}",
            "VersionMin": {
                "Major": 1,
                "Minor": 2,
                "Build": 2,
                "Revision": -1,
                "MajorRevision": -1,
                "MinorRevision": -1
            },
            "VersionMax": null,
            "Language": "1033",
            "Attributes": 2
        }
    ]
```

2021-07-14 14:05 UTC, pjcollins commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
As long as we're ok with hiding all other potential `PackagePath` conflicts I think this should be fine.

2021-07-14 15:44 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
@chcosta is there a bug in the Arcade SDK (ProjectDefaults.targets)

```
<!--
    Include package icon in the package.
  -->
  <ItemGroup Condition="'$(PackageIcon)' != '' and '$(IsPackable)' == 'true'">
    <None Include="$(PackageIconFullPath)" Pack="true" PackagePath="$(PackageIcon)" Visible="false" />
  </ItemGroup>
```

When I set PackageIcon in my .csproj, this condition for the item group becomes true and it will include a duplicate PackageIcon

2021-07-14 15:47 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
Looking

2021-07-14 16:05 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
Is the goal to have no icon, or to switch icons?  if it's to switch icons, then that should be done by defining something like this defined in your project

``` MSBuild
<PropertyGroup>
  <PackageIconFullPath>$(yourpathtoanicon)\YourIcon.png</PackageIconFullPath>
</PropertyGroup>
```

Then Arcade will handle the definition of the `None` item group

2021-07-14 16:38 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
well, the problem is that the tools generate a csproj and it can be used inside dotnet, but also in other CI environments like Xamarin.

2021-07-14 16:40 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
Sorry, I'm not familiar with the pieces here.  The tool can't generate the property group in the csproj?

2021-07-14 16:43 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
No, it does

```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IsPackable>true</IsPackable>
    <PackageType>DotnetPlatform</PackageType>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <PackageId>Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100.Msi.arm64</PackageId>
    <PackageVersion>6.0.0-preview.7.21362.9</PackageVersion>
    <Description>Internal toolchain package not meant for direct consumption. Please do not reference directly.</Description>
    <PackageIcon>Icon.png</PackageIcon>
    <Authors>Microsoft</Authors>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
```

2021-07-14 16:56 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
Chatted with @joeloff offline to understand the problem / goal better.  Taking another look

2021-07-14 17:09 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
To recap, the issue is that this project will run both with Arcade sdk imports and without.  Obviously, Arcade isn't set up for this, so if the package icon is defined for the non-Arcade scenario, then when run in the Arcade scenario, you end up with a duplicate content warning.

The way I could see Arcade's definition being disabled and making this consistent is to do something like this (untested)

```XML
<PropertyGroup>
  <PackageIcon />
</PropertyGroup>

<Target Name="AddPackageIcon"
        BeforeTargets="GenerateNuspec">
  <PropertyGroup>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageIconFullPath Condition="'$(PackageIconFullPath)' == ''">Some path to an icon based on the non-Arcade scenario</PackageIconFullPath>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="$(PackageIconFullPath)" Pack="true" PackagePath="$(PackageIcon)" Visible="false" />
  </ItemGroup>

</Target>
```

2021-07-14 17:31 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateManifestMsi.cs
> -            writer.WriteElementString("PackageIcon", "Icon.png");
You might have to define an empty "PackageIcon" property so that Arcade doesn't provide defaults and then adds the item group for you.

2021-07-14 17:37 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateManifestMsi.cs
> -            writer.WriteElementString("PackageIcon", "Icon.png");
I ran under Arcade SDK in dotnet/installer and it seems to work, but I will condition the target

2021-07-14 17:39 UTC, chcosta commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateManifestMsi.cs
> -            writer.WriteElementString("PackageIcon", "Icon.png");
If it works, that's great.  I wouldn't think the target would need a condition.  I just thought you would have to undefine packageicon in your project to prevent [this](https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.targets#L49-L51) from executing.  Perhaps I'm missing something though.

2021-07-14 19:32 UTC, pjcollins commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
This still doesn't work for me, if we want to use this new target I think it needs to run before `_GetPackageFiles` as well. We could change this:
```xml
<Target Name="AddPackageIcon"
        BeforeTargets="$(GenerateNuspecDependsOn)"
        Condition="'$(PackageIcon)' == ''">
```

Or we could skip the target and add conditions to the existing property/item, similar to was mentioned earlier:
```xml
    <PackageIcon Condition="'$(PackageIcon)' == ''">Icon.png</PackageIcon>
```
```xml
    <None Include="$(PackageIcon)" Pack="true" PackagePath="$(PackageIcon)" Visible="false" Condition=" @(None->'%(PackagePath)') != '$(PackageIcon)' " />
```

2021-07-14 19:45 UTC, joeloff commented on src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
> -            WriteItem(writer, "None", iconFileName, string.Empty);
I think we should have this resolved now. I updated to GenerateNuspecDependsOn

2021-07-14 20:22 UTC, pjcollins approved these changes
The latest icon related changes appear to be working for me.

2021-07-14 23:19 UTC, merged