Enable or disable telemetry
dotnet/arcade pull request #7638
Opened 2021-07-16 18:24 UTC by epananth

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

Added ability to turn off telemetry in Telemetry.cs 

was able to test this in release pipeline -> https://dnceng.visualstudio.com/internal/_build/results?buildId=1241503&view=logs&j=d7f318d2-3658-5f56-29df-16b211ec56a6&t=7851342b-b7f6-561e-0dbe-e63708dfa83e

2021-07-16 18:54 UTC, adiaaida commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("DISABLE_TELEMETRY"), out bool telemetrySwitch))
so we are going to have to try parse this environment variable every time we do anything with the telemetry? Why not just save the value away after finding it once?

2021-07-16 18:55 UTC, adiaaida commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("DISABLE_TELEMETRY"), out bool telemetrySwitch))
Also, I might rename this to `SIGNTOOL_DISABLE_TELEMETRY` just to distinguish it from like.... other places that might have the same sort of environment varaible.

2021-07-16 19:49 UTC, epananth commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("DISABLE_TELEMETRY"), out bool telemetrySwitch))
Sure will do

2021-07-19 16:49 UTC, epananth commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("DISABLE_TELEMETRY"), out bool telemetrySwitch))
done

2021-07-19 16:53 UTC, adiaaida commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +        private static bool disableTelemetry;
I would follow the naming convention established above and call this _disableTelemetry

2021-07-19 16:54 UTC, adiaaida commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +                telemetrySwitch = false;
you can just return false here.

2021-07-19 16:55 UTC, adiaaida approved these changes
I'm happy with this, but make sure Chris gets a chance to review

2021-07-19 17:50 UTC, epananth commented
@chcosta  can you please take a look at this before I merge this change?

2021-07-19 18:16 UTC, chcosta requested changes

2021-07-19 18:16 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("SIGNTOOL_DISABLE_TELEMETRY"), out bool telemetrySwitch))
nit: you can return true if _disableTelemetry is true instead of checking / parsing the env variable again.

2021-07-19 18:16 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("SIGNTOOL_DISABLE_TELEMETRY"), out bool telemetrySwitch))
In fact, you don't need a function, you can just move this into the constructor.  Probably don't make _disableTelemetry static because it could lead to unexpected behavior if somehow a shared instance  started running and flipped the value, instead mark it readonly and init it in the constructor.

2021-07-20 19:04 UTC, epananth commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +            if (!bool.TryParse(Environment.GetEnvironmentVariable("SIGNTOOL_DISABLE_TELEMETRY"), out bool telemetrySwitch))
done

2021-07-20 19:46 UTC, chcosta commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +                                && string.Equals(Environment.GetEnvironmentVariable("SIGNTOOL_DISABLE_TELEMETRY"),"true"));
I don't think the comparison against "true" is interesting.  Someone might say "True" or "TRUE" or "1" or something else, and that's fine.  If the variable is not empty, I think that's sufficient to say "disable this".

2021-07-20 19:46 UTC, chcosta approved these changes
Remove the "true" explicit check and this LGTM

2021-07-20 19:57 UTC, epananth commented on src/Microsoft.DotNet.SignTool/src/Telemetry.cs
> +                                && string.Equals(Environment.GetEnvironmentVariable("SIGNTOOL_DISABLE_TELEMETRY"),"true"));
done!

2021-07-20 20:48 UTC, merged