update System.Text.Encodings.Web version
dotnet/arcade pull request #8152
Opened 2021-11-08 22:31 UTC by epananth

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

Issue -> https://github.com/dotnet/core-eng/issues/14879

2021-11-08 22:39 UTC, riarenas requested changes
This is a version downgrade.

2021-11-08 22:39 UTC, riarenas commented on eng/Versions.props
> +    <SystemTextEncodingsWebVersion>4.7.1</SystemTextEncodingsWebVersion>
This looks like a downgrade to me?

2021-11-08 22:40 UTC, riarenas commented
I think what you want to do is find which project is bringing in 4.6.0, and update that one. Downgrading versions.props to use 4.7.1 does not seem right to me.

2021-11-09 00:34 UTC, epananth commented
Closing this PR out. This isn't the correct way to resolve this

2021-11-09 00:34 UTC, closed without merging