Expose a property to specify additional app arguments to pass through xharness
dotnet/arcade pull request #8705
Opened 2022-03-31 16:29 UTC by jkoritzinsky

cc: @premun 

This is in support of the new merged test runners in dotnet/runtime. cc: @trylek

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2022-03-31 17:22 UTC, premun requested changes
@jkoritzinsky this won't be enough for things to work I am afraid.

This property would need to be plumbed through more to work.
1. Create the property in `CreateXHarnessAppleWorkItems.cs`
2. Pass it to the Helix job it creates, add it to the default command
3. Receive it in the `.ps1` and `.sh` payload scripts and store into variables

There is also another way to control the XHarness call fully via the `CustomCommands` metadata that you can supply (these are custom xharness commands that will be executed) but plumbing the property might work nicely too. Not sure which one is a preference

2022-03-31 17:27 UTC, jkoritzinsky commented
It looks like it's already plumbed through on the Apple side: https://github.com/dotnet/arcade/blob/e0b311bcd81fc9e27bcf7715dcda62fa38dfa49a/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAppleWorkItems.cs#L236
https://github.com/dotnet/arcade/blob/e0b311bcd81fc9e27bcf7715dcda62fa38dfa49a/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh#L15

Is there a place I'm missing that it needs to be added to?

2022-03-31 17:30 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/XHarnessRunner.targets
> +    <CreateXHarnessAndroidWorkItems Apks="@(XHarnessApkToTest)" IsPosixShell="$(IsPosixShell)" AppArguments="$(XHarnessAppArguments)">
@jkoritzinsky oh, I got confused because you changed Android by mistake probably.

If it's plumbed on Apple side then just fix this and we're good to go!

2022-03-31 17:33 UTC, jkoritzinsky commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/XHarnessRunner.targets
> +    <CreateXHarnessAndroidWorkItems Apks="@(XHarnessApkToTest)" IsPosixShell="$(IsPosixShell)" AppArguments="$(XHarnessAppArguments)">
I wanted to use this on both Android and Apple. Is this only plumbed through on Apple and not on Android? It looks like it's supported in Android as well: https://github.com/dotnet/arcade/blob/e0b311bcd81fc9e27bcf7715dcda62fa38dfa49a/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAndroidWorkItems.cs#L140

2022-04-01 07:44 UTC, premun commented on src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/XHarnessRunner.targets
> +    <CreateXHarnessAndroidWorkItems Apks="@(XHarnessApkToTest)" IsPosixShell="$(IsPosixShell)" AppArguments="$(XHarnessAppArguments)">
Ah, it's already implemented in the base class. My bad, I wanted to give a quick review yesterday evening to unblock you but I should have read the code more carefully. I will review everything properly today

2022-04-01 10:18 UTC, premun commented
@jkoritzinsky I am reviewing the code and I think the code is not 100% correct. I think it did work at some point but the code changed then and this was not migrated well

- The `xharness-helix-job.android.sh` and `.ps1` scripts are missing plumbing of this parameter
- `AppArguments` are wrapped in `"` and so if you used `"` within them things will break

I'm not sure whether it's better to remove this functionality and use `CustomCommands` or if we should plumb this through

2022-07-02 18:21 UTC, jkoritzinsky commented
I'm going to close this as I found an alternative solution and don't have cycles to finish this

2022-07-02 18:21 UTC, closed without merging