Sbom for vs insertion
dotnet/arcade pull request #8781
Opened 2022-04-06 04:45 UTC by epananth

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

Tests 
Winforms-designer ->

2022-04-06 21:36 UTC, JoeRobich reviewed
Excited to see this get in. Will this be back-ported to Arcade 6?

2022-04-06 21:36 UTC, JoeRobich commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      Text="Cannot file SBOM file, so not going to generate vs manifest!" />
```suggestion
      Text="Cannot find SBOM file, so not going to generate vs manifest!" />
```

2022-04-06 21:36 UTC, JoeRobich commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +  <Message Text="Completed generating SBOM manifest." Importance="high"/>
```suggestion
    <Exec Command = "$(DotNetTool) $(NUGET_PACKAGES)microsoft.manifesttool.crossplatform\$(MicrosoftManifestToolCrossPlatformVersion)\Content\Microsoft.ManifestTool.dll generate -b $(ArtifactsDir)Vsix -m $(ArtifactsDir)sbom -pn VsInsertion -V Verbose"/>
    <Message Text="Completed generating SBOM manifest." Importance="high"/>
```

2022-04-07 00:24 UTC, epananth commented
> Excited to see this get in. Will this be back-ported to Arcade 6?

Yes I am planning to back port this change to release/6.0

But unfortunately when I did more tests in winforms-designer repo I found another bug in Swix package

![image](https://user-images.githubusercontent.com/47157394/162096229-0da3412f-d82a-40cd-b9a4-c430b86cc415.png)

I am talking with that team to get this sorted before I can merge this change.

2022-04-07 18:04 UTC, mmitche commented on eng/common/internal/Tools.csproj
>      <RestoreSources Condition="'$(UsingToolIbcOptimization)' == 'true'">
We can just remove this, since the feed will be added whether Ibc is used or not.

2022-04-07 18:05 UTC, mmitche commented on eng/common/internal/Tools.csproj
>      <RestoreSources Condition="'$(UsingToolIbcOptimization)' == 'true'">
Is this RestoreSources necessary at all? The nuget.config in the same dir has the feed. Generally it would be preferable to use that and not RestoreSources, since the feed checkers will miss property based restore sources.

2022-04-07 18:07 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +    <MakeDir Directories="$(ArtifactsDir)sbom"/>
This can be collapsed into one MakeDir separated by `;`, since Directories is an ItemGroup

2022-04-07 18:09 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
What happens if there are multiple SBOMs to generate (multiplate vsman files)? I think they would get generated in parallel, which would mean that it would try to overwrite this file. It seems like the SBOM location should vary based on the VSIX

2022-04-07 18:11 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +  <Target Name="_BuildManifest" DependsOnTargets="_SetManifestBuildVersion;GenerateSetupManifest;AddSBOM" />
Where does `AddSBOM` come from? I would add some comments as to where it's coming from, why we're depending on it, and what the required input properties are.

2022-04-07 18:11 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Condition="!Exists('$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json')"
Should this be checking for the existence of SBOMFileLocation. I assume that's what AddSBOM wants?

2022-04-07 18:12 UTC, mmitche requested changes
A few questions about nuget configuration and parallelism.

2022-04-07 18:49 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
ahh, I think, its a small change, I will make the change and test my changes on vsUnitTesting-Sign that has multiple vsman files..

2022-04-07 19:01 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
So one thing is even though there are multiple VSIX files, it all unpacks in the same directory. So no matter how many VSIX files we have one SBOM for this.. So this code should handle it,

I will run a test to make sure though..

2022-04-07 19:12 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +  <Target Name="_BuildManifest" DependsOnTargets="_SetManifestBuildVersion;GenerateSetupManifest;AddSBOM" />
GenerateSetupManifest and AddSBOM both are targets in Microsoft.VisualStudioEng.MicroBuild.Plugins.SwixBuild.targets 

I will add a comment here..

2022-04-07 19:22 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Condition="!Exists('$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json')"
I added this here, there was no logs if the sboms were getting included initially. 

Then we want this to fail if there are no sboms getting generated, else the check in vs insertion will fail at a the later stage.. I feel it will be good to catch this error here... I can change this to warning atleast.. 

AddSBOM task does not log anything, so this error might get swallowed..

2022-04-07 19:23 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Condition="!Exists('$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json')"
Also AddSbom task is used to add SBOM link to vsmanifest.. It does not check if the SBOM is created or not..

2022-04-07 20:15 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
As discussed, we want one SBOM for one VSIX.. I will update this code..

2022-04-07 20:16 UTC, epananth commented
Discussed that we need one SBOM per VSIX, its a small change.. Will update the code and have the test on this.

2022-04-07 20:42 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <MergeManifest Include="@(_PackageStubFiles->'$(SetupOutputPath)%(Filename).json')">
THIS IS THE ERROR! :(

2022-04-20 00:12 UTC, tmat commented on eng/common/internal/Tools.csproj
>      <RestoreSources Condition="'$(UsingToolIbcOptimization)' == 'true'">
RestoreSources  should be removed.

2022-04-20 00:42 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
>BUILD_SOURCESDIRECTORY [](http://example.com/codeflow?start=26&length=22)

BUILD_SOURCESDIRECTORY is not defined when building locally. Use predefined Artifacts properties.

2022-04-20 01:07 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +     <MakeDir Directories="$(ArtifactsDir)Vsix"/>
>ArtifactsDir [](http://example.com/codeflow?start=29&length=12)

Ideally, we would use `$(VisualStudioSetupIntermediateOutputPath)` directory for temporary files related to VSIXes.
This directory will have a subdirectory for every component and that subdirectory will contain *.stub files (one for each VSIX merged into this component). See `_StubFiles` and `_StubDirs` items defined above.

2022-04-22 08:51 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Condition="!Exists('$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json')"
AddSbom is no longer required now. 

The reason it did not call the task earlier was it was not able to find the sbom and there was no log that mentioned that. After extensive testing I came to the conclusion after setting the recognizable path for sbom, I am able to generate vsmanifest

2022-04-22 08:51 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
Cannot use $(ArtifactsDir) as it is null at this point.

2022-04-22 08:51 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +     <MakeDir Directories="$(ArtifactsDir)Vsix"/>
VisualStudioSetupIntermediateOutputPath I got an error when I tried to create temp dir here..

2022-04-22 08:52 UTC, epananth commented on eng/common/internal/Tools.csproj
>      <RestoreSources Condition="'$(UsingToolIbcOptimization)' == 'true'">
Done

2022-04-26 16:26 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
I think @tmat is right. The reason it's empty is the project is invoked via an MSBuild task. The thing to do is to add the artifacts dir to the _Args https://github.com/dotnet/arcade/pull/8781/files#diff-12362a14f25b6014a544f7e422afae9a1699a7e6998af5aba61120da75fc094fR51 list that gets passed to the task. Then you can eliminate the dependence on BUILD_SOURCESDIRECTORY.

2022-04-26 16:27 UTC, mmitche commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +     <MakeDir Directories="$(ArtifactsDir)Vsix"/>
What does the `VisualStudioSetupIntermediateOutputPath ` directory point to?

2022-04-26 16:28 UTC, mmitche requested changes
Looks good so far. I'd just like to see the removal of dependence on the AzDO properties.

2022-05-09 23:14 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <SBOMFileLocation>$(BUILD_SOURCESDIRECTORY)\artifacts\sbom\spdx_2.2\manifest.spdx.json</SBOMFileLocation>
Changed this to artifactsDir

2022-05-09 23:15 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets
> +     <MakeDir Directories="$(ArtifactsDir)Vsix"/>
This is the dir - D:\a\_work\1\s\artifacts\VSSetup.obj\Release\

2022-05-09 23:16 UTC, epananth commented
Test build VSUnitTesting repo => https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6129271&view=results

2022-05-09 23:23 UTC, epananth commented
Winform-desginer -> https://dnceng.visualstudio.com/internal/_build/results?buildId=1761178&view=results

2022-05-10 15:10 UTC, mmitche approved these changes

2022-05-10 18:26 UTC, merged

2022-05-10 18:27 UTC, mmitche commented
WOOP WOOP! Yes!