Vs insertion Sbom generation (Roslyn,fSharp)
dotnet/arcade pull request #9629
Opened 2022-06-09 17:57 UTC by epananth

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2022-06-09 18:22 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Inputs="@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\%(Name)')"
>$(ArtifactsDir)VSSetup\$(Configuration)\Insertion [](http://example.com/codeflow?start=34&length=49)

This should be `$(VisualStudioSetupInsertionPath)`

2022-06-09 18:23 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Outputs="@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\$(ComponentName)\%(Name)')"
>$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\$(ComponentName) [](http://example.com/codeflow?start=35&length=66)

This should be `$(ComponentIntermediateOutputPath)`

2022-06-09 18:24 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <MakeDir Directories="$(ComponentIntermediateOutputPath)$(ComponentName)\Sbom;$(ComponentIntermediateOutputPath)$(ComponentName)\unpacked"/>
>ComponentIntermediateOutputPath [](http://example.com/codeflow?start=28&length=31)

Already includes ComponentName in the path.

2022-06-09 18:31 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Outputs="@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\$(ComponentName)\%(Name)')"
>@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\$(ComponentName)\%(Name)') [](http://example.com/codeflow?start=17&length=94)

Should be the path to the generated SBOM: `@(_VsixFileInfo->'$(ComponentIntermediateOutputPath)\%(Name)\sbom\spdx_2.2\manifest.spdx.json'`


Let's make the directory structure like so:
```
$(ComponentIntermediateOutputPath)\%(Name)\unpacked <- vsix unpackaged to this dir
$(ComponentIntermediateOutputPath)\%(Name)\sbom   <- sbom generated to this dir.
```

2022-06-09 18:31 UTC, tmat commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Condition="'$(GenerateSbom)' != 'false'">
>Condition="'$(GenerateSbom)' != 'false'" [](http://example.com/codeflow?start=8&length=40)

Remove the condition and the variable, we should always generate sbom

2022-06-09 18:51 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Inputs="@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\%(Name)')"
I cannot access $(VisualStudioSetupInsertionPath) at that stage, probably I need to pass that. For testing purpose I have used $(ArtifactsDir), I will pass $(VisualStudioSetupInsertionPath)

2022-06-14 00:18 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Outputs="@(_VsixFileInfo->'$(ArtifactsDir)VSSetup\$(Configuration)\Insertion\$(ComponentName)\%(Name)')"
Updated this

2022-06-14 00:18 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +        Condition="'$(GenerateSbom)' != 'false'">
yes this was only temp, reverted this

2022-06-14 00:18 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <MakeDir Directories="$(ComponentIntermediateOutputPath)$(ComponentName)\Sbom;$(ComponentIntermediateOutputPath)$(ComponentName)\unpacked"/>
reverted this

2022-06-14 00:21 UTC, epananth commented
Vs-code-debugger -> https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6274569&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=cad3d46b-5f74-58eb-de70-3c25ea3898bd&l=940

Fsharp fails cos of this issue -> https://github.com/microsoft/dropvalidator/issues/455

Roslyn ->

2022-06-15 18:30 UTC, mmitche reviewed
Looks generally good. Can you add a description to the PR indicating what the current problem is, what the changes are to solve it?

2022-06-15 19:10 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Sure will do

2022-06-15 19:10 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Sure will do

2022-06-15 19:11 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
We are just parsing the file to get the contents of it. I will add comments on what is expected. This pretty much the same file as before, but has one extra parameter I don't think we need to check that.

2022-06-15 19:22 UTC, riarenas commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Text="Visual Studio component '$(ComponentName)' contains multiple VSIX files with different versions: @(_VsixVersionNoDuplicates->'%(VsixFileName) (version %(Identity))', ', ')"
Maybe the error message should mention that all versions need to match for sbom generation? if I got this error I wouldn't understand what's wrong about having different versions in my components, which doesn't seem that strange (if a new vsix is added it doesn't seem weird to me that it would have a different version than existing ones)

2022-06-15 19:22 UTC, riarenas commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Yep I didn't really understand this block either so comments seem necessary.
I find it helpful whenever you're splitting something by index to have an example of what each section is trying to extract. 

Can `$([MSBuild]::ValueOrDefault('%(_StubLine.Identity)', '').Split('/')` be assigned to something and then we just pick up the different parts?

2022-06-15 19:36 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +    <Error Text="Visual Studio component '$(ComponentName)' contains multiple VSIX files with different versions: @(_VsixVersionNoDuplicates->'%(VsixFileName) (version %(Identity))', ', ')"
Actually for sbom generation we are just using the Vsix version. This error msg is specifically for VS manifest generation. So I am going to add something like
```
"Cannot generate VS manifest because Visual Studio Component '$(ComponentName)' contains multiple VSIX files with different versions: @(_VsixVersionNoDuplicates->'%(VsixFileName) (version %(Identity))', ', ')" 
```

This way we will know that vs manifest is not generated cos of version error.

2022-06-15 19:37 UTC, epananth commented
adding an example to make this part clearer..

2022-06-15 19:43 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Added example to this

2022-06-15 20:04 UTC, mmitche approved these changes

2022-06-15 20:06 UTC, riarenas commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Thanks for the example. How about the duplication in lns 60-62? can we set a property that has the split stub line and then just pick up the different parts, instead of splitting things 3 times?

2022-06-15 20:16 UTC, riarenas requested changes
Not a big deal but I'd like my comment to be addressed (even with a "not possible")

https://github.com/dotnet/arcade/pull/9629/files#r898372524

2022-06-15 20:29 UTC, epananth commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Sorry @riarenas missed that second part, I can do it but this will mean I need to test the whole thing again before I get this PR approved. How about I get this merged and create a new PR just for this update?

2022-06-15 20:32 UTC, riarenas commented on src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.SetupPackage.vsmanproj
> +      <_ParsedLine Include="@(_StubLine)"
Sure.

2022-06-15 20:32 UTC, riarenas approved these changes

2022-06-15 20:36 UTC, merged

2022-06-16 00:35 UTC, epananth commented
@riarenas I was trying to split that once, like you suggested. But I was not successful, so I asked @alexperovich and he mentioned I should probably move that a different task and is probably not worth it. So I don't think I will be able to do that.