Support wixpack signing in Sign.proj
dotnet/arcade pull request #9721
Opened 2022-06-17 19:40 UTC by mmitche

Wixpacks were implemented for post-build signing to allow us to sign MSIs and bundles after the build was done. They are a separate zip file that contains the files necessary to reconstruct an installer. Prior to post-build signing, repositories producing installers typically signed the files going into the installer, then created the installer, then signed it. Potentially there were other stages for nested installers, dealing with bundles, etc.

There is a push to add back in-build signing. The in-build staged installer creation/signing steps have been removed from some repos. Rather than add these back, it makes more sense to enable signing installer as part of the normal signing process, which happens just before the publish stage of the build. Here the files to be signed are analyzed, unpacked, signed, and repacked.

To do this, we need a tweak to Arcade to send the path to the wix tooling to the sign task. If a repo produces no installers or wixpacks, this tooling will be unused.

While doing this, I also unified some of the wix tooling packages in use to use the same version of the package.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

2022-06-17 19:41 UTC, mmitche commented
See https://dev.azure.com/dnceng/internal/_build/results?buildId=1831326&view=logs&j=09811346-8274-5b72-2d96-1dd38f87c84b&t=484aa08d-83e1-520a-76ed-fc8b43244d09&l=469 for an installer build where this was used.

2022-06-17 20:35 UTC, joeloff submitted a review, later dismissed

2022-06-19 21:38 UTC, AraHaan requested changes
Also plans to update the WixTools part of the SharedFramework SDK which is also outdated (can could benefit from using ``$(MicrosoftSignedWixVersion)``.

2022-06-19 21:38 UTC, AraHaan commented on eng/Versions.props
> +    <MicrosoftSignedWixVersion>1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
Please update this to 3.14.0.6526.

2022-06-19 21:38 UTC, AraHaan commented on src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props
> +    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
Please update this to 3.14.0.6526.

2022-06-19 21:41 UTC, AraHaan commented on eng/Versions.props
> +    <MicrosoftSignedWixVersion>1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
```suggestion
    <MicrosoftSignedWixVersion>1.0.0-v3.14.0.6526</MicrosoftSignedWixVersion>
```

2022-06-19 21:41 UTC, AraHaan commented on src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props
> +    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
```suggestion
    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.6526</MicrosoftSignedWixVersion>
```

2022-06-20 02:54 UTC, joeloff commented on src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props
> +    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
That package doesn't exist. This is an internal package of WiX and we haven't created a copy using the newer binaries.

2022-06-20 04:06 UTC, AraHaan commented on src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props
> +    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
I see, is that in the todo?

2022-06-20 05:57 UTC, joeloff commented on src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props
> +    <MicrosoftSignedWixVersion Condition="'$(MicrosoftSignedWixVersion)' == ''">1.0.0-v3.14.0.5722</MicrosoftSignedWixVersion>
We probably won't take the new version. The only fixes were for VS 2022 support (we don't ship the VSIX) and some localization updates.

2022-06-21 17:32 UTC, missymessa submitted a review, later dismissed
Looks like the build of this broke, but after that's fixed...

LGTM ![shipit](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)

2022-06-28 15:52 UTC, mmitche commented
> Also plans to update the WixTools part of the SharedFramework SDK which is also outdated (can could benefit from using `$(MicrosoftSignedWixVersion)`.
> 
> I would love to update it myself, but since this PR would make it needless I think it should be updated here as well.

@AraHaan Do you have the 1.0.0-v3.14.0.6526 package around? It's not available.

2022-06-28 16:01 UTC, joeloff commented
@mmitche the WiX package we use is an internal build that is signed with additional certificates. It's currently produced from an internal pipeline.

2022-06-29 16:32 UTC, joeloff approved these changes

2022-06-29 16:32 UTC, merged