Central version
dotnet/arcade pull request #9885
Opened 2022-07-05 22:58 UTC by ChadNedzlek

Use central package versions to help pulling versions forward be easier.

Had to suppress a few new warnings and, in a few places, override the versions backward
because of breaking changes.

If this doesn't break the world, I'll be shocked.

2022-07-05 23:16 UTC, alexperovich submitted a review, later dismissed

2022-07-06 20:49 UTC, joeloff submitted a review, later dismissed
SignCheck and workload changes look fine to me, thank you.

2022-07-06 20:49 UTC, adiaaida submitted a review, later dismissed

2022-07-06 21:11 UTC, rainersigwald submitted a review, later dismissed

2022-07-06 21:11 UTC, rainersigwald commented on src/Microsoft.DotNet.Build.Tasks.Packaging/tests/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
>      <PackageReference Include="@(TestPackage)" />
You might consider migrating to use `PackageDownload` for these; that's a bit cleaner representation of what you want to do with them.

2022-07-06 21:12 UTC, ChadNedzlek commented on src/Microsoft.DotNet.Build.Tasks.Packaging/tests/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
>      <PackageReference Include="@(TestPackage)" />
? Instead of adding them to "PackageReference"?  That would be ideal, because I think that would avoid a lot of mess I had to do.

2022-07-06 21:12 UTC, JoeRobich commented
Since package versions are now stored in both Directory.Packages.props and eng/Versions.props, it seems like it would be hard to keep track of where to update what. Is there any advice on how to manage this cleanly? Such as, only track versions for package subscriptions in Versions.props?

2022-07-06 21:37 UTC, ChadNedzlek commented
@JoeRobich, the package versions were already haphazardly stored... _Most_ were in Versions.props, but some were arbitrarily included verbatim in csprojs (those are the versions that are encoded in Version.props).

I'm not sure what the best route forward is... personally I find Versions.props to be a headache, but it's all the maesto can update, so it needs to be present at least for any package that takes part in dependency flow. In addition, some of the variables defiend in that file are used in various places in arcade... so remove them is going to be a difficult, error prone process (because msbuild tends to just... keep on chugging if you try to use an undefined variable).

We could go the other direction, and put ALL the version in Versions.props, and then just have to indirect everything.  I think a better long term solution is that Maestro understands Directory.Packages.props, and then we wouldn't need Versions.props at all, but we aren't at that place right now.

2022-07-06 21:43 UTC, lbussell commented on Directory.Packages.props
> +    <NoWarn>$(NoWarn);NU1507</NoWarn>
I think the actual solution to this is to add package version mapping, see https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

Otherwise, NuGet will restore all of these packages from whichever feed responds first.

2022-07-06 21:57 UTC, lbussell commented
I started a source-build tarball build locally to see if this affects the prebuilt situation.

2022-07-06 22:32 UTC, ChadNedzlek commented on Directory.Packages.props
> +    <NoWarn>$(NoWarn);NU1507</NoWarn>
Unfortunateyl, Maestro can't work with package mapping, so we can't support it. Especially when release time rolls around, the sources are non-static, so Maestro would have to update all the package mappings every time it modified the feeds.

Given that we already have checks in place in our builds to ensure that all the feeds are safe, this warning is not helpful.  (And the warning really has nothing to do with centralized package management, even without it, you are subject to the same problem, arguably moreso, because you don't actually control indirect dependencies versions... I'm not sure why this warning is tied to this feature, as they are unrelated).

2022-07-06 23:11 UTC, ChadNedzlek commented
List package outputs:
Before: https://gist.github.com/ChadNedzlek/ccfc83115b8139fa187665cdc5b9af5c#file-before-txt
After: https://gist.github.com/ChadNedzlek/ccfc83115b8139fa187665cdc5b9af5c#file-after-txt
Diff: 
Before: https://gist.github.com/ChadNedzlek/ccfc83115b8139fa187665cdc5b9af5c#file-before-txt

2022-07-06 23:34 UTC, lbussell requested changes

2022-07-06 23:34 UTC, lbussell commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
Hardcoded package versions will cause prebuilts or NU1109 Package Downgrade errors during source-build. Microsoft.Bcl.AsyncInterfaces is the only one I see causing this issue locally at the moment. The version should be stored in a property declared in eng/Versions.props so that it can be overridden in source-build.

2022-07-06 23:45 UTC, ChadNedzlek commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
Hrm. It feels like we should consider having source-build and maestro able to handle Directory.Packages.props directly, rather than having to indirect everything. The file format is pretty simple to parse, so it wouldn't be that hard...

But for now, I'll move all the versions over to Versions.props to work around this.

2022-07-06 23:52 UTC, ChadNedzlek commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
Created https://github.com/dotnet/arcade/issues/9902 to discuss using Directory.Packages.props more fully in our infrastructure.

2022-07-07 00:09 UTC, ChadNedzlek commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
Pushed a version with ALL versions in Versions.props for now while the other issue is considered

2022-07-07 08:14 UTC, ViktorHofer commented on src/Microsoft.DotNet.Build.Tasks.Packaging/tests/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
>      <PackageReference Include="@(TestPackage)" />
Note that this is a legacy project and I expect it to go away when migrated all repos off from .pkgprojs.

2022-07-07 08:16 UTC, ViktorHofer commented on src/SignCheck/Microsoft.SignCheck/Microsoft.DotNet.SignCheckLibrary.csproj
> +    <PackageReference Include="NuGet.Versioning" VersionOverride="4.7.0" />
Apart from one test project it looks like this is the only shipping project that requires the version override. We might want to look into if the version override is technically even required or even using a flowing version if just fine.

2022-07-07 19:41 UTC, ChadNedzlek commented on src/SignCheck/Microsoft.SignCheck/Microsoft.DotNet.SignCheckLibrary.csproj
> +    <PackageReference Include="NuGet.Versioning" VersionOverride="4.7.0" />
I tried that. There are a bunch of "signing" types that don't exist in never versions. I tried briefly to see if there was a suitable drop in replacement in newer Nuget versions, but nothing looked quite right, so I overrode them downward.  I didn't like it, but I didn't know what else to do.

2022-07-11 21:02 UTC, ChadNedzlek commented
/azp run

2022-07-12 19:36 UTC, ChadNedzlek commented
/azp run

2022-07-12 20:20 UTC, ChadNedzlek commented
Apparently https://github.com/NuGet/Home/issues/10311 will cause a pretty big mess if we take this right now, so I'm closing this PR. Darn.

2022-07-12 20:20 UTC, closed without merging