Add source-build option to build scripts
dotnet/arcade pull request #9989
Opened 2022-07-13 12:46 UTC by oleksandr-didyk

Resolves https://github.com/dotnet/source-build/issues/2674

CC: @tkapin @MichaelSimons @riarenas

2022-07-13 12:46 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/arcade?pullRequest=9989) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/arcade?pullRequest=9989) before we can accept your contribution.<br/><br/>:x: oleksandr-didyk [sign now](https://cla.dotnetfoundation.org/dotnet/arcade?pullRequest=9989)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/arcade?pullRequest=9989) it.</sub>

2022-07-13 14:02 UTC, tkapin requested changes

2022-07-13 14:05 UTC, tkapin commented
@oleksandr-didyk - could you please also describe how did you test this change?

@riarenas / @markwilkie  - what is your preference regarding reviews of such changes? Do you want to be explicitly called for reviews of changes that might be affecting common arcade pieces such as the entry point scripts?

2022-07-13 14:37 UTC, tkapin commented on eng/common/build.sh
> +      if [[ "$configuration_is_set" == false ]]; then
No, that was exactly what my comment was about, but it wasn't straightforward to realize without going through the branches in the code. One suggestion then - since we are basically setting the default configuration based on whether we are running a regular build or a source-build, it might be more straightforward to set the default configuration to empty and then, after options are processed (and before any other code is sourced), just check if it stayed empty and set it to either Debug or Release, depending on the sourcebuild flag. The advantages would be 1) there wouldn't be any coupling when processing options and 2) you wouldn't need the `configuration_is_set` flag and its corresponding logic at all. Thoughts?

2022-07-13 14:41 UTC, oleksandr-didyk commented on eng/common/build.sh
> +      if [[ "$configuration_is_set" == false ]]; then
Sure, sounds like a better solution.

Thanks for the suggestion, I'll try to incorporate it

2022-07-13 15:22 UTC, tkapin approved these changes
Nice, thanks for accepting my suggestion.

2022-07-18 09:03 UTC, oleksandr-didyk commented
Update: removed left-over flag from changes made before the PR feedback

2022-07-20 19:32 UTC, crummel approved these changes

2022-07-20 22:29 UTC, MichaelSimons submitted a review, later dismissed
I have one question regarding windows.  Overall it looks good.

2022-07-20 22:29 UTC, MichaelSimons commented on eng/common/build.ps1
> +  Write-Host "  -sourceBuild            Source-build the solution (short: -sb)"
Source-build is not supported on Windows.  Should it be noted here or either by logic to error out if this option is used on Windows?  

I am assuming someone can use this script on linux since pwsh is cross platform

2022-07-21 08:16 UTC, oleksandr-didyk commented on eng/common/build.ps1
> +  Write-Host "  -sourceBuild            Source-build the solution (short: -sb)"
Oh, my bad, did not know about that. Thanks for the suggestions, I'll try to have it throw on un-supported platform + add it to do the doc

2022-07-25 08:42 UTC, oleksandr-didyk commented
Update: reverted changes to `\eng\common\build.ps1`

2022-07-26 09:45 UTC, merged